### ISSUE TITLE
Create and tested runbook for replaying consumer events

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#115]
AC:
- [x] Write and test a runbook for replaying events on the consumer. (Can this be public or will we need different versions?)
- [x] Use runbook to test replay of Dec 17 failed events due to production issue (see additional notes).
- [x] Link to runbook from appropriate docs. (In particular public documentation)

Additional notes:
- Test against stage, just in case there are differences from dev. We don't actually need to cause an error, although it might help to prove you actually got updates that you wouldn't have.
- Tim mentioned possibly 1) stopping consumers, 2) updating offset in Kafka, and 3) restarting consumers. What does Confluent think about this plan? Also, do we need to make API call to do this, or can it be done through the UI?
- For Dec 17 clean-up:
  - Communicate to support and warroom.
  - Do a trial run of 1 hour, and then maybe 24 hours, to ensure it works and to learn how long it will take to catch up.

**Comment by robrap** [comment]
@dianakhuang: I've assigned this to you.

**Comment by dianakhuang** [comment]
Draft of runbook: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/266993906/Replay+Events+on+the+Event+Bus

**Comment by robrap** [comment]
@dianakhuang: 
* I made some very minor updates to the runbook.
* I added some links from the[ Event Bus Alerts runbook](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/234258433/Event+Bus+alert+runbook), but these may need to be updated.
* I would like the ["Error Handling" section of the public how-to](https://openedx.atlassian.net/wiki/spaces/AC/pages/3508699151/How+to+start+using+the+Event+Bus) to be updated, but your runbook is currently private. I'd like for it to be public, but it might need to be updated to note that includes private links.

**Comment by dianakhuang** [comment]
Note on testing:
* our test replay replayed significantly more than we expected it to. we believe that this is because we are passing along the incorrect version of the timestamp, in seconds instead of milliseconds or vice versa

**Comment by rgraber** [comment]
We resolved the issue of replaying too far back with https://github.com/openedx/event-bus-kafka/compare/v3.5.0...v3.5.1
