### ISSUE TITLE
Investigate why stage course-discovery worker logs aren't making it to Splunk

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#117]
Production logs are fine, but `sourcetype="kube:container:course-discovery-worker" index="stage-edx"` is empty since about 2022-11-08.

The code in question is running correctly, and the logs are appearing on the workers, but are not making it from the pod to Splunk.  Startup logs do appear to be making it from the pod to Splunk.

Event bus testing on stage is difficult without resolving this.

**Comment by rgraber** [comment]
Fixed with https://github.com/edx/terraform/pull/5039
