### ISSUE TITLE
Fix GoCD email notifications reliability

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#128]
Arch-BOM currently uses GoCD's built in email notifications for edxapp failure notifications. Unfortunately, the emails stop working after GoCD restart, until someone logs in and refreshes the preferences. See https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16386719/edxapp+GoCD+alert+runbook#GoCD-Notifications-Stopped-Firing for more details.

Note that personal notifications from GoCD also stop after a restart.

We have several options for fixing our GoCD OpsGenie alerting so we no longer need a manual step after each restart:
1. Investigate and fix the actual problem. This would solve personal notifications as well. See https://github.com/gocd/gocd/issues/9691#issuecomment-1341126469 for possible next steps, which may just be looking more at GoCD logs.
2. Hack our way around the problem by having an automated job that logs into GoCD once every 30 minutes. (Would require a service account with a username/password login rather than a GitHub login.)
3. Transfer our notifications to the pipeline code. This gets complicated, which is why we wanted to avoid it in the beginning.

Additional Notes:
* Are we sick of this toil? Should we switch to custom/complicated notifications from the pipelines?
* In addition to toil, we missed 2 weeks of notifications at some point, so it is simple to miss doing this update.
* We have on-call checking for a heartbeat notification from GoCD so we can notice when it stops.

A/C:
* We continue receiving alerts even after GoCD restarts
* The documentation is updated accordingly
* Any code needed solely for the old notification mechanism is removed

Implementation notes:
* Another pipeline that works the way we want is https://github.com/edx/edx-internal/blob/d934feb5a91222557ff95f256abc5c46d5e62ca9/gocd/manually-created-pipelines/prospectus.yaml#L180
* The key point is to use "run_if: failed"
* Old edxapp pipeline which did this: https://github.com/edx/edx-internal/blob/b50a49d401e9aca0f70450ace1faed82cbbd3bbd/gocd/manually-created-pipelines/edxapp.yaml
* Kubernetes pipelines equivalent: https://github.com/edx/edx-internal/blob/d934feb5a91222557ff95f256abc5c46d5e62ca9/gocd/generated-pipelines/templates/k8s-gocd-pipeline.yaml.j2#L199

**Comment by arch-bom-gocd-alerts** [comment]
Closed by https://github.com/edx/edx-internal/pull/8736 among others (private link)
