### ISSUE TITLE
Replace whitelist_externals with allowlist_externals in tox file for all repos

### ISSUE THREAD

**Issue by aht007** [edx/edx-arch-experiments#130]
whitelist_externals has been deprecated in tox for a long time. See: [Changelogs](https://github.com/tox-dev/tox/blob/legacy/docs/changelog.rst#deprecations-removal-in-next-major-release).
This came into light when tox was upgraded to version 4.0.0 in upgrade PRs and some PRs failed due to this. For now tox has been pinned to <4.0.0 due to other breaking changes too but we should fix this issue so that whenever we upgrade tox to some version >4.0.0 we don't face this issue again.
A better approach to handle this would be to write a script and run it through bulk repo update job to make all the PRs in one go

**Comment by iamsobanjaved** [comment]
This is now removed in `tox==4.0.0` and we have to replace this with `allowlist_externals` so we are unblocked to upgrade tox to latest version.

Filtered view from Repo Health Dashboard about the usage of `whitelist_externals`: https://github.com/tox-dev/tox/blob/main/docs/changelog.rst#deprecations-and-removals---400rc4

Removal from tox version 4.0.0: https://github.com/tox-dev/tox/blob/main/docs/changelog.rst#deprecations-and-removals---400rc4
