### ISSUE TITLE
Enable New Relic "users impacted" metrics

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#140]
New Relic just added a feature to its [errors inbox](https://docs.newrelic.com/docs/errors-inbox/errors-inbox/) to track the number of unique users impacted by each category of error.  This looks pretty useful for determining whether a high-frequency error is triggered by 1-2 people in some weird state or more broadly affecting the site's users, which is an important factor in prioritization decisions.  Let's make the configuration changes needed to enable this, and also experiment with using the errors inbox for the code we own.

A/C:

1. Read the [getting started guide](https://newrelic.com/blog/nerdlog/error-triage-workflow#toc-get-started-setting-alerts-based-on-users-impacted) for the new feature in order to understand it
2. Follow the [setup instructions](https://docs.newrelic.com/docs/errors-inbox/error-users-impacted/), at least for edx-platform.  We'll probably need to either rename or duplicate the custom attribute we use to identify the user; there may be advantages to picking the attribute name that complies with the OpenTelemetry standard (`enduser.id`)
  * We currently have a [custom attribute named request_user_id](https://github.com/openedx/edx-drf-extensions/blob/2fe20fb5cf092a0b767543a97fde85e2fa782be5/edx_rest_framework_extensions/middleware.py#L107) that we could deprecate. The new id should be set in the same code.
  * For this ticket we only need to update current usages of request_user_id to use the new name, not fill gaps where we have not yet added request_user_id.
3. ~~See if it's possible to create a [workload](https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/workloads/use-workloads/#create) corresponding to the code that Arch-BOM owns; getting the right pieces of edx-platform may be tricky, but it looks like we might be able to leverage the attributes we already use for alerting.~~
4. Look at the errors inbox for the new workload with user impact data and see if it works correctly and/or yields any useful insights on fixes to prioritize.
5. Document your findings and steps to reproduce, which can be followed for other services and/or workloads.
6. Write tickets for any logical next steps.

**Comment by robrap** [comment]
@jmbowman:
1. I added to [edx-drf-extensions 8.4.0](https://github.com/openedx/edx-drf-extensions/releases/tag/8.4.0), so all IDAs will eventually get this automatically once they upgrade.
2. I sent an email and created an arch-bom ticket for top errors in LMS: https://github.com/edx/edx-arch-experiments/issues/154. Note that errors inbox user data may not be critical for the very top errors.
3. I haven't sent any other notifications or documentation. I'm not sure what you want to have happen next. The idea of workloads and an error inbox is something another team could experiment with, and I'm happy to support, but it is really up to other teams whether they want to try it out or not. I'm happy to write an informational email explaining the new metric and these tools.

Let me know your thoughts so I can close out this ticket. Thanks!

**Comment by robrap** [comment]
Did some additional announcing in Slack. Closing.
