### ISSUE TITLE
Fix GoCD pipeline false positive failures with ArgoCD

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#141]
Some pipeline stages have failed due to what looks to simply be an attempt to get info from ArgoCD before it is done. Here is an example: https://gocd.tools.edx.org/go/tab/build/detail/course-discovery-prod/6/deploy_to_prod/1/sync_prod_course_discovery

The potentially most relevant output:
```
    Phase:              Running
    Start:              2022-12-15 21:15:33 +0000 UTC
    Finished:           <nil>
    Duration:           0s

    ...

    FATA[0007] Operation has completed with phase: Running  
    [go] Task status: failed, took: 23.947s, exited: 1

    [go] Current job status: failed
```
It looks like the job failed because the operation is still running. Maybe some retries are needed for getting status?

**Comment by robrap** [comment]
Most of the prod deployment for the discovery consumers have failed. See https://gocd.tools.edx.org/go/pipeline/activity/course-discovery-prod. At least the latest ones have failed for the same reason. Note: this also keeps it from sending a New Relic deploy event.

**Comment by rgraber** [comment]
Addressed with https://github.com/edx/edx-internal/pull/7594
