### ISSUE TITLE
Autorecovery from lost connection error in event bus consumer

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#144]
We found that Django can get into a state where once it loses a sql connection, it does not recover and continues to get the same error for subsequent messages until restarted.

From discovery:

* Django only replaces a broken or over-max-age DB connection at the start of a _request_, which means connections in our infinite loop never never heal.
  * It's not clear if there's a way to make it work more like separate web requests. This would give the quickest recovery, but would be specific to this type of error.
* We're going to try restarting after 5 (or 2, or 3?) failed messages in a row. This would more generally handle other recoverable errors that need a restart, if there are any. This should be done **after** we commit the message, which means that these messages should be re-processed.
  * [x] https://github.com/openedx/event-bus-kafka/pull/105 -- implementation
  * [x] https://github.com/edx/edx-internal/pull/7593 -- set new setting
  * [x] https://github.com/openedx/course-discovery/pull/3751 -- use in course-discovery
  * [x] Update https://openedx.atlassian.net/wiki/spaces/AC/pages/3508699151/How+to+start+using+the+Event+Bus with new recommended settings

**Additional Notes/Questions:**

* I [Robert] don't think we will look further into why this happens in the first place at this time.
* Is it possible to replicate the lost SQL connection locally by running the infinite loop and stopping mySQL, or causing some other db connection issue? This should be time-boxed if attempted.

**Comment by robrap** [comment]
@timmc-edx: Created the issue for better handling of db connection failures here: https://github.com/edx/edx-arch-experiments/issues/158. Feel free to comment or edit. Looks like this ticket can be closed?

**Comment by timmc-edx** [comment]
I think that captures the more DB/Django-specific questions! Closing this one.
