### ISSUE TITLE
Add Github Actions for CI in openedx/xblock-sql-grader

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#146]
Repo: https://github.com/openedx/xblock-sql-grader

As this XBlock has recently moved to our ownership, we want to improve its state. This should run CI on Github Actions as per our organization's standard.

**A/C**
- [x] Add a workflow for CI.
- [ ] Make sure we have the correct requirement files structure as per [OEP-18](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0018-bp-python-dependencies.html)
- [ ] Modify upgrade requirements workflow to tag the Arbi-BOM team.

**Comment by jmbowman** [comment]
Implementation PR: https://github.com/openedx/xblock-sql-grader/pull/70
