### ISSUE TITLE
Re-enable production of catalog info changed events

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#147]
We've had to stop production of catalog info changed events in Studio since it was triggering a race condition in Discovery (due to bidirectional data flow). Checklist for re-enabling:

- [x] Set `SEND_CATALOG_INFO_SIGNAL` back to true in remote-config for stage and prod studio
- [x] Re-enable any disabled conditions in New Relic alert policy `platform-arch-bom-event-bus` (some may have been disabled due to lost-signal conditions caused by lack of events)

**Comment by robrap** [comment]
@timmc-edx: I assume this is out of date and should be closed?

**Comment by timmc-edx** [comment]
Looks like both items are already done. Closing out.
