### ISSUE TITLE
Runbook and implementation of updating devstack sql scripts

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#152]
The devstack sql script should be updated occasionally for several reasons:

1. If someone tries to delete squashed migrations, and the script has only gone through part of the squash, it will break until the script is updated.
2. The script provides a performance boost, but only for the migrations it includes.

Minimally, this should probably be performed for each named release. In theory, this could be automated, but first we should know how to do it manually.

**Acceptance Criteria:**
- [x] Update the devstack sql script.
- [ ] Revert the revert of deleting some squashed migrations: https://github.com/openedx/edx-enterprise/pull/1696
- [x] Create runbook (or how-to) with steps required.

**Additional notes:**
- This was a past ticket with notes: https://2u-internal.atlassian.net/browse/ARCHBOM-1790.  Maybe `make destroy` is required?
- Here are some Slack threads from breaking things because of a delete of squashed migrations:
  - https://twou.slack.com/archives/C04A66RDPEZ/p1671550732367419
  - https://twou.slack.com/archives/C04A66RDPEZ/p1671819685283399

**Comment by rgraber** [comment]
Note: It's possible there's a bug in `update-dbs-init-sql-scripts.sh` When we tried to use it last, the sql scripts it created failed provisioning tests. See https://github.com/openedx/devstack/actions/runs/3767100117/jobs/6404300721

**Comment by robrap** [comment]
Reminder to try `make destroy`.

**Comment by rgraber** [comment]
./update-dbs-init-sql-scripts.sh actually runs make destroy as part of it

**Comment by rgraber** [comment]
Note: Unfortunately it's been long enough that changes have slipped in and we can no longer just revert the revert. I've asked the enterprise team to make another branch for the cleanup.

**Comment by rgraber** [comment]
Wasn't much to the how to besides "run the script," but I added it to https://2u-internal.atlassian.net/wiki/spaces/AT/pages/352190477/Quarterly+Tasks

**Comment by rgraber** [comment]
Also updated https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations#EverythingAboutDatabaseMigrations-Don'trevertcodethatincludesmigrations%2Cdon'tchangeoldmigrations.
