### ISSUE TITLE
Review Arch-BOM owned LMS errors

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#154]
Acceptance Criteria:
- [ ] Complete review and discovery of top errors
- [ ] Create follow-up tasks as needed

The scope of this ticket does not include fixing the errors, the follow-up tickets should cover that.  If there are errors that are deemed unimportant to fix, ticket either preventing them from reaching New Relic or telling New Relic to ignore them.

See following email for general notes:
> Hello Infinity, Aurora and Arch-BOM squads.
>
> Our teams have the top-ranking errors in LMS based on quantity, and as the overall owning team of LMS (Arch-BOM), we'd like to improve (a.k.a. decrease) the baseline error rate.
>
> Depending on the error, we may want to mark it as expected, or you may want to fix the error. Please reach out to me or in #tech-arch-bom with any questions.
>
> Here are some links that may help you:
> 
> * Top LMS errors grouped by squad: https://onenr.io/0bRmNEazzjy
> * Runbook for LMS errors by squad (with dashboard links): https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/19470837/Squad+Owned+LMS+New+Relic+Alert+Runbook
> * LMS Errors inbox (includes users impacted, does not include owning squad): https://onenr.io/02R5g65v0Qb
>
> Thank you.

Arch-BOM seems to have 3 main errors:
1. RelayState
2. Session value state missing
3. Deadlock found

The first two issues are probably SAML related and have been long time issues. We inherited this issue, and it is possible we could mark it expected, or actually work on a fix. Enterprise determined it wasn't worth their time in the distant past. Search JIRA for old tickets.

The deadlock issue may be relatively recent. There were some recent spikes at end of 2022. Seems related to a view used for mobile auth, which recently was updated to support JWTs. See https://onenr.io/0oR8AGpgXjG (data will be gone at end of January). Note that there are other deadlock errors, mostly owned by Aurora, so don't get them confused.

**Comment by robrap** [comment]
@jmbowman: Wondering about adding a "maintainer" label, for work we should do as maintainer?

**Comment by robrap** [comment]
[inform] I may look into SAML related things for Auth right now, so I may end up picking up those errors. Reach out to me to confirm.

**Comment by dianakhuang** [comment]
Double checking on the errors that we are seeing, and it seems like the top 3 over the past month have not changed, though the deadlock errors barely happened in the last 24 hour period while being the top error in the last week. I'll try to see if we can find out more about them.

**Comment by dianakhuang** [comment]
RelayState: can we make this error spit out a more specific and more helpful error message?
Session state value missing: Can we filter it out of our own alert vs. global error? Or put in a threshold?

**Comment by dianakhuang** [comment]
Deadlock: Can modify this particular transaction to be non-atomic.

**Comment by robrap** [comment]
@dianakhuang: Here's some possible next steps:
1. Land your current PR.
2. Create a task for adding throttling to protect against the deadlock issue. We would need to coordinate with Mobile to have them first correct the issue, but otherwise we can just introduce the throttling so Mobile just starts getting errors instead of pounding the backend.
3. Create a task for follow-up on the SAML work, finding a way to deliver the error messages to the end user.
