### ISSUE TITLE
Document how to verify data issues for catalog changed event

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#162]
AC
- [x] Write and find home for docs.
- [x] Share with Rebecca Doris

**Comment by robrap** [comment]
@beckrecca: You showed me the history table in Discovery. See the above comment for details of querying the history table in LMS (proxy for Studio changes), and how I was able to verify that an actual user made the change in Studio that eventually made it over to Discovery.

**Comment by rgraber** [comment]
This is now documented in Confluence: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/340492442/How+to+Verify+Data+for+Catalog+Changed+Event
