### ISSUE TITLE
[Cookies] Alerting for unrecognized large cookies

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#166]
We could create an allow list for large cookies above a certain size, and alert when we see a new one we don't recognize.

Acceptance Criteria
- [ ] Implement new alert and supporting code.
- [ ] Create runbook

Additional notes:
- We could add every last cookie to the allow list, but that seems like more on-call overhead than benefit. Using a threshold for what is considered a large cookie could make this simpler to manage.
- This alert would provide an early warning as soon as a new large cookie were introduced. This would hopefully allow us to provide feedback to someone while they are still working on something, versus the possibility of noticing this months or years later.
- Although the documentation requested in https://github.com/edx/edx-arch-experiments/issues/165 would be better for hopefully helping people avoid this situation, we still need to ensure all is well.

Note: The runbook for the alert might simply be: 1) find owner of new cookie, 2) send link to why and how to avoid large cookies doc (see https://github.com/edx/edx-arch-experiments/issues/165).

**Comment by robrap** [comment]
Feel free to mention in the runbook that this could be iterated on for whomever takes over watching cookies for compliance reasons.

**Comment by robrap** [comment]
* Potentially there is a new "unrecognized_large_cookie_names" custom attribute that can be alerted against.
* You'll need to come up with a cutoff.
* The runbook should note how to add to the recognized allow list of large cookies. Maybe we also update the runbook with notes on each large cookie, or a ticket on how and when it might be fixed.

**Comment by robrap** [comment]
Moving to backlog so we can concentrate on other priorities for now.

**Comment by jristau1984** [comment]
Closing, as this is no longer an Arch-BOM owned concern.  

@kalebjdavenport is this something you would like to port over to your team?

**Comment by kalebjdavenport** [comment]
@jristau1984 I think we could potentially port this over but I would love to wait until the Red Ventures transition has started so we don't port it and then port it again two weeks later 👍
