### ISSUE TITLE
Support Mobile JWT transition

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#17]
This ticket is to support reviews and other help related to switching Mobile auth from the opaque (Bearer) tokens to JWTs. 

## Acceptance Criteria

Provide support, including reviewing the following:

- [x] https://github.com/openedx/edx-platform/pull/30283
- [x] Exchange token for session: https://github.com/openedx/edx-platform/pull/29963 
  - [x] Add grant_type in JWTs: https://github.com/openedx/edx-platform/pull/30519
  - [x] Incorporate grant_type in exchange PR.
  - [x] Add asymmetric only JWT decode method to edx-drf-extensions.
  - [x] Allow asymmetric opt-in for access token requests.
  - [x] Exchange view ensures asymmetric using new method.
- [x] Ensure ADRs are created.
- [ ] Help with rollout. 
  - [ ] Toggle?
  - [ ] New Relic dashboard?
    - [ ] Include custom attributes from https://github.com/openedx/edx-platform/pull/30519/files
  - [ ] Check logs for "Unable to get grant_type from access token." and clean up code.
- [ ] OEP updated. Can replace/archive Confluence doc.

## Notes

* See doc [Mobile authentication with JWTs](https://openedx.atlassian.net/wiki/spaces/AC/pages/3351609433/Mobile+authentication+with+JWTs)
* Internal slack thread here: https://edx-internal.slack.com/archives/CG7FM3BLY/p1652189463755469?thread_ts=1650996699.553789&cid=CG7FM3BLY

Original ticket: https://2u-internal.atlassian.net/browse/ARCHBOM-2103

**Comment by robrap** [comment]
Jawad has not been responding, and is likely OOO for some reason. Marking as blocked until I hear back.

**Comment by jawad-khan** [comment]
We are moving ahead with JWT, ADRs hae been created and merged, grant _type added in jwt payload. We are working on asymmetric JWT right now.

**Comment by robrap** [comment]
@jawad-khan: I updated the task list above with the plan we outlined. Let me know if it makes sense. Also, now that the plan is clear, would you be able to get internal reviews and sign-offs before bringing me in, and just bringing me in for blocking questions before that?

**Comment by jawad-khan** [comment]
@robrap The task list is clear. We can discuss about toggle later but currently its good. I'll try to get internal review before bringing you in. Thanks.

**Comment by robrap** [comment]
@jawad-khan: I'm curious about progress and deadlines for your team. No urgency from my end, just checking. Good luck.

**Comment by robrap** [comment]
@jawad-khan: Looks like you are real close. Let me know if you want to discuss (sync or async) the rollout plans (toggle, dashboard, etc.) mentioned in the top of this ticket.

**Comment by robrap** [comment]
@jawad-khan: I am closing this ticket. I also sent the unchecked items from above in Slack for your team to consider picking up. Good luck.
