### ISSUE TITLE
[Abstraction] Add how-to for how to add a new concrete implementation of the event bus

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#172]
# Acceptance Criteria

- [x] A wiki or other document with information about what will be required for any event bus abstraction, shareable with the community. Minimally document db re-connect, and see notes for more details.
- [x] Wiki is shared with the people who are working on this at tCRIL. Include TODO for tCRIL to link to their abstraction/Redis work.
- [x] Wiki has link to all existing abstraction tickets (use https://github.com/orgs/edx/projects/11/views/4?filterQuery=label%3Aevent-bus+-status%3ADone+abstraction)

# Notes
* We will want to emphasize that new implementations will need to copy the consume_indefinitely pattern (including database reconnections) unless/until we break out more reusable code from the consumer loop.
* This is meant to be a start for this doc capturing things that the tCRIL team wouldn't know on their own, like the db re-connect issue, and maybe the link to the tickets. The tCRIL team can flesh out this doc as they actually do a second implementation.

**Comment by robrap** [comment]
Thoughts: maybe this is a "How-to add a new technology implementation of the event bus (api? abstraction layer?)." The how-to could live in openedx-events or in the wiki (to start).
