### ISSUE TITLE
Ensure Arbisoft contractors can access OpsGenie

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#175]

**Comment by rgraber** [comment]
This is now https://jira.2u.com/servicedesk/customer/portal/9/PSO-12192

**Comment by rgraber** [comment]
After some back and forth, this is back with SaaS Ops. They have met with the folks from Arbisoft and seen the issue firsthand so hopefully have a better idea of what's going on.

**Comment by rgraber** [comment]
Everyone has confirmed access
