### ISSUE TITLE
Finish ownership transfer of CENG repos

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#18]
- [x] Update ownership spreadsheet with new owners of CE repos/services/etc.
- [x] #132
- [ ] #133
- [x] #135
- [x] #136
- [x] #137

Moved from private Jira ticket: https://2u-internal.atlassian.net/browse/ARCHBOM-1974

**Comment by robrap** [comment]
Comment originally from @jmbowman: [CE Squad Ownership Transition](https://docs.google.com/spreadsheets/d/151a6LSZbVlsnK6HMQfS4sJSIuYDTjM1mFB9aTj1sepc/edit#gid=662356550) - this is the penciled in ownership changes that Sarina and I came up with, may need some adjustment if intended owners don’t think they should inherit these.

**Comment by robrap** [comment]
Transferring and/or cleaning up on-call should be a part of this ticket or a new ticket:
* Review/transfer/remove New Relic alert policies and notification channels.
* Review old OpsGenie alerts and integrations, before removal.

**Comment by jmbowman** [comment]
Try not to spend too much time on the remaining cleanup; urgency is low, we just don't want to have to come back to it.

**Comment by timmc-edx** [comment]
The involved CODEOWNERS files are all identical:

```
$ sha256sum `ack community-engineering ~/mirrored-orgs/{edx,openedx}/*/.github/CODEOWNERS -l` | cut -d ' ' -f1 | uniq -c
     44 b49129dd0e32a677549adfae1c5d19c2cc8dbe9b865f91f23bba2208d1b54f50
```

I'll see if I can get that one Jenkins job to do this.

**Comment by timmc-edx** [comment]
All items have been turned into separate tickets.

**Comment by robrap** [comment]
The remaining work is tasked separately (and blocked), so closing this ticket. See https://github.com/edx/edx-arch-experiments/issues/133.
