### ISSUE TITLE
[Observability] Remove unused and confusing expected error functionality

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#182]
Consider removing expected errors functionality. It was meant to allow for greater flexibility and was written before New Relic enabled their own. Now the New Relic and our own custom attribute have different names, and different values, based on where the expected errors are configured. Additionally, the setting is named after EXPECTED_ERRORS, even though the default for all the settings if ignored errors. Renaming this to IGNORED_ERRORS (or allowing for either name for backward compatibility) would be another nice enhancement.

Separate, but related, the ignored error custom attributes (New Relic and our own) use a "." before the class name and a ":" before the class (I forget which is which). If these looked the same once they got to New Relic (even if defined differently), we could simplify the query in https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16386732/Expected+and+Ignored+Error+Runbook#2.-Determine-likely-cause and in the alert, by not having to do a capture, but simply by doing a direct compare. This could be its own ticket, but might be nice to fix this if and when we ever fix the above.

Note: For all of the above, runbooks and docs should be fixed up.

**Comment by jristau1984** [comment]
I believe this can now be closed.
