### ISSUE TITLE
Determine process for approving API access requests

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#185]
Recently, someone in Data Analysis requested client credentials for a service user, following the process laid out here: https://course-catalog-api-guide.readthedocs.io/en/latest/intro_edx_apis.html. It is unclear how Helpdesk (or anyone) are supposed to determine whether or not to approve.

## Acceptance Criteria

- [ ] The correct people are notified when someone submits a credentials request via https://courses.edx.org/api-admin/
- [ ] The approvers have a process to determine if a request should be approved 

## Notes
It was found that the request could be approved by someone with access to https://internal.courses.edx.org/admin/api_admin/apiaccessrequest/ , but there did not seem to be much of a pattern in who had that access. Helpdesk did but they weren't sure if they were really supposed to be approving requests. 

Part of this ticket is determining if Helpdesk should be the ones approving these requests, or if it should be someone else, hence "the correct people" in the first A/C.

It's possible the process will be just asking the manager of the person who made the request, similar to how it works with app-permissions.

**Comment by jristau1984** [comment]
https://2u-internal.atlassian.net/wiki/spaces/~60ba5f9548549e0069510f53/pages/773947498/Learning+Platform+API+Access+Request+Review+Process
