### ISSUE TITLE
Archive edx/django-require

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#187]
https://github.com/edx/django-require was recently forked to https://github.com/openedx/django-require , but we haven't yet archived the former and moved it to edx-unsupported.  We should do so to avoid any future confusion around which repo to make changes in.

This topic was first raised in https://openedx.slack.com/archives/C0497NQCLBT/p1676038450857889 .

**Comment by dianakhuang** [comment]
We should check to see how we're installing it and make sure no one is using the edx version vs. the openedx one.

**Comment by dianakhuang** [comment]
We have confirmed that only older releases of Open edX would be affected, so we will continue with this archival.
