### ISSUE TITLE
Investigate corrupt cookie header hypothesis

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#19]
We have two ways that we detect what we are considering to be corrupt cookie headers:

1. We find “Cookie:” in the header. See https://2u-internal.atlassian.net/browse/CR-4614 for more details.
2. The raw cookie header size is much larger than the calculated cookie size.

The second case, based on cookie header size differences is more of a mystery, and this ticket is for making this less of a mystery.

See https://github.com/openedx/edx-django-utils/blob/master/edx_django_utils/monitoring/internal/middleware.py#L322-L381  for details on how these two sizes are calculated.

The proposal would be for large cookie headers (> 10k ?), to also do **encrypted** logging of the original header. **Note:** this threshold should be its own setting so that we can disable or minimize this logging as needed. This data could be added to the cookie size logging so it is simple to match these up.

Comparing the actual header to the reported cookie sizes will help us understand where some of the header is getting lost when being converted to the cookies dict.

Also see https://openedx.atlassian.net/wiki/spaces/AT/pages/3192225888/Runbook+for+Very+large+cookie+headers+in+xyz for additional information.

**Comment by robrap** [comment]
See original ticket https://2u-internal.atlassian.net/browse/ARCHBOM-2082 for more comments that have not moved, and related PRs and branches, etc.

**Comment by jmbowman** [comment]
We have collected more data, but not yet made time to analyze it.

**Comment by jristau1984** [comment]
Cookies have been moved out of Arch-BOM team ownership.
