### ISSUE TITLE
Update or remove v2 Transifex config in various remaining repos

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#190]
We have a number of repos that seem to have a v2 Transifex configuration. These might not actually be translated repos, so for most of these we probably just want to remove the translations/Transifex references.

Repos with explicit `/api/2` references in their Makefiles:

```
$ ack -Q 'transifex.com/api/2/' ~/mirrored-orgs/{edx,openedx}/*/Makefile -l | sed -e 's|/Makefile.*||' -e 's|.*-orgs/||' | sort

edx/frontend-component-footer-edx
edx/frontend-component-header-edx
openedx/frontend-app-account
openedx/frontend-app-communications
openedx/frontend-app-course-authoring
openedx/frontend-app-discussions
openedx/frontend-app-enterprise-public-catalog
openedx/frontend-app-gradebook
openedx/frontend-app-learner-dashboard
openedx/frontend-app-learner-record
openedx/frontend-app-library-authoring
openedx/frontend-app-ora-grading
openedx/frontend-app-profile
openedx/frontend-app-support-tools
openedx/frontend-component-footer
openedx/frontend-component-header
openedx/frontend-lib-content-components
openedx/frontend-lib-special-exams
openedx/frontend-template-application
openedx/studio-frontend
```

Additional repos with `.tx/config` that use v2-style project headers:

```
edx/commerce-coordinator
edx/demographics
edx/platform-plugin-coaching
edx/portal-designer
edx/program-intent-engagement
edx/video-encode-manager
openedx/edx-app-android
openedx/edx-app-ios
openedx/edx-celeryutils
openedx/enterprise-subsidy
openedx/xblock-google-drive
openedx/xblock-image-modal
openedx/xblock-qualtrics-survey
openedx/xblock-submit-and-compare
```

And some repos that use `-af` (rather than `-a -f`) in the Transifex call, since I'm not sure if that's compatible with the v3 client:

```
edx/edx-arch-experiments
edx/edx-exams
edx/edx-name-affirmation
edx/financial-assistance
edx/learner-pathway-progress
edx/outcome-surveys
edx/platform-plugin-notices
edx/subscriptions
edx/token-utils
openedx/edx-rbac
openedx/enterprise-access
openedx/enterprise-catalog
openedx/event-bus-kafka
openedx/event-routing-backends
openedx/openedx-learning
openedx/openedx-ledger
openedx/registrar
openedx/taxonomy-connector
```

**Comment by timmc-edx** [comment]
I'm not totally confident that the strings I searched for are fully indicative of v2 configs, so take these lists with a grain of salt.

**Comment by UsamaSadiq** [comment]
Hi @timmc-edx , 
After going through the attached repos list and issues mentioned separately, I've prepared following plan of action to address these three issues separately which will be implemented gradually by arbi-bom to complete this issue as soon as possible: 

## 1. Updating `/api/v2` endpoints
At the time of migrating transifex client from `v2` to `v3`, `arbi-bom` only followed the steps mentioned in the migration docs for the `transifex/cli` i.e. ran `tx migrate` to update the config file and updated the `pull/push translations` targets to follow new syntax changes but seems like we missed these api endpoints as these were not present in any backend repos. 
- These mentioned endpoints will need to be updated according to the new api syntax and the endpoint will need to be updated from `www.transifex.com` to `rest.api.transifex.com` instead. 
- Further investigation will be needed to ensure if only updating the endpoint base url will work or additional flags will need to be provided according to the transifex [api-docs](https://transifex.github.io/openapi/index.html#section/Asynchronous-Processing). 
- Existing [answers](https://community.transifex.com/t/confused-about-how-to-put-together-a-request-for-api-v3/2469) on the transifex developer forum could also be useful in the discovery.

## 2. Updating old `.tx/config`
- `arbi-bom` will update all these repos by running `tx migrate` with new `transifex client` and follow the `transifex docs` to update the config.
- If a repo only has `.tx/config` file present but hasn't had any translations merged, the owning team will be consulted to completely remove the config file & the `pull/push translations` make targets from the repo.

## 3. Use of `-af` and `-a -f`
The initial versions of transifex cli v3 `transifex<1.1.0` had the issue where the combined flags didn't work and it was [raised](https://github.com/transifex/cli/issues/27) by arbi-bom to the transifex maintainers at the time of migrating `transifex` client and config in all repos. This issue got [resolved](https://github.com/transifex/cli/pull/37) in the version 1.1.0 and now both methods work in the same way. 
- To make the format consistent across the repos, arbi-bom will update all the mentioned repos to use same flags notation (`-a -f`)as the other repos. 

CC: @jmbowman @iamsobanjaved

**Comment by UsamaSadiq** [comment]
After discussing with `bom-fe` team, the 1st task was assigned to their team since the changes were mostly in the front end repos.

**Comment by timmc-edx** [comment]
Fantastic, thank you! Love seeing all that green in Jenkins. :-)
