### ISSUE TITLE
Please create stage and prod consumer groups for Subscriptions service

### ISSUE THREAD

**Issue by christopappas** [edx/edx-arch-experiments#195]
Hi there,

I'm setting up Kafka/event-bus infra for my new django app called Subscriptions, and need a consumer group created for the stage and prod environments.

Can you please create `subscriptions_stage` and `subscriptions_prod` consumer groups for me? Putting this request here for now per @rgraber 's recommendation!

Please let me know if I can provide any additional information.

Thanks,
Chris

**Comment by rgraber** [comment]
This has been set up, with the topics subscription-created, subscription-updated, subscription-deleted on both stage and prod. Credentials have been shared with @christopappas .
