### ISSUE TITLE
Tune event bus alerting for Stage

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#200]
**AC:**
- [ ] Review the 2 event bus alerts happening in Stage.
- [ ] Tune alerts and/or fix issues.
- [ ] Update Runbook as appropriate.

**Notes:**

The following 2 self-closing alerts went off over the weekend of Feb 25, 2023:
* stage-edx-discovery query result is > 2.0 for 30 minutes on 'Consumer latency above 2s [P3]'
  * [OpsGenie alert](https://2u-internal.app.opsgenie.com/alert/detail/45616db1-fa31-407e-8c4e-b6283dbe2d61-1677501263607/details)
* Signal lost for 1440 minutes on 'No event produced in past day on any topic [P3]'
  * Target: [MessageBroker/Kafka/Topic/Produce/Named/stage-course-catalog-info-changed](https://insights.newrelic.com/accounts/88178/query?query=select+count%28newrelic.timeslice.value%29+from+Metric+facet+metricTimesliceName+where+appName+like+%27%25%27+and+metricTimesliceName+like+%27MessageBroker%2FKafka%2FTopic%2FProduce%2FNamed%2F%25%27+TIMESERIES+5+MINUTES+SINCE+%272023-02-24+11%3A18%3A50%27+UNTIL+%272023-02-25+17%3A13%3A50%27)
  * [Opsgenie Alert](https://2u-internal.app.opsgenie.com/alert/detail/af926e5a-27ae-4c6b-9d19-a6146836d577-1677345233995/details)

Both are related to Stage. It is not clear why Consumer latency gets kicked off in Stage from time to time, and that should probably be investigated rather than tuned out. However, the no event produced alert may be a really useless alert for certain stage topics.

Ideally, alerts should indicate when there is an issue that should be investigated.

**Comment by robrap** [comment]
There was another Latency alert in Stage. See [Opsgenie alert](https://2u-internal.app.opsgenie.com/alert/detail/cdd7e0a9-046d-45a1-a725-9317524afd27-1677510883328/details). We should probably take care of this sooner rather than later, so it doesn't keep annoying us.

**Comment by robrap** [comment]
Adjusted gap filling to 0 for Consumer Latency alert, and maybe that will take care of the false positives in Stage.

**Comment by dianakhuang** [comment]
For documentation purposes:
- Robert tuned the consumer latency alert, and we are planning on monitoring this to see if it fixes the spurious issues.
- We are considering that the 'No event produced' alert is not actually useful for monitoring stage as nearly all activity on there only happens during working hours. We will probably disable those alerts on stage.

**Comment by dianakhuang** [comment]
I made changes to the 'No event produced' alert to disable it from alerting on stage environments (hopefully).

**Comment by dianakhuang** [comment]
We also removed the latency alert after we realized that most of the latency was in the business logic of the event processing. This decision was recorded on the [runbook](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/234258433/Event+Bus+alert+runbook).

**Comment by robrap** [comment]
> We also removed the latency alert after we realized that most of the latency was in the business logic of the event processing. This decision was recorded on the [runbook](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/234258433/Event+Bus+alert+runbook).

FYI: @rgraber: I know this was your plan from the start. Sometimes it takes a while for me to catch up to you. :)

**Comment by rgraber** [comment]
> > We also removed the latency alert after we realized that most of the latency was in the business logic of the event processing. This decision was recorded on the [runbook](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/234258433/Event+Bus+alert+runbook).
> 
> FYI: @rgraber: I know this was your plan from the start. Sometimes it takes a while for me to catch up to you. :)

I'm glad to hear past me had plans. Present me has very little recollection of them.
