### ISSUE TITLE
Adopt ownership of user_api app

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#214]
Phoenix currently owns this Django app in edx-platform, but Arch-BOM may be a more appropriate home.  Earlier discussion in https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16385873/BOM+Standup+Parking+Lot#2023-03-06 .

A/C:

* Confirm with Phoenix that they're open to handing it over
* Update ownership spreadsheet and CODEOWNERS file appropriately
* Document how we plan to approach maintaining it

**Comment by jristau1984** [comment]
This is now owned by Aperture.
