### ISSUE TITLE
Handle dependencies for removing old account settings pages

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#218]
We had to revert a PR removing the old account settings pages (https://github.com/openedx/edx-platform/pull/30336) because the header used the old pages to redirect to the MFE.

Here's the things that are going to need to be fixed before we can merge again:
- Have the dropdown bar in the header point to the account MFE instead of the old account settings page.
    - This has partially been handled by the PRs: https://github.com/edx/edx-internal/pull/7937, https://github.com/edx/frontend-component-header-edx/pull/351, https://github.com/edx/edx-internal/pull/7939 (still needs to be merged)
 - Have the account settings MFE setup on the edge environment.
    - We will also need to make sure to update edge-internal to have the correct URL.

We may also want to look to see if there's other places that need to have the URL updated.

**Comment by abdullahwaheed** [comment]
we have updated account URL in MFEs using header-edx.
Account and profile MFEs are deployed on edge.
