### ISSUE TITLE
Remove `CONFLUENCE_PASSWORD` secret from GoCD

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#219]
After the PRs listed in https://github.com/edx/edx-arch-experiments/issues/215 were merged, this secret is no longer referenced in any GoCD pipelines and can be removed from GoCD.

I'll separately ensure that the corresponding user (release-pipeline-bot) is removed from the openedx Confluence.

**Comment by rgraber** [comment]
Escalating since I don't think I have permissions to do this.

**Comment by rgraber** [comment]
This is now https://2u-internal.atlassian.net/browse/PSRE-2285
