### ISSUE TITLE
Enumerate communication channels Arch-BOM needs to follow

### ISSUE THREAD

**Issue by nedbat** [edx/edx-arch-experiments#22]
- What channels should Arch-BOM people be listening to?
  - Slack channels in two Slacks
  - Discourse
  - Working groups
  - Pull requests
  - OEP reviews
  - etc
- Can we delegate some to specific people to avoid everyone listening to everything?
- Can we avoid hearing duplicate announcements with a per-channel strategy?

**Comment by jristau1984** [comment]
Closing due to age and inactivity.
