### ISSUE TITLE
Docs: Find/improve documentation for deploying new plugins

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#227]
We have documentation for how to create a new plugin but not much around how to deploy the new plugin. This ticket should have information about how to use `EDXAPP_EXTRA_REQUIREMENTS` (see https://github.com/edx/edx-internal/blob/9c3910fe96d346d8f40a1150ff02af74ddcebb27/ansible/vars/prod-edx.yml#L150) and note that versioning will need to be done there.
We should include a warning to always quote version strings, because ">" is a special character in yaml

Make sure the docs are easily discoverable

AC:
- [ ] Add information on how to use EDXAPP_EXTRA_REQUIREMENTS and versioning.
    - [ ] Updates to requirements need to happen in both the configuration repo and in remote config. https://github.com/openedx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L535
- [ ] Make sure this is discoverable.
- [ ] Write up a ticket for investigating the difference between EDXAPP_EXTRA_REQUIREMENTS and EDXAPP_PRIVATE_REQUIREMENTS.
- [ ] Write up new tickets if there's docs issues that need to be addressed.

Note: We know that this is confusing between EDXAPP_EXTRA_REQUIREMENTS and EDXAPP_PRIVATE_REQUIREMENTS. Recommend putting things in EDXAPP_EXTRA_REQUIREMENTS and the if you don't know which one otherwise.

**Comment by rgraber** [comment]
Note: this is meant to be quick. Tickets to refine and/or move whatever documentation comes out of this can be created as a part of the process.

**Comment by dianakhuang** [comment]
Looking at the explanation here, I believe the difference between `EXTRA_REQUIREMENTS` and `PRIVATE_REQUIREMENTS` is that `PRIVATE_REQUIREMENTS` can install plugins from private repositories and `EXTRA_REQUIREMENTS` cannot. I'll add the distinction in the document.
