### ISSUE TITLE
Oauth token deletion jobs not keeping up with table growth

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#236]
## A/C

- [x] Any existing open OpsGenie alerts for this job are routed to Arch BOM (there were none)
- [x] Arch BOM is notified when prod-edx-delete_expired_dot_tokens (and presumably stage_, if necessary) fail
- [x] The prod-edx-delete_expired_dot_tokens runs in a reasonable amount of time
  - [x] If the initial pass doesn't resolve the problem, make new tickets for more discovery work around the actual problem  - thus is now https://github.com/edx/edx-arch-experiments/issues/240

I noticed a while back that [runs of this job](https://tools-edx-jenkins.edx.org/job/oauth/job/prod-edx-delete_expired_dot_tokens/) were running for really long spans of time, and in some spare cycles investigated why. (Quite dramatically and probably due to a bug on the jenkins side, one of them had hung for 20 days at the time this piqued my interest.) I had initially investigated this thinking it was SRE's to own based on the fact that we were getting failure notifications via email for it. Team members impressed on me though that I should look into it and it does look like [y'all perhaps should've owned it all along](https://github.com/edx/edx-internal/pull/7993).

[The management command run by this job](https://github.com/openedx/edx-platform/blob/33de5aad1a814dbbf3a9d45b4ea1a96091e45155/openedx/core/djangoapps/oauth_dispatch/management/commands/edx_clear_expired_tokens.py) attempts to delete a bunch of rows in three tables, deleting first from [`RefreshToken`](https://github.com/openedx/edx-platform/blob/33de5aad1a814dbbf3a9d45b4ea1a96091e45155/openedx/core/djangoapps/oauth_dispatch/management/commands/edx_clear_expired_tokens.py#L84) based on the expiry of the corresponding access token (read: across a join), then deleting any access tokens which newly have no refresh tokens, and then deleting any of a third thing I haven't thought about because since 2020 nothing but the first thing has even attempted to happen.

I have some PRs which I think might help improve the situation:
- https://github.com/openedx/edx-platform/pull/31921 (adds flags so we can skip steps)
- https://github.com/edx/edx-internal/pull/7986 (adds a job which skips step 1, because maybe we can improve the performance of deleting refresh tokens that way 🤞 )
- https://github.com/edx/edx-internal/pull/7993 (alerts y'all instead of SRE as this job continues to fail)

How would y'all feel taking back over more active ownership of this job? I don't think it's particularly urgent to get it back to green, i.e. I don't know of any end-user impact to these expired tokens persisting in our database. Still, it seems like hundreds of millions of database rows may be a nice cost-saving opportunity to remove.

**Comment by matthugs** [comment]
Other fun little details for me to pass off: I've been estimating the effective rate of deletion/accretion with queries like this:

```
mysql> select min(rt.access_token_id) from oauth2_provider_refreshtoken rt;
+-------------------------+
| min(rt.access_token_id) |
+-------------------------+
|               338616106 |
+-------------------------+
1 row in set (0.00 sec)
```

best I can tell that moved by about half a million in the last day, while a job was running for around 20 hours straight. (The jobs get interrupted whenever an edxapp deploy happens so this is unusual.) We're more than 300 million rows behind right now.

count(1) queries against this table take several minutes, by comparison.

**Comment by rgraber** [comment]
closing in favor of https://github.com/edx/edx-arch-experiments/issues/240, the new discovery ticket
