### ISSUE TITLE
[Discovery] Oauth token deletion jobs failing

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#240]
https://github.com/edx/edx-arch-experiments/issues/236 brought to our attention that the prod-edx-delete_expired_dot_tokens job has been failing for a while, after taking a prohibitively long amount of time to run. The initial attempts to fix it by running a separate job (prod-edx-delete_expired_dot_tokens_monthly_refreshtokens) that skipped the first step failed.
This ticket is for discovery around how we can get the job running again and hopefully avoid this problem in the future.

**Comment by matthugs** [comment]
> The initial attempts to fix it by running a separate job (prod-edx-delete_expired_dot_tokens_monthly_refreshtokens) that skipped the first step failed.

"failed" is a strong word; I do think the job is performing ever-so-slightly better due to the deletion of long-dead `AccessToken`s. I investigated this a little more and I think the best forward-fix is going to be adding a database index.

An EXPLAIN I ran from read-replica on one of the queries pulling deletable `RefreshToken`s: 

```
mysql> explain SELECT `oauth2_provider_refreshtoken`.`id` FROM `oauth2_provider_refreshtoken` INNER JOIN `oauth2_provider_accesstoken` ON (`oauth2_provider_refreshtoken`.`access_token_id` = `oauth2_provider_accesstoken`.`id`) WHERE `oauth2_provider_accesstoken`.`expires` < '2022-12-18 20:18:17.437901' LIMIT 1000
    -> ;
+----+-------------+------------------------------+------------+------+-----------------+-----------------+---------+------------------------------------+-----------+----------+-------------+
| id | select_type | table                        | partitions | type | possible_keys   | key             | key_len | ref                                | rows      | filtered | Extra       |
+----+-------------+------------------------------+------------+------+-----------------+-----------------+---------+------------------------------------+-----------+----------+-------------+
|  1 | SIMPLE      | oauth2_provider_accesstoken  | NULL       | ALL  | PRIMARY         | NULL            | NULL    | NULL                               | 329752627 |    33.33 | Using where |
|  1 | SIMPLE      | oauth2_provider_refreshtoken | NULL       | ref  | access_token_id | access_token_id | 9       | wwc.oauth2_provider_accesstoken.id |         1 |   100.00 | Using index |
+----+-------------+------------------------------+------------+------+-----------------+-----------------+---------+------------------------------------+-----------+----------+-------------+
2 rows in set, 1 warning (0.00 sec)
```

The `type` of `ALL` in the `oauth2_provider_accesstoken` row is the kiss of death: it's doing a full table scan just to find 1000 rows satisfying the WHERE clause for expired tokens (and I suppose implicitly also ones for which the RefreshToken isn't null? idk). Generally you prevent a table scan like that by throwing an index on whichever field your WHERE clause applies to. I think we can do that but it requires customizing the AccessToken table being used to be a custom-rolled extension of the library-provided one, replacing the `expires` field with a copy thereof but with `index=True` set.

I did look to see whether a more recent version of the oauth library adds such an index on the expires column and it looks like they do not.

I also looked into a bunch of stuff related to creating the index without causing table locking, and it does seem possible (since MySQL 5.6, which our DBs are): https://realpython.com/create-django-index-without-downtime/ & https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html#online-ddl-index-operations

**Comment by rgraber** [comment]
Two questions that I'm currently unable to answer to my satisfaction:
What happens if we add a raw SQL migration and then, in the future, the library updates the models to have the same index? I'm assuming we'll have to fake apply the new migration the library gives us. It is possible there will be no conflict since it seems like Django will usually put a hash at the end of the index name when it creates one automatically, but I'm not positive.

Is it ok to add the index in SQL without adding it on the model? It didn't make a difference when running locally but that's not a guarantee.

**Comment by rgraber** [comment]
Also the last time the job failed, it deleted a couple hundred thousands of rows in RefreshTokens first, which worries me since it means that even if we can speed up the joins we'll fail due to the sheer number of deletions we have to perform. I'm going to look at how many new rows are added daily to see if there's any chance of us catching up or if the additions will always outweigh the deletions.

**Comment by rgraber** [comment]
The good news is we're only adding ~20K rows per day to each table, so if we can delete in the millions, we're at least not falling more behind.

**Comment by rgraber** [comment]
Proposal as crafted by @timmc-edx and myself:

* Run two different versions of edx_clear_expired_tokens, one of which deals just with the RefreshTokens (revoked and expired), one of which deals with AccessTokens and Grants 
  * Remove expired tokens before revoked ones. Even though finding expired tokens requires a join, there are probably many more expired tokens than revoked ones
* Reduce the delay on both jobs to 2 seconds
* Run each of these every hour
  * If necessary, can we configure this to say "Run every hour unless it's already running"
  * The job is usually long running and gets interrupted by a deploy. If we run it once every hour we can effectively run it continuously without relying on a long period with no deploys.

At this rate, if Tim's calculations are correct, we should be caught up in a month or two. 
We could conceivably still add the index to the AccessToken table but first we would need to figure out if we could safely reverse the migration. This is currently causing concern as running the reverse migration takes 2 minutes on a 7 row table in local devstack.

It would be very helpful if someone who knows more about these tables could review this plan. @robrap @dianakhuang

**Comment by robrap** [comment]
1. I know a little, but not much. I feel like once upon a time there was info about the refresh token that wasn't redundant, and you needed to look at the access token to learn the state. None of this may be true now, but if it is, make sure that we aren't losing info by not cascading the clean-up.
2. Is it possible to have SRE set up a server on the side that is outside of the pool and doesn't get interrupted with each deploy?

**Comment by timmc-edx** [comment]
I think that's true but that it's already handled by the script. (Note that the script itself does not enforce an ordering, as you can use the CLI options to run any selection of steps individually.) Expired refresh tokens can only be properly discovered by joining to access tokens, but access tokens only get deleted by this script if the refresh token is already missing. So there shouldn't be any orphaned refresh tokens. I suspect it would also be acceptable to delete any refresh token that didn't _have_ an access token, although I bet that doesn't occur, and maybe _can't_ occur (depending on what the DB enforces).

The only problem I've noticed with this script is that in one place we delete things where `expires` is in the past, and in another place we delete where `expires` is at least `REFRESH_TOKEN_EXPIRE_SECONDS` seconds in the past. Something to clean up, but I don't think that's going to interfere with any application invariants.

**Comment by robrap** [comment]
Great. Thanks @timmc-edx.
