### ISSUE TITLE
Don't have moderated announcement emails re-moderated

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#241]
When we send emails to the edX tech announcements list, the messages are held for moderation. However, once they are released, they then arrive at the subgroups... many of which _also_ hold the messages for moderation. This can cause significant delays in reaching engineers, as the owners of those lists are usually managers who don't necessarily get to their emails very quickly.

Some approaches to explore:

- Is there a way we can support those list moderators in acting faster?
- Can we get those lists to be unmoderated?
- Can we get certain senders approved for _all_ of the lists?

**Comment by robrap** [comment]
We're going to try sending this from the email list so that it can go through unmoderated.
