### ISSUE TITLE
Add a standard footer about the purpose of the announcement list

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#242]
The edX tech announce list should include a footer that explains the purpose of the list.

**Comment by robrap** [comment]
How do people feel about the following?:

> This group email is used for announcement related to 2U's uses or extensions of the Open edX platform. If these announcements don't feel relevant to you, please ignore or use email filtering as appropriate. Thank you.

I think this needs to be set by an owner: Ned, Robert, or Jeremy (at this point).

**Comment by rgraber** [comment]
Typo: announcementS should be plural

**Comment by nedbat** [comment]
Mention edx.org, and I'm good:
> This group email is used for announcements related to 2U's uses or extensions of the Open edX platform, including edx.org. If these announcements don't feel relevant to you, please ignore or use email filtering as appropriate. Thank you.

**Comment by robrap** [comment]
I updated this.
