### ISSUE TITLE
Move all pipelines to autodeploy to production.

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#243]
Currently, the edxapp pipeline auto-deploys to production after e2e tests have run, which is different from all our other pipelines, which require a manual intervention to trigger a deploy to production. We would like to move all the other pipelines to be more consistent with edxapp, especially since there are new versions of smaller deploys like MFEs that sit without being released to production for months.

Acceptance Criteria
- [x] Start a conversation with owning teams about changing the default behavior of deploys.
- [ ] Make a plan for what steps we would need to take in order to start deploying more things to production directly.
- [ ] Create a ticket once next steps are understood.

Note:
- We can also do a smaller amount of work to improve education around the deployment of edxapp and how it differs from other deployments.

**Comment by jristau1984** [comment]
Discussions and observations with teams have led me to decide this is not a desired course of action.
