### ISSUE TITLE
[Discovery] Determine if memcached issues are self-healing

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#244]
This ticket is just for determining whether memcached is self-healing after issues inside the consumer infinite loop, unlike the database.

**AC:**
- [x] Perform test in devstack to ensure that memcached is self-healing in infinite loop.
- [x] Based on findings, create follow-up ticket or document non-issue in this ticket.
- [x] Let Robert know the findings.

**Notes:**
- Should be able to take down Memcached container in devstack, and then bring back up, and check to see whether it is working.
- Note that Memcached doesn't provide good errors, so we will need to write a value and read it and ensure it actually is working.
- We don't have a good reproduction case, but we can create a consumer that just checks memcached and outputs status.

**Comment by dianakhuang** [comment]
If this is not completed before the event bus presentation at the Open edX 2023 conference, we can move this down in priority.
