### ISSUE TITLE
[Discovery] When to use Dedicated Kafka cluster?

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#247]
We chose to start with a Standard Kafka cluster at Confluent, rather than a Dedicated cluster. This saves us on monthly cost, but will increase the cost/impact of migration when and if we switch to a Dedicated cluster. Now that more events will soon be onboarded, we may want to double-check the decision, and/or determine if we wish to defer again and stick with the Standard cluster. Note that we don't need to actually answer the question, as long as the answer continues to be "not now".

More information:
* See https://2u-internal.atlassian.net/wiki/spaces/AT/pages/2626417/Confluent.io+Kafka+Hosting+Notes#Decision
* VPC Peering probably has additional expense, and additional issues with Schema Registry, so we'll probably continue to avoid this.

Acceptance Criteria:
- [x] Document answers to open questions (and any other relevant questions that come up during discovery that would influence the decision in the next AC).
- [x] Document recommended decision for whether we should switch now (in a newly created ticket), or punt into the future (and how far it should be punted).
- [ ] Get approval on recommendation from @robrap.

Questions:
- [ ] What is the cost difference of switching?
- [ ] What is the impact of migration per topic and overall? Can this be done without downtime? Does it depend on the event on whether we can get away with losing some events?
- [ ] Are there differences in performance guarantees around the different clusters? Is this just in terms of uptime guarantees? Do they have any SLAs on a per event basis? How does Confluent assess what it too noisy, regarding noisy-neighbors, and what acceptable impact may be?
- [ ] What are our options in related to those who are managing the contract (formerly Degrees)? Possible discuss with Oleg or determine with whom we should discuss.
- [ ] Would we leave Stage as-is for cost savings purposes? Is there any possible impact to having Stage and Prod not match?
- [ ] How many new topics do we expect in the short-term? Can we even know? If we punt on this, how far out should we reminder ourselves to re-assess?

**Comment by dianakhuang** [comment]
This ticket is about determining criteria for dedicated vs. standard cluster in Confluent in the short term vs. the long term, not doing the work to actually move anything.

**Comment by rgraber** [comment]
Going to document answers as comments as I find them. Will consider better places for docs later.
1. "Standard has an approximate fixed cost of ~$13k for multi-AZ per year, where Dedicated is ~$66k for multi-AZ (minimum 2 CKU) per year." 
2. There's a talk [here](https://www.confluent.io/events/current-2022/zero-down-time-move-from-apache-kafka-to-confluent/) about a company that migrated using cluster links, but I don't understand all of it. Cluster links auto sync data from one cluster to another, including things like consumer offsets. 
     a. The main thing I don't understand is how they moved the producers over without missing events
     b. We can send to as many topics as we want just by calling send() multiple times, but I'm not sure if we can do this across clusters

**Comment by robrap** [comment]
@rgraber: Thanks. I added us as assignees (I guess issues can't have a reviewer) and moved this to In Code Review.
