### ISSUE TITLE
Discovery for Studio event bus use case

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#25]
This discovery is to both confirm that the Studio course publish event to Discovery use case, as a replacement for a part of Refresh Course Metadata, is the right move. It is also to help create follow-up tasks.

- [x] Document findings.
- [x] Confirm difficulty of publishing the course publish event in Studio. This would entail appropriate event design.
- [x] Confirm difficulty of consuming the event in Discovery and logging.
- [x] Confirm difficulty of consuming the event in Discovery and running appropriate idempotent code to update the course. (Determine if this should be left to another Epic?)
- [x] Who owns the Studio event publish side? TNL? We should discuss long-term ownership with them. 
- [x] Does Pheonix own the Discovery consuming side? We should discuss long-term ownership with them.
- [x] Support creation of follow-up tickets (with discussion first), including moving boiler-plate code to proper libraries.

**Comment by robrap** [comment]
@rgraber: Can you also document any findings so far from any discovery you've done?

**Comment by rgraber** [comment]
The documentation for this ended up in https://2u-internal.atlassian.net/wiki/spaces/AT/pages/63373336/Discovery+-+discovery

**Comment by robrap** [comment]
@rgraber: I think we discussed long-term ownership with Phoenix. I'm not sure what we did for TNL. They should be involved with sad-path of the event publishing, and what they think they'd do regarding sad-path, etc. Should we create a separate ticket, or just move this unchecked task to the sad-path task so we can close this out?

**Comment by rgraber** [comment]
I think either way "Who owns the Studio event publish side? TNL? We should discuss long-term ownership with them" does not work as an acceptance criteria. I'm not even sure it belongs in a ticket.

**Comment by rgraber** [comment]
I think we should close this. We can put a note in the sad path task to make sure to run it by TNL.

**Comment by robrap** [comment]
Thanks. I added a note about TNL to https://github.com/edx/edx-arch-experiments/issues/54 (sad path). I want this represented in a ticket because I think we'll get into trouble if we don't address it, and it would be easy to forget about.
