### ISSUE TITLE
Create diff-cover based alternative to codecov

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#255]
The subscriptions repo is private and it wants to monitor changes in coverage, despite the fact that we aren't paying for codecov. We would like to help the owning team find a reasonable alternative.

We have an alternative we like: https://github.com/py-cov-action/python-coverage-comment-action

Acceptance Criteria
- [ ] Have a coverage check on the subscriptions repo.
- [x] Add documentation to https://docs.openedx.org/en/latest/developers/how-tos/index.html on enabling this action for a repository.
  - [ ] Cookiecutter could ask if the repo is private, and only include this if it is private. 
- [ ] Make this action available to repos (which may be private) in https://github.com/openedx/edx-cookiecutters
- [ ] Ticket follow-up for ADR on how to handle coverage for public repos going forward (this vs codecov).

**Comment by jmbowman** [comment]
Another option is to subscribe to coveralls for private repos.  We previously migrated off of it in favor of codecov, but it is much less expensive than codecov for private repos (we could use it on 10 private repos for $50/month, vs. nearly $5,000/month for codecov).  On the other hand, there probably would be some vendor review involved and it's not free, so a diff-cover approach is fine as long as it doesn't turn into a large development effort.

**Comment by dianakhuang** [comment]
As part of the April hackathon, we did do some digging into some alternatives, and we found https://github.com/py-cov-action/python-coverage-comment-action , which is a project that we believe will provide us a GitHub action that will handle all the use cases we care about.

https://github.com/nedbat/hackathon-edx-exams-copy is a repository that we implemented this action in. (see PRs: https://github.com/nedbat/hackathon-edx-exams-copy/pull/1, https://github.com/nedbat/hackathon-edx-exams-copy/pull/3)

**Comment by robrap** [comment]
Ponderosa is most interested in this, but we don't know when they are going to want it.

**Comment by dianakhuang** [comment]
We have a sense that we won't get feedback on the documentation until after June, so I will split out cookiecutter work into its own ticket for then along with the ADR ticket.

**Comment by dianakhuang** [comment]
Ticket for implementing it for an edx private repo: https://2u-internal.atlassian.net/browse/PON-163

**Comment by robrap** [comment]
@dianakhuang: Consider adding a note to https://2u-internal.atlassian.net/wiki/spaces/IT/pages/13084109/How+to+request+a+new+GitHub+repo explaining. Please timebox and then close this out. Thanks.

**Comment by dianakhuang** [comment]
Added the note to the documentation.
