### ISSUE TITLE
Add missing user groups to docs.edx.org

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#270]
AC:
- [ ] Have design discussion with @nedbat.
- [ ] Minimally add links for Documentors and Translators (or a general link for other user groups)

The site https://docs.edx.org/ is in https://github.com/edx/docs.edx.org, which is owned by arbi-bom, is missing links to information that exists on https://docs.openedx.org/, for example the user groups Documentors and Translators.

Is there any organization to our docs site that could minimize changes when new user groups are added, or should we just update as required? In either case, docs for all user groups should probably be represented, or there should be a general link provided.

Note: Ned could potentially just pick up this ticket.

**Comment by robrap** [comment]
Note: @nedbat has sort of been managing these docs, and arbi-bom owns them according to the ownership spreadsheet.

**Comment by nedbat** [comment]
PR: https://github.com/edx/docs.edx.org/pull/24
