### ISSUE TITLE
Remove obsolete Jenkins jobs

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#28]
There are perhaps a dozen jobs on https://build.testeng.edx.org/ which haven't been run in months, if ever.  Inquire with the creators which of these are safe to remove now, and get rid of those.

A/C:

- [x] Identify the owners of all jobs on build-jenkins that haven't been run in more than 4 months
- [x] Ask those owners if they have any objection to deleting these jobs
- [x] For the ok to delete list, disable and then delete each job
- [ ] For each job on that list, also remove the corresponding configuration in jenkins-job-dsl

**Comment by robrap** [comment]
Migrated from https://2u-internal.atlassian.net/browse/ARCHBOM-1968

**Comment by jmbowman** [comment]
I've reviewed all the remaining jobs, and deleted the ones which are clearly no longer in active use.  SRE is coordinating with other squads to finish migrating the last 2 jobs in active use.  The last remaining task for Arch-BOM here is to help purge any remaining configuration code that is no longer needed, and that is perhaps best deferred until after we've finished shutting down the server.

**Comment by jmbowman** [comment]
Note to self: much of the Terraform in https://github.com/edx/terraform/tree/master/plans/testeng can go away, especially https://github.com/edx/terraform/blob/master/plans/testeng/terraform.tfvars .  Ask SRE for help sorting this out once the other PRs are ready for review.

**Comment by robrap** [comment]
@jmbowman: I'm not sure which Jenkins server this is about, but can you check out https://2u-internal.atlassian.net/browse/ISRE-1461?focusedCommentId=643329 and confirm if I can delete all this from New Relic? Thanks.

**Comment by jmbowman** [comment]
@robrap Yes, I'm pretty sure that was for the defunct server mentioned in the issue description.

**Comment by jmbowman** [comment]
Note to future self: the script added in https://github.com/edx/edx-internal/pull/6222 can go.

**Comment by robrap** [comment]
> @robrap Yes, I'm pretty sure that was for the defunct server mentioned in the issue description.

Great. These have been deleted.

**Comment by jmbowman** [comment]
Also should review the edx-platform folder in tools-edx-jenkins to see if any of that can go: https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/19239017/Inventory+of+Current+Tools+Jenkins+Plugins+Folders?focusedCommentId=113279379

**Comment by jmbowman** [comment]
Three work-in-progress PRs have been created:

* https://github.com/edx/jenkins-job-dsl/pull/1657
* https://github.com/openedx/testeng-ci/pull/362
* https://github.com/openedx/configuration/pull/6929

They should be safe to merge as is, but may not yet be complete (although I think they're getting close).  SRE [recently deleted](https://2u-internal.atlassian.net/browse/ISRE-1869) the entire `testeng-secure` repository, which was also related.  I haven't yet followed up on the notes above regarding `edx-internal` or the edx-platform folder in tools-edx-jenkins.

**Comment by jmbowman** [comment]
I also created https://github.com/edx/edx-internal/pull/8349 .  Given that SRE already deleted the Terraform mentioned above, I think that covers everything in this ticket other than the tools-edx-jenkins edx-platform folder (which I still don't have access to).

**Comment by jmbowman** [comment]
There is also a https://github.com/edx/jenkins-configuration repository, but as far as I can tell nearly everything in it is also utilized for other Jenkins servers that still exist.  Some of the plugins that it configures may not be needed on the remaining servers for the jobs they currently run, but it doesn't feel worth going down that rabbit hole right now.

**Comment by jmbowman** [comment]
The removal PRs (about 10,000 lines of code overall) have been merged and it's been almost a day without needing to revert, closing the issue as done.
