### ISSUE TITLE
Check if `JWT_PRIVATE_SIGNING_JWK` is present in vault or edx-secure

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#284]
In https://github.com/openedx/edx-platform/issues/32054 we're working on removing `JWT_PRIVATE_SIGNING_JWK` from CMS. CMS no longer requires this value (as far as we are aware) and so it has been removed from remote-config for stage, but it's not clear whether there might be a copy sneaking in via edx-secure. We'd like to get some SRE support in determining whether it's in there.

- [ ] Check whether `JWT_PRIVATE_SIGNING_JWK` is present in edx-secure, and if so, whether it matches what's in edx-remote-config. (Just looking at the `kid` key ID field should be sufficient; edx-remote-config is up to `lms{stage,prod}002`.)
- [ ] Check whether `JWT_PRIVATE_SIGNING_JWK` is present in Vault, which is possible because we've been looking at setting up LMS in k8s. If so, we'd like to know what `kid` value is in there.

**Comment by rgraber** [comment]
I did not see the key in vault. I cannot check edx-secure so I'm escalating this to PSRE. Just a note to PSRE: we originally got the value from edx-secure for LMS, this ticket is for checking if it's in CMS.

**Comment by adzuci** [comment]
Left some comments on the PSRE ticket.

**Comment by robrap** [comment]
@rgraber: Don't close this until either this has been removed, or we have properly ticketed the cleanup

**Comment by rgraber** [comment]
The ticket to actually do the removal is here: https://github.com/edx/edx-arch-experiments/issues/295

**Comment by timmc-edx** [comment]
Outcome:

- It's in edx-secure, with the 002 `kid`
- It's not in Vault
