### ISSUE TITLE
Remove defunct AWS accounts from IAM script list

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#293]
The list of accounts in https://github.com/edx/edx-internal/blob/master/scripts/assume-role.sh#L3 includes a few that I believe no longer exist (testeng, testeng-readonly, and it-jenkins).  This list should be reviewed, and any no longer relevant accounts removed from it.

A/C:
* Already deleted accounts are no longer in the assume-role script list

**Comment by rgraber** [comment]
We might be able to get rid of that entire script https://github.com/edx/edx-internal/pull/8369
