### ISSUE TITLE
Middleware to delete unwanted cookies

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#297]
A/C
- [ ] Django setting of a list of cookie names and name patterns
   - [ ] edx-user-personalized-recommendation
   - [ ] Check list in runbook for others
- [ ] CookieMonitoringMiddleware updated to check requests for matching cookies and at response time sets the cookies to the empty string with an expiry in the past
- [ ] Update the runbook to include the possibility of adding to the list of cookies to delete, esp if you have discovered something and it's in the process of being resolved

We might like to have a middleware that can detect and delete cookies matching a certain name or name pattern.

Motivation: 5 months ago we stopped setting the `edx-user-personalized-recommendation` cookie (because it was over 1kb in size) but we still see it in 10-20% of large-cookie log messages. We don't currently have a way of clearing these cookies out of users' browsers, but if we could do so, it would both help us avoid approaching the 16k max header limit and also reduce noise in our monitoring.

We may also need to match patterns (or at least prefixes) because we've seen requests with tens of cookies like `amp_cookie_test{RANDOM_CHARS}` and we can't get rid of those using fixed names.

**Comment by robrap** [comment]
I would propose we add this as an additional feature of `CookieMonitoringMiddleware`. Benefits:
* We don't need to add yet another middleware for similar functionality.
* There is an order dependency between the cleanup and monitoring, because it would be great if the cleanup could happen **before** we detect sizes so these don't contribute to our monitoring as they are being cleaned up, which may have a long tail.

**Comment by timmc-edx** [comment]
It definitely seems like the right place, but it's unfortunate that it's currently called a _monitoring_ middleware.

**Comment by timmc-edx** [comment]
I don't think there's an ordering dependency, though. The deletion has to happen on the response side anyhow, so the monitoring middleware should just ignore the listed cookies at request time, or at most say "and XXX bytes of cookies to delete".
