### ISSUE TITLE
[Discovery] Homegrown metrics solutions

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#301]
A/C

- [ ] A recommendation and basic implementation plan for a metrics solution
    - [ ] the solution includes: NPS, reliability, change failure rate, deployment frequency, code review timing, mean time to recover
    - [ ] nice to have but unlikely: onboarding time 
- [ ] Issues for further work

Implementation note:
Adam Blackwell may or may not be already doing some things with deployment frequency, might be useful to check in with him
We are trying to get Atlassian Compass turned on, whoever works on this should check in on progress there

Possible avenues:
Prometheus/Grafana
New Relic - 30 day expiration
Apache DevLake

**Comment by jmbowman** [comment]
Relatedly, there's a Backstage plugin for displaying DORA metrics from DevLake: https://github.com/DevoteamNL/opendora

**Comment by jristau1984** [comment]
I propose closing this ticket, as the metrics effort has moved to the executive level to move forward.
