### ISSUE TITLE
Compile list of changes that affect our system for Django 4.2 upgrade

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#309]
Create a document to list all the changes from Djonago 4.0, 4.1, and 4.2 releases that can affect our services and packages.

**Comment by UsamaSadiq** [comment]
Initial findings have been added in the document https://openedx.atlassian.net/wiki/spaces/AC/pages/3768123412/Django+4.2+Upgrade+Key+Changes.
