### ISSUE TITLE
Set up Arbi-BOM team in OpsGenie

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#31]
This is to complete setup of the Arbi-BOM team in OpsGenie: https://2u-internal.app.opsgenie.com/teams/dashboard/b6fb91e8-a11d-44c2-9bda-3cf8639ff539/main

Note: It may be as simple as adding the team members to the rotation. See additional comments.

**Comment by robrap** [comment]
@awais786: I made you an Admin of your team in OpsGenie, so you can update it as you wish. You could also some or all of the rest of your team admins, depending on how you wish to manage it.

There are 2 options for escalations:
Option 1. Leave the default configuration and just add your team to the rotation. It is set up to ping the first person, if not response it pings the next person, and finally it pings everyone.

Option 2. Create a separate rotation for primary and secondary. The benefit is that the secondary gets notified that they are starting/ending their secondary rotation. The disadvantage is that you need to manage the two rotations, and ensure that whoever is secondary one week is primary the next week. It may be simplest to just start with Option 1 and have people track when their rotation is coming up.

Also, do you want to rotate weekly? That is what we do.

**Comment by robrap** [comment]
@awais786: Note: I added a Primary rotation. You can edit it as you wish, including start day and time. Note that you won't get alerts until you configure your own, or we start pointing our overnight on-call coverage to your team.

**Comment by awais786** [comment]
@robrap Thanks for sharing. We are exploring it now.
