### ISSUE TITLE
Include openedx/.github in the ownership spreadsheet

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#311]
For some reason, the ownership spreadsheet contains `edx/.github` but not `openedx/.github`. (Perhaps we track based on shortname, not fullname.) We probably want to ensure it is tracked.

This is currently the only case of both orgs having a repo with the same name, although that could change over time (and we might not notice):

```
$ cd ~/mirrored-orgs/
$ comm -12 <(ls -A1 edx | sort) <(ls -A1 openedx | sort)
.github
```

New AC:
- [x] Update docs to clarify heuristic of ignoring the non-edx repos with a naming conflict

Note: We decided the following changes were not important enough for what are likely to be Axim owned repositories.

A/C:
* ~~Update the code that filters out duplicate repository names (may just be using a dict)~~
* ~~Update any automation which counts on the first column being unique~~
* ~~Populate the correct information for the new row~~
* ~~Announce the change in the ownership channel, so people know where to report breakage~~

**Comment by robrap** [comment]
We could improve the comment, but https://github.com/edx/jenkins-job-dsl-internal/commit/1400c47e22e2efdae71ae348360cbb16a8fb6156 is where we ignore repos of the same name that are not "edx". I think this remains a reasonable heuristic. We can always add notes on that line about the fork, if there is something important to call out.
