### ISSUE TITLE
Plan work for required .readthedocs.yaml files

### ISSUE THREAD

**Issue by nedbat** [edx/edx-arch-experiments#316]
ReadTheDocs is going to require .readthedocs.yaml files in September: https://blog.readthedocs.com/migrate-configuration-v2/

We should plan this work using the [Upgrade Project Runbook](https://openedx.atlassian.net/wiki/spaces/AC/pages/3660316693/Upgrade+Project+Runbook).

**Comment by jmbowman** [comment]
Note that the official filename to use for this is now `.readthedocs.yaml`; usage of such other names such as `.readthedocs.yml` (which we currently use more often) is deprecated: https://docs.readthedocs.io/en/stable/config-file/index.html .

**Comment by iamsobanjaved** [comment]
Created tickets for further action:

- https://github.com/edx/edx-arch-experiments/issues/417
- https://github.com/edx/edx-arch-experiments/issues/418
