### ISSUE TITLE
Update 2U internal devstack documentation

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#318]
We have some feedback from folks from within 2U on how to improve devstack documentation.

A/C:
- [x] Updated documentation that makes clear when to use hosted devstack and when not to.
- [x] Incorporate the "hints" section of https://2u-internal.atlassian.net/wiki/spaces/TNL/pages/170360918/Guided+lab+Develop+with+Devstack#Tips-installing-devstack into proper documentation
- [x] Indicate where to go to help for hosted and non-hosted devstack
- [x] Incorporate any other bits from https://docs.google.com/document/d/1DkRLLKl1CNUwkg3L98x0qakhpg1XNJr4Zhj9JCTEZ2o/edit?usp=sharing that seem useful

Implementation Details
- A 2U employee wrote up this feedback (restricted access): https://docs.google.com/document/d/1DkRLLKl1CNUwkg3L98x0qakhpg1XNJr4Zhj9JCTEZ2o/edit?usp=sharing
- We want to be clear on when we recommend hosted devstack.

**Comment by robrap** [comment]
FYI: I saw this new comment: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/53674147/Hosted+Devstack?focusedCommentId=465338421. I wonder what team or teams the comment `Now that hosted devstack is being created for new devs...` applies to, and whether we can also add clarity if there are certain squads that are largely using it?
