### ISSUE TITLE
Development data

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#320]
This is the  epic for the work to improve the provisioned developer data for edx-platform and other services.

```[tasklist]
### Tasks
- [ ] https://github.com/edx/edx-arch-experiments/issues/290
- [ ] https://github.com/edx/edx-arch-experiments/issues/138
```

**Comment by jristau1984** [comment]
I have moved reference of this epic to Confluence: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/1154875404/BOM+Epic+Proposals

I have confirmed all linked takss have the Developer data epic applied, as does this ticket for historical reference. I am closing this ticket as replaced by the Epics custom project field.
