### ISSUE TITLE
Pipeline automation between EC2 service pipeline and k8s pipeline

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#328]
Do we need to automate hooking up EC2 pipelines with k8s consumer pipelines, rather than making this manual and having the consumers potentially get out of sync? When will this start causing issues?

**Comment by robrap** [comment]
Maybe we just ignore this until everything is in k8s?

**Comment by robrap** [comment]
For now, we've continued to put effort toward containerization, rather than into linking the GoCD pipelines. Hopefully dealing with manual deployments of the k8s consumer containers is good enough. If not, we can remove this from the icebox.

**Comment by jristau1984** [comment]
We will be rolling this goal into the containerization effort, so this is no longer needed.
