### ISSUE TITLE
Fix event replay to work with new --extra arg

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#332]
**A/C:**

- [x] Get replay to work on Stage
- [x] Update runbook as necessary
- [x] Once working, notify SRE about the k8s YAML mangling.

**Notes:**

- Replay with new `extra` arg was not tested after the new arg was introduced, and it does not seem to work yet.
- Unfortunately, requires 3 layers of quotes: 1) bash command, 2) extra arg, 3) in json. Attempts used
- Runbook [Replay Events on the Event Bus](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/266993906/Replay+Events+on+the+Event+Bus) was updated, but it does not yet work.  
- First attempt did not work:
  - https://github.com/edx/edx-internal/commit/1496d119aba82ee9ef0186959190d2050d9edec2
  - https://github.com/edx/edx-internal/pull/8617
  - Error from [ArgoCD](https://argocd.tools.edx.org/applications/argocd/stage-course-discovery?view=tree&resource=&operation=true): `Error: YAML parse error on course-discovery/charts/django-ida/templates/workers.yaml: error converting YAML to JSON: yaml: line 23: did not find expected key Use --debug flag to render out invalid YAML` 
- @timmc-edx noted: "You might have to use [consults https://yaml-multiline.info/] the "folded stripping block scalar header", `>-`, rather than `|`"
  - PRs were created to try this. We'll see what happens.
    - https://github.com/edx/edx-internal/pull/8618
    - https://github.com/edx/edx-internal/pull/8619
- An ugly solution would be to use `\u0027` for `'` inside the json, which leaves only 2 other layers of quotes. For example:
```
command: |
             bash -c "./manage.py consume_events -t course-catalog-info-changed -g course_discovery_prod --extra '{\u0027offset_time\u0027: \u00272023-06-14T04:20:00\u0027}'"
```

**Comment by robrap** [comment]
1. Tried `>-`, rather than `|`, but seemed to result in the same error.

2. Tried the JSON escaping (`\u0027`) in https://github.com/edx/edx-internal/pull/8626, which also didn't work. 
This gave the error `unrecognized type: string.`.

- I'm not sure where the argocd logs are?
- I'm not sure if the `--debug` note from the first error would help at all?
- I don't know how to proceed.

**Comment by robrap** [comment]
@timmc-edx determined that `:` should be replaced with `\u003A` in the next attempt.

**Comment by robrap** [comment]
Tried the updated encoding in https://github.com/edx/edx-internal/commit/7b808d0f551839e589184aa86096c01641f61d7b, and we got past the YAML. The container tried to start. However, we got the following error, even though it seemed 

Error:
```
2023-06-20 20:09:14,226 INFO 1 [algoliasearch_django.registration] registration.py:77 - REGISTER <class 'course_discovery.apps.course_metadata.algolia_models.AlgoliaProxyProduct'>
29
2023-06-20 20:09:21,320 ERROR 1 [openedx_events.management.commands.consume_events] consume_events.py:74 - Error consuming events
28
Traceback (most recent call last):
27
  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/openedx_events/management/commands/consume_events.py", line 65, in handle
26
    extra = json.loads(options.get('extra') or '{}')
25
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
24
    return _default_decoder.decode(s)
23
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
22
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
21
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
20
    obj, end = self.scan_once(s, idx)
19
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
18
System check identified some issues:
```

Although I checked that the following works:
```
>>> json.loads('{\u0022offset_time\u0022\u003A \u00222023-06-14T04\u003A20\u003A00\u0022}')
{'offset_time': '2023-06-14T04:20:00'}
```

The final output uses single quotes, and JSON expects double quotes, so the code https://github.com/openedx/openedx-events/blob/5d936baf70c6ab85bd61eac2224bcb58a0a1069a/openedx_events/management/commands/consume_events.py#L65 needs to correct the quotes. Also see https://stackoverflow.com/questions/4162642/single-vs-double-quotes-in-json. I'm not sure of the cleanest way to clean this up.

**Comment by timmc-edx** [comment]
I don't think we want to try to swap out the JSON quotes in the management command -- our YAML parsing is just plain broken somewhere in the deployment stack, and that's what we need to fix.

**Comment by robrap** [comment]
> I don't think we want to try to swap out the JSON quotes in the management command -- our YAML parsing is just plain broken somewhere in the deployment stack, and that's what we need to fix.

There are two ways to go on this ticket, which are not mutually exclusive:
1. Look into the YAML parsing that Tim mentioned, and/or
2. Update the commands to switch back from `extra` args JSON back to individual args, but they need to be more like kwargs.

**Comment by robrap** [comment]
[suggestion] Create a new ticket in openedx-events to move part of this discussion.

For discussion on the new ticket:
* Include the redis folk, but don't block yourself as long as changes are backward compatible.
* We can discuss whether or not we want to deprecate/remove the current extra args.
* Are you imagining `handle_extra_args` would be sent the parsed dict? Also, what if someone used `-o 'my string with spaces' -d 2023-06-22`?

**Comment by timmc-edx** [comment]
This should be resolved with the combination of https://github.com/edx/edx-arch-experiments/issues/341 and https://github.com/edx/edx-arch-experiments/issues/343

**Comment by robrap** [comment]
Looks complete.
