### ISSUE TITLE
Update and transfer catalog event monitoring

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#333]
Note: This ticket is a bit larger than one might initially think, because it entails splitting out monitoring and runbook so that it is clear what is needed for the owner of an event (producer and consumer), vs what is needed by arch-bom for watching from a high-level (if anything).

A/C:
- [x] Transfer catalog event consumer monitoring to Phoenix
- [x] Transfer studio event producing monitoring to TNL
- [x] Ensure Arch-BOM maintains proper safety-net monitoring
- [ ] Ensure there's a step in event bus onboarding where teams prepare to monitor their new events (may already be there?)

Notes:
- Requires discussing with each owning team.
- Probably requires new policies in New Relic.
- May require new runbooks or at least updating the runbook.
- The Arch BOM work is to split the current alerts and runbooks into team-specific vs safety net, and then handing the team specific ones to TNL/Phoenix. 
  - Consumer alerts for CATALOG event move to Phoenix
  - Producing alert for CATALOG events move to TNL
  - Arch-BOM retains safety-net alerts for overall issues (e.g. at a higher threshold).

**Comment by rgraber** [comment]
TNL ticket: https://2u-internal.atlassian.net/browse/TNL-11110
Phoenix ticket: https://2u-internal.atlassian.net/browse/PROD-3712
