### ISSUE TITLE
Builds should fail when npm install fails

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#335]
Occasionally, `make dev.up.frontend-app-*` will fail when running `npm install`, but then will keep going and attempt to start up the server regardless. This results in errors that are difficult to diagnose because it's not obvious that the failure was in the install step. [This command](https://github.com/openedx/devstack/blob/399c8f097dced30f560b8a64cf528d9bd472f6ed/microfrontend.yml#L7) should not move on to `npm start` if `npm install` fails. This may also be an issue when building edx-platform frontend code.

Acceptance Criteria:
- [x] Microfrontend command uses `npm ci` instead.
- [x] When bringing up an MFE in devstack, any failure in `npm ci` kills the whole chain of commands.
- [x] During edx-platform provisioning, any npm install failures should kill the whole provisioning script.

Implementation Details:
- The MFE case should be handled by the command listed in the description.
- In edx-platform, that will most likely be in one of the devstack provisioning scripts for lms or studio (or both).
- Recommend talking to FEDx about whether or not we want an npm install running when we bring up a devstack container.

**Comment by timmc-edx** [comment]
https://github.com/openedx/devstack/pull/1107 should take care of MFEs in devstack in general. Still need to look into the edx-platform provisioning part.

**Comment by timmc-edx** [comment]
edx-platform appears to touch npm at a couple points.

- In the `node_prereqs_installation` method of `pavelib/prereqs.py` (called by LMS devstack provisioning) there is a call to `npm clean-install`, the longer name for `npm ci`. We may want to use the shorter, more commonly used name.
- The Dockerfile uses `npm install`. This might not affect provisioning directly, but we should fix it: https://github.com/openedx/edx-platform/pull/32590

**Comment by timmc-edx** [comment]
Leaving ticket open for a bit to ensure that deploys and devstack images continue working.
