### ISSUE TITLE
Determine timeline for event bus milestone

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#34]
Note: This is somewhat blocked on determining when and if we get focused resources, but we can try answering the following:
- How many person hours do we think this will take?
- How many days with a focused team (4 engineers?)
- How many days with an unfocused team (1.5 engineers)

**Comment by rgraber** [comment]
Ambitious goal: Finish by July 30 (when @rgraber will be going on vacation)
Otherwise, finish by Aug 12 (when @rgraber gets back from vacation)
