### ISSUE TITLE
Fix quoting of string values in helm-charts

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#343]
https://github.com/edx/helm-charts contains a number of instances of text data being interpolated into YAML without quoting or escaping. This is OK when the content is of a controlled form, but in other cases it can break deploys or mangle configurations.

An example is in the django-ida worker command, where a piece of shell script is interpolated into a larger shell script. Because the templating is performed _before_ YAML parsing occurs, any newlines, quotes, colons, etc. in the IDA's configured shell command are allowed to modify the structure of the YAML. When we tried to [include some JSON in the command line for course discovery](https://github.com/edx/edx-internal/pull/8600/files), a colon in the JSON was interpreted as a key-value mapping separator, and Kubernetes was not able to launch new pods. A [change in `django-ida/templates/workers.yaml`](https://github.com/edx/helm-charts/compare/a6e37cd0030b304172e7f20f20d7e0e0ced1da33..8c5206685ea9c460988b13f611380edfffe108d1#diff-774118e4450d45bbaa43cc9cab60e9c8e60c77cb1a09ebdbb5d9846ccec0bf04) fixed this for all workers.

- For any other places where we **interpolate** shell scripts and other "uncontrolled" text into YAML strings, we should be using this `"... {{ regexReplaceAll "^\"|\"$" (quote $someValue) "" }} ..."` technique. There are at least two known places where this should be done -- cronjobs.yaml and app-deployment.yaml both include a shell command string from the IDA's config. This is the approach to use: https://github.com/edx/helm-charts/blob/8c5206685ea9c460988b13f611380edfffe108d1/django-ida/templates/workers.yaml#L28-L30
  - Here's a PR to fix two such instances: https://github.com/edx/helm-charts/pull/91
- There may be places where the **entire value** is a single config value. In those cases, we should just use `{{ $someValue | quote }}`. Even "safe"-seeming values like `no` and `22:22` are [not actually safe in YAML](https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell) so a maximalist approach may be warranted.
- There may be places where the containing string needs to be multiline and you need to interpolate uncontrolled text into it. In that case, the containing string will need to be translated into a double-quoted flow string with explicit `\n` marks, and then the first technique will work. If it *also* requires indentation in places... I don't know what to do, since indentation is swallowed by the double-quoted flow string scalar.

https://github.com/edx/edx-arch-experiments/issues/341 contains experiment logs on how to safely interpolate text in Helm templates, and may be of interest.

**Comment by rgraber** [comment]
Closing this since there's no more work for arch to do on it. The ticket is now fully on SRE's board.
