### ISSUE TITLE
DEPR JWT_AUTH_REFRESH_COOKIE in edX org

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#353]
To track my DEPR work for this ticket in the edx org. There's not much left, but wanted a ticket for tracking.

DEPR ticket for openedx org exists here: https://github.com/openedx/public-engineering/issues/190

Search for edx org usage is here: https://github.com/search?q=org%3Aedx+JWT_AUTH_REFRESH_COOKIE&type=code

**Comment by robrap** [comment]
I'm not clear if the openedx configuration repo setting `COMMON_JWT_AUTH_REFRESH_COOKIE` is blocking the rest of the edx-internal clean-up?: https://github.com/search?q=%28org%3Aedx+OR+org%3Aopenedx%29+COMMON_JWT_AUTH_REFRESH_COOKIE&type=code

**Comment by robrap** [comment]
I'm moving this out of in-progress until I land my other open threads.

**Comment by Yagnesh1998** [comment]
assign me

**Comment by robrap** [comment]
@Yagnesh1998: This ticket is for my company. Instead, please use `assign me` on the original DEPR ticket here: https://github.com/openedx/public-engineering/issues/190

**Comment by robrap** [comment]
Created a bunch of PRs, which can be found here: https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Arobrap+archived%3Afalse+%22fix%3A+remove+JWT_AUTH_REFRESH_COOKIE%22

**Comment by robrap** [comment]
- Here are all related closed PRs: https://github.com/pulls?q=is%3Apr+author%3Arobrap+archived%3Afalse+is%3Aclosed+JWT_AUTH_REFRESH_COOKIE
- Here is a search for usages across both orgs, which now shows nothing: https://github.com/search?q=(org%3Aedx%20OR%20org%3Aopenedx)%20JWT_AUTH_REFRESH_COOKIE&type=code

I'm closing this ticket.
