### ISSUE TITLE
Possible GoCD edxapp pipeline failure notification bug

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#356]
GoCD alerts for failing builds seem to be closed as soon as the stage starts running again when hitting replay, rather than waiting for a success or failure.

This is definitely not as high a priority as fixing actual issues, and may not be important. It can be misleading though. I was surprised to see the ticket Closed so fast, and then I noticed that it was still running.

Not sure if this is helpful at all, but here is the alert where this happened:
https://2u-internal.app.opsgenie.com/alert/detail/9ef161de-ebc4-4093-8963-75be882048b9-1689276078164/logs 

A/C:
- [ ] alerts are not closed unless the stage has successfully passed

Implementation Details:
- Add the stage to the incident alias
- We will need to add alert updates to every job
- There might be some trickiness with figuring out how to tell that all the jobs have passed.

**Comment by dianakhuang** [comment]
This seems like it might be due to issues of pipeline/stage mismatch.

**Comment by robrap** [comment]
@rgraber: [question] Would you be able to add the stage name to the incident title as well? For example, instead of `[GoCD] edxapp build failed on deploy_to_prod_or_rollback` we'd have `[GoCD] edxapp build failed on deploy_to_prod_or_rollback - deploy_ami`. Although this wouldn't pinpoint specific errors, at least we could quickly collect data about the stage that is failing the most.

**Comment by rgraber** [comment]
Ended up with pipeline, stage, and job name in the name.
https://github.com/edx/edx-internal/pull/9047
