### ISSUE TITLE
Enable retry for certain ansible tasks in edxapp pipeline

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#359]
A/C

- [x] Retry `TASK [insightvm_agent : Check if Rapid7 Agent Currently Installed]` in build_edxapp_amis - run_play if it fails
- [x] Retry `TASK [security : Take security updates during ansible runs]` in build_edxapp_amis - run_play if it fails

Some common failures in the pipeline in ansible tasks documented in the runbook were fixed when rerun.

Is it possible to use Ansible's retry capabilities to get these to work without failing a build? Let's try and see.

See https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16386719/edxapp+GoCD+alert+runbook#Common-failure-modes

**Comment by rgraber** [comment]
This should be resolved with https://github.com/openedx/configuration/pull/6965

**Comment by robrap** [comment]
@rgraber: I know we didn't have this in the original AC, but could you update the runbook by adding a link to the PR for those known issues, noting that we hope that the retries will correct the issue. And then, move those sections to the [Common past failures](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16386719/edxapp+GoCD+alert+runbook#Common-past-failures-(should-be-fixed)) section. Thanks.

**Comment by robrap** [comment]
@rgraber: Also, nice job. Glad this ended up being so simple and :crossed_fingers: that it does the trick.

**Comment by rgraber** [comment]
@robrap  updated.

**Comment by dianakhuang** [comment]
Updated notes on retries:

> I think our use of `retries: 3` in Ansible tasks won't actually work unless we also register a variable for the task and then reference it in an until condition, like so:

```
register: edxapp_install_extra_python_reqs
  until: edxapp_install_extra_python_reqs is success
  retries: 5
  delay: 15
```
