### ISSUE TITLE
Clean up [stage|prod]-subscription-* topics from Kafka

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#361]
Now that topics are in terraform, can we clean out the ` [stage|prod]-subscription-*` topics?

- I assume if these topics are ever really needed, we could recreate as a single `lifecycle` topic?
- Do we need to differentiate between b2c and b2b subscriptions?
- Can you communicate with the owning team, and let them know we can easily restore using terraform when needed?
- Can we update the table in the how-to doc, which probably just means deleting the row? See https://2u-internal.atlassian.net/wiki/spaces/AT/pages/174555142?focusedCommentId=511148404

**Comment by rgraber** [comment]
Deleted the topics after talking to @christopappas . We can add the new lifecycle topic when it's needed.
