### ISSUE TITLE
New Relic removing NrUsage and NrDailyUsage 2023-09-01

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#364]
> We’ll be deprecating our NrUsage and NrDailyUsage events for all our consumption-based customers and moving all the metadata fields to our NrConsumption and NrMTDConsumption events. This will help minimize the number of events that need to be tracked and remove duplicate events from workflows.

Searching for these events in our policies and dashboards using the [NRQL search](https://github.com/openedx/edx-django-utils/blob/f4ffe347ccc4554621cac8ea3b83f5c4e2a7e15e/edx_django_utils/monitoring/scripts/new_relic_search.py) results in three hits:

- `--regex 'NrUsage'`
  - https://one.newrelic.com/dashboards/detail/MTk0OTcwN3xWSVp8REFTSEJPQVJEfDE3NDQ3MDU
- `--regex 'NrDailyUsage'`
  - https://one.newrelic.com/dashboards/detail/MjUzMzcxMHxWSVp8REFTSEJPQVJEfDEwOTcxODg
  - https://one.newrelic.com/dashboards/detail/ODgxNzh8VklafERBU0hCT0FSRHw2OTExNDQ

(If rerunning, just use `--regex 'Nr(Daily)?Usage'` to speed things up.)

**Comment by robrap** [comment]
This ticket was being moved to SRE. New Relic is retiring some events. Arch-BOM found 3 dashboards which use the old event. It is unclear if the linked dashboards were created by SRE or New Relic, but they are meant for SRE. We are closing this ticket, since it has been moved to SRE.
