### ISSUE TITLE
Get devstack tickets onto Arch-BOM board

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#368]
Acceptance Criteria:
- [ ] When new bug tickets are filed in the devstack repo, have them show up on the Arch-BOM board (in the No Status) column

Implementation Details
- This will probably need to be a GitHub action similar to the action that puts DEPR tickets onto the DEPR board, though this may be complicated with having to do it across organizations.
   - https://github.com/openedx/.github/blob/master/.github/workflows/add-depr-ticket-to-depr-board.yml

Split off from https://github.com/edx/edx-arch-experiments/issues/291

**Comment by jmbowman** [comment]
We think https://openedx.atlassian.net/wiki/spaces/AC/pages/3710451733/How+to+have+issues+and+pull+requests+added+to+GitHub+Projects#Open-edX-shared-workflow is the appropriate implementation method for this.

**Comment by timmc-edx** [comment]
https://github.com/openedx/devstack/pull/1184 didn't work because the github token is incorrect for this cross-org flow.

**Comment by timmc-edx** [comment]
Filed https://github.com/edx/edx-arch-experiments/issues/467 for getting the correct creds.

**Comment by rgraber** [comment]
Closing this since we managed it with workflows. https://github.com/orgs/edx/projects/11/workflows/13199169
