### ISSUE TITLE
Improve efficiency of handling gocd alerts

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#370]
It takes a while to understand what is wrong in GoCD. Following up on an alert requires VPN and finding failure log in GoCD, and then knowing how to search for the actual failure, depending on where it failed. It would be great if the alerts had more context.

**AC:**

Timeboxed effort -- 1 day.

- [ ] Some useful extract of the logs shows up in the Opsgenie alert (so that we can tell if it's a known/unknown issue, etc.)

**Questions/Notes:** 

- This work would only help in situations where you don't have to go on GoCD to re-run a stage anyhow (e.g. self-closing alerts).
- We want to switch to ArgoCD & Kubernetes relatively soon; are there quick improvements to get more context in alerts, or are there improvements that would carry over?
- Could we get the error details into the alert so VPN and GoCD login isn’t required?
- The Runbook has some notes that can be referenced (or added to) for searching to find errors in logs of various stages.

**Comment by dianakhuang** [comment]
From what I understand, the best we can do is try to pull the GoCD logs from within a Python script in order to extract the failure information, I'm not sure how easy this will be to implement, and the testing for it would be a significant overhead in terms of doing this. I don't think it will be possible to fit this work into the timebox, and I'm not sure it's worth it.

**Comment by robrap** [comment]
@dianakhuang: Is there any way for the script that is failing to gather this info and put it somewhere (environment variable, other) that can be found and used elsewhere in the pipeline?

**Comment by dianakhuang** [comment]
Considering how the GoCD pipelines are configured and the many and varied scripts that are called from it, I don't think there's any way to centralize this behavior and make it consistent.

**Comment by robrap** [comment]
[inform] I am re-opening this ticket, but it was put in the new "Icebox" option of the Arch-BOM project's "Backlog" option.

**Comment by jristau1984** [comment]
Closing this.
