### ISSUE TITLE
Detect and alert DoS attacks

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#371]
Acceptance Criteria:
- [x] Alert Arch-BOM on on DoS attack
- [x] Write up runbook for DOS alerts.
      - [ ] Runbook should mention that we want to alert warroom once we have tuned the alert.
      - [ ] Runbook should mention how to let other teams know that this is happening.
- [x] Communicate with SRE about new alert

Implementation Details:
- Using the NRQL used to produce graph is probably a simple enough idea. The comments have more questions about IP-based custom attributes that aren't needed for this ticket.

------

The point of this is to help us and others understand as quickly as possible that issues being seen is due to an outside cause, rather than a bug released in a recent deployment.

Create New Relic alert (for SRE) to detect DoS attacks, since SRE is able to respond.

- Ideally this would be an SRE ticket. 
- See https://onenr.io/0nQxPyzlXQV for 2023-07-23 attack details. (link data will expire after around 2023-08-20)
- A potential NRQL that would provide the IP and app:
```
SELECT count(ip_chain.raw) FROM TransactionError FACET appName, ip_chain.raw TIMESERIES
```
- Here is how to include the facet details in the alert itself: https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/19262329/Useful+New+Relic+NRQL+Queries+and+Tips#Alerts-with-FACET
- Consider alerting #incident-warroom in addition to SRE to alert others that odd errors may be due to the attack.
- Screenshot from 2023-07-23 attack:
![Image](https://user-images.githubusercontent.com/14576445/255974564-0d16c557-5cfc-4523-ae8b-f1d07849fd07.png)

**Comment by robrap** [comment]
There was also a question of whether we could throttle DoS attacks? 

Here are some notes on the topic:
- See https://www.django-rest-framework.org/api-guide/throttling/ as an example.
- I'm not sure if we need multiple solutions for DRF and plain views?

It would be better to have the alerting, and that will help us see the extent to which this has any urgency.

**Comment by robrap** [comment]
@timmc-edx: I noticed that we just seem to have a custom attribute for `ip_chain.raw`. Many of the IP chains had 2 values (not including 127.0.0.1), where 1 was shared across these requests, and 1 was not. I'm still unclear which is which. In any case, do you have a recommendation of how you'd write the runbook for this, or whether we should have an attribute for something else from https://github.com/openedx/edx-django-utils/blob/master/edx_django_utils/ip/internal/ip.py that would make it simpler to detect and note the IP that should be blocked? get_safest_client_ip? Other?

**Comment by timmc-edx** [comment]
The second-to-last of the chain is probably Cloudflare, so you'd want to look at the first IP to the left of that.

Example of checking if it's Cloudflare: https://www.maxmind.com/en/geoip2-precision-demo?ip_address=162.158.158.51

**Comment by robrap** [comment]
Thanks @timmc-edx.
1. It seems like in your last comment you were answering the question of how to help write the runbook.
2. Do you also think the alerting and runbook would be simpler if we had the result of `get_safest_client_ip` as its own attribute?

**Comment by timmc-edx** [comment]
Yeah, that's the manual step I would take. But I see what you're saying now -- while there's technically enough information in the custom attrs (combine `ip_chain.external.count` with the other info) it would probably be better to add another one that explicitly names the IP just outside the trust boundary (output of `get_safest_client_ip`).

**Comment by dianakhuang** [comment]
New runbook is over here: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/551780388/Large+number+of+requests+from+the+same+IP+address+Runbook

Not sure how to task the follow up work, but maybe we will just be waiting for another incident to occur.

**Comment by robrap** [comment]
@dianakhuang: I recommend we move this to "In Code Review" (I am about to review), and when we are done with review we just close this. I think adding possible next steps in the Run Book, as you have done, as perfect and all we should need to do.

**Comment by robrap** [comment]
@dianakhuang: I reviewed the alert itself as well.
1. I added a "Gap- filling strategy" of "Custom static value" and 0. We should probably fill this in on all alerts.
2. I think we should add an explicit priority. I think the priority of all the alerts in that policy are P1 by default, but making it more explicit like we have in https://onenr.io/0PwJEYVxkQ7 would be cleaner.

I am also done with the Confluence page, and you can mark all the comments resolved when you are done.

Once this is all wrapped up, we can close this.

**Comment by robrap** [comment]
Thanks @dianakhuang. I made one more small update to the Runbook noting about considering bumping to P1 once it is stable.
