### ISSUE TITLE
Write up what we do related to site cookies

### ISSUE THREAD

**Issue by davidjoy** [edx/edx-arch-experiments#372]
# Background 
Amber Dorst over in Marketplace was willing to explore whether one of her teams (or adjacent teams) would be able to take over ownership of site cookie monitoring.  

She asked us to write up what we do related to site cookies, how we monitor, etc., so she can help figure out where it should go.  

# Current State

Initial draft of the ownership transfer document is here: [Site Cookie Size Monitoring - Ownership Transfer](https://docs.google.com/document/d/1-FOhlSi-g__NjZ6CW7LjQdfoTIFEiEBO5T1HVI2Cjdw/edit)

# Open Questions/Subtasks

- [x] Where are the cookie size alerts configured in New Relic? Link them into this document.
- [x] What is the name of the alert(s)?  Update the runbook name to match, clarify that “xyz” is referring to whatever environment the alert came from.
- [x] What else is missing from the transfer process/are there other systems involved beside NR and OpsGenie?
- [x] Any other related documents we’ve missed?
- [x] Does the ownership transfer process below look correct?  Update with details (particularly for the NR and OpsGenie transfers).  What additional knowledge would we want to transfer in person, if anything?  If nothing, assume that a transfer session will be done only if the receiving team wants it.

# Acceptance Criteria

- [x] A document describing how we would transfer ownership of site cookie monitoring. 
- [x] Send the document to Amber Dorst
- [x] Determine next steps/timeline for ownership transfer

# Existing docs linked in standup

- [Cookie Size Dashboard](https://one.newrelic.com/dashboards/detail/ODgxNzh8VklafERBU0hCT0FSRHwxNjI4NDY0) (New Relic)
- [Cookie Best Practices](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16385315/Cookie+Best+Practices) (Wiki)
- [Runbook for Very large cookie headers in xyz](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16385229/Runbook+for+Very+large+cookie+headers+in+xyz) (Wiki)
- [Cookie Handling](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16385461/Cookie+Handling) (Wiki)

**Comment by robrap** [comment]
Moving this to Blocked while assigned to @davidjoy. David - please let us know when you are done with this ticket.

**Comment by dianakhuang** [comment]
i have updated the doc. I don't think we need to do a synchronous transfer session unless the receiving team wants it.

**Comment by dianakhuang** [comment]
Closed because we have acknowledgement from the new team, and if there needs to be any followup work that results from their review, we can make a new ticket with those action items.
