### ISSUE TITLE
Upgrade django-simple-history in edx-platform

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#376]
As we are upgrading dependencies to have support for Django 4.2, we need to upgrade `django-simple-history` in our services to have support for Django 4.2. We currently have a pin for `django-simple-history==3.0.0` in global constraints as it was creating migrations. So in this upgrade, we have to cater all those migrations and create an appropriate upgrade plan to avoid any database lock.

**Comment by awais786** [comment]
We need to mention in release notes.
