### ISSUE TITLE
Basic Auth is broken on sandboxes

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#388]
It seems sandboxes are broken with Basic Auth is enabled in Jenkins (which is the default). The problem seems to be that the subsequent requests from the MFE have the header 'Authorization: Basic xxxxxxx' included, and these return an invalid username/password error.  I am unable to log in via the AuthN MFE. 

Is it possible that this used to work by not passing this header on to Django? Other?

I'm escalating this to SRE because I think this is owned by SRE.

Note: This replaces https://2u-internal.atlassian.net/browse/DOS-3917 which I will close.

**Comment by jmbowman** [comment]
Marking as blocked while we wait for PSRE to address.

**Comment by robrap** [comment]
Dropping BasicAuthentication from sandboxes as a default class fixed the issue. Closing this ticket.

**Comment by robrap** [comment]
@rgraber: This issue is fixed. I commented as such on the PSRE ticket, but Adam still had a long comment on there, so I didn't want to just mark as Done. Should we follow-up or just forget about it?

**Comment by rgraber** [comment]
Given that the solution turned out to be pretty easy it seems like, I think we can ignore it. Reading his comment, it looks like he was more concerned with what to do if it turned out to be hard.
