### ISSUE TITLE
Ownership transfer: GitHub automation

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#393]
A/C
- [ ] Determine if we want to transfer ownership of GitHub automation and, if so, to whom
- [ ] If we want to transfer ownership, write a proposal for the process of doing so

Notes
This may make sense for ArbiBOM

**Comment by jmbowman** [comment]
We think Arbi-BOM already effectively owns this.  If anyone remembers an aspect that Arch-BOM still does, we can revisit.
