### ISSUE TITLE
Ownership transfer: CI / package services

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#394]
A/C
- [ ] Determine if we want to transfer ownership of CI package services and, if so, to whom
- [ ] If we want to transfer ownership, write a proposal for the process of doing so (see https://github.com/edx/edx-arch-experiments/issues/443)

Notes: 
This includes codecov, pypi, renovate, etc. 
Arbi-BOM is a candidate for this

Things that need to happen:
- Update spreadsheet
- Notify new owning teams

**Comment by dianakhuang** [comment]
Renovate - FED-BOM
PyPi, CodeCov - Arbi-BOM

Concerns about permissions.

**Comment by robrap** [comment]
Moving this to backlog as Future work until post reorg in early 2024, when we have more info about what our team will be and what the new org structure looks like.

**Comment by jristau1984** [comment]
Closing for now, as no better owner exists in the slimmed down eng org.
