### ISSUE TITLE
Ownership transfer: Auth backends

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#395]
A/C
- [ ] Determine if we want to transfer ownership of the Auth backends and, if so, to whom
- [ ] If we want to transfer ownership, write a proposal for the process of doing so

Notes: 
This is on the LP tech vision doc as something to give to GUID

**Comment by jmbowman** [comment]
The GUID project effectively is the ownership transfer for this.  Waiting for that project to get far enough to provide clarity on how this will be done.

**Comment by jristau1984** [comment]
There are no teams with available bandwidth to transfer this to at the moment.  If the discussion comes up again, we can log a new request.  No point in having this sit around for years.
