### ISSUE TITLE
Ownership transfer: edX Github org 

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#396]
A/C
- [ ] Determine if we want to transfer ownership of the edX github org and, if so, to whom
- [ ] If we want to transfer ownership, write a proposal for the process of doing so (see https://github.com/edx/edx-arch-experiments/issues/443)

Notes:

- Ownership entails making org-level configuration changes
- SRE is a good candidate for this, since they own other orgs

**Comment by robrap** [comment]
This is intentionally assigned to @jmbowman.

**Comment by robrap** [comment]
Moving this to backlog as Future work until post reorg in early 2024, when we have more info about what our team will be and what the new org structure looks like.

**Comment by jristau1984** [comment]
@robrap I believe this ticket can now be closed... looking at https://github.com/orgs/edx/people/enterprise_owners, it seems SRE is the owner of the parent enterprise that edx org sits in.

I presume that the role above is what was in scope for this task, not the large list of employees in the owner role: https://github.com/orgs/edx/people?query=role%3Aowner
