### ISSUE TITLE
Ownership transfer: ReadTheDocs

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#399]
A/C

- [ ] Determine if we want to transfer ownership of ReadTheDocs and, if so, to whom
- [ ] If we want to transfer ownership, write a proposal for the process of doing so (see https://github.com/edx/edx-arch-experiments/issues/443)

Notes:

- This would be mostly owning the vendor relationship
- Axim should own some of this, not clear where the dividing line would be
- Ned probably has thoughts on who would be the best owner

**Comment by dianakhuang** [comment]
2U is paying for this, but many of the docs are for openedx repos. Part of this work is going to be understanding how many of the docs are for edx repos vs. openedx. Maybe the manager will continue managing the relationship.

**Comment by robrap** [comment]
Moving this to backlog as Future work until post reorg in early 2024, when we have more info about what our team will be and what the new org structure looks like.

**Comment by jristau1984** [comment]
Closing for now, as no better owner exists in the slimmed down eng org.
