### ISSUE TITLE
[Docs] Move Chris hand-off doc to Confluence

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#40]
Acceptance Criteria:

- [ ] Move https://docs.google.com/document/d/1ZiKchmsH82mjjNwZpCRzZXUiCGVy7iuv8hl7zgqEP7s/edit to Confluence
- [ ] Potentially have document reviewed by Chris and are event-busers.

Note: Presentation given by Phil on “k8s bootstrap project” included docs and images that covered much of this. Try to minimize this work, which may include referencing (and/or updating) existing docs.

**Comment by robrap** [comment]
Moved from https://2u-internal.atlassian.net/browse/ARCHBOM-2122

**Comment by rgraber** [comment]
The lines we actually need to edit to deploy the consumer worker:

(stage) https://github.com/edx/edx-internal/blob/31a801883ed959fcab66e7d83cafe6ed014ed287/argocd/applications/course-discovery/stage-config.yaml#L57

(prod) https://github.com/edx/edx-internal/blob/31a801883ed959fcab66e7d83cafe6ed014ed287/argocd/applications/course-discovery/prod-config.yaml#L58

Basically you just need to edit the worker command to run `./manage.py consume_event -with-arguments`

You will also need to add the Kafka/Schema Registry configs here:
(stage) https://github.com/edx/edx-internal/blob/31a801883ed959fcab66e7d83cafe6ed014ed287/argocd/applications/course-discovery/stage-config.yaml#L28

(prod) https://github.com/edx/edx-internal/blob/31a801883ed959fcab66e7d83cafe6ed014ed287/argocd/applications/course-discovery/prod-config.yaml#L29

The secrets should be in the form `{{ .Data.data.KAFKA_API_KEY }}'` so it can get the secrets from the vault. Find out what the actual secret keys are called.

Testing this setup locally is quite hard, especially if you don't already have a local minikube/ArgoCD setup. You can do it, you just have to be willing to make a lot of strange local changes without committing them. You will likely have to test on stage by actually merging changes to edx-internal. 

Any changes to edx-internal config files should show up immediately (within reason) here https://argocd.tools.edx.org/applications/stage-course-discovery?resource= after you merge. 

Anything that changes the service itself or the Dockerfile requires triggering and waiting for the GoCD build. The GoCD pipeline is here https://gocd.tools.edx.org/go/pipeline/activity/course-discovery-build

If you actually need to add something to the vault, that requires SRE. If anything changes in the vault, you'll need to update the version of the vault used on the line linked below. Note that stage and prod have different vaults so may be on different versions. 

(stage) https://github.com/edx/edx-internal/blob/31a801883ed959fcab66e7d83cafe6ed014ed287/argocd/applications/course-discovery/stage-config.yaml#L78

**Comment by rgraber** [comment]
New doc is here https://2u-internal.atlassian.net/wiki/spaces/AT/pages/112197633/Containerization+for+Consumers+Formerly+Chris+Hand-off+Doc

**Comment by robrap** [comment]
I'm reviewing and making small updates.

**Comment by robrap** [comment]
Thanks for getting this done @rgraber! Looks great. I'm putting back to Done.
