### ISSUE TITLE
Ownership transfer: Event bus monitoring

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#400]
A/C

- [x] Determine if we want to transfer ownership of the event bus monitoring and Confluent vendor relationship and, if so, to whom
- [ ] If we want to transfer ownership, write a proposal for the process of doing so (see https://github.com/edx/edx-arch-experiments/issues/443)

Notes
This involves long-term monitoring and owning the relationship with Confluent
SRE is a potential candidate for this one

**Comment by timmc-edx** [comment]
Blocked: Becca is currently working on disentangling alerting.

**Comment by rgraber** [comment]
We're going to keep event bus monitoring and let Degrees keep the overall Confluent vendor relationship. We'll start taking on some of the terraform work.
