### ISSUE TITLE
Missing runbook for Jenkins: Oauth Session management » prod-edx-delete_expired_dot_tokens_refreshtokens

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#401]
We are missing a runbook for failures of this Jenkins job: Build failed in Jenkins: Oauth Session management » prod-edx-delete_expired_dot_tokens_refreshtokens #2967. See OpsGenie alert example: https://2u-internal.app.opsgenie.com/alert/detail/4e41f64c-60bb-4646-81fd-471c55223bd7-1692028905225/details.

Acceptance Criteria:
- [ ] Create a runbook and provide in Jenkins output.
- [ ] From runbook, reference ASG issue and possible fix: https://github.com/edx/edx-arch-experiments/issues/378. Note that rerunning should fix.

**Comment by robrap** [comment]
Failed again on 2023-10-27: https://2u-internal.app.opsgenie.com/alert/detail/ced08fd9-470d-43bf-b63b-897d47e281cd-1698426122205/details

**Comment by rgraber** [comment]
Updated the OpsGenie integration instead of the Jenkins output to link to the runbook to avoid linking to a private runbook in public code (the jenkins job just runs a management command in edx-platform)
