### ISSUE TITLE
Kick off Redis 7.x upgrade process

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#408]
The support window for Redis 6.2 ends just before the end of support for the upcoming Quince release.  Let's see if we can upgrade to 7.0 or even 7.2 before the Quince branches of cut.  Follow the [upgrade project runbook](https://openedx.atlassian.net/wiki/spaces/AC/pages/3660316693/Upgrade+Project+Runbook), and close this issue once there's a roadmap issue on the Arbi-BOM board for further progress tracking.

**Comment by mumarkhan999** [comment]
Roadmap issue for Redis 7.2 upgrade: https://github.com/openedx/platform-roadmap/issues/283

**Comment by mumarkhan999** [comment]
It's being tracked in another ticket.
