### ISSUE TITLE
build_edxapp_ami - run_play fails transiently

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#410]
build_edxapp_ami sometimes fails at the run_play stage with
npm ERR! code ECONNRESET
It's possible we could fix this with a retry. Likely related to the flaky network calls.

**Comment by jristau1984** [comment]
@robrap after almost a year, should this be closed now and a new ticket created if it becomes a problem again?

**Comment by robrap** [comment]
Closing, because this no longe seems to be an active issue.
