### ISSUE TITLE
Finish plan for edxapp containerization

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#419]
A/C:

- [x] We have clearly documented plans for getting CMS and LMS into Kubernetes in production
  - CMS containerization epic: https://2u-internal.atlassian.net/browse/GSRE-545
    - [x] Read through the plans and ensure anything that needs to be changed is listed in this GH issue
    - [x] Ensure that codejail extraction gets added to the epic: https://2u-internal.atlassian.net/browse/GSRE-802
  - LMS containerization epic: https://2u-internal.atlassian.net/browse/GSRE-626
- [x] All blocking work is ticketed and assigned to appropriate teams
  - SRE is the nominal assignee of containerization but will be relying on application teams for some of the work. Arch-BOM in particular will need to handle the codejail work.

SRE has kicked off a project to move all our services from EC2 virtual machines to Docker images in Kubernetes clusters, but is struggling to free up bandwidth to finish the work.  Let's review the current plan and progress so far for edx-platform (edxapp) specifically, and figure out what we can do to get that project over the line.  This is important to us because:

* Our current edx-platform deployment pipeline frequently fails on intermittent issues caused by the pipeline software and infrastructure.
* We want to share the burden of supporting the edx-platform deployment pipeline with other teams, but don't want to increase their cognitive load by training them on a complex, unique pipeline that we plan to replace soon.
* Getting the services into Kubernetes in production makes it possible to craft Kubernetes-based development environments that more closely match prod, instead of having a gulf between VMs in production and docker-compose for development.
* Most new improvements in the software development, deployment, and monitoring ecosystem are requiring Kubernetes as the underlying platform, so we currently can't take advantage of any of those.

The CMS containerization effort is further along, so that should be the first priority.  But we should also review the LMS plan and flesh it out, identifying any blocking work that should be started.  The already identified blockers are:

- https://2u-internal.atlassian.net/browse/PSRE-2663 (for CMS)
- https://github.com/openedx/edx-platform/issues/31517 (for both LMS and CMS)
  - Possible intermediate step: https://github.com/openedx/edx-platform/issues/33538

Ideally the planned CMS and LMS pipelines closely match those of our other newer services

References:

* The overall plan for containerizing all our Django services in production: https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/19238579/Django+Containerization+Project+Plan
* The current state of post-containerization deployment workflows: https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/19271637/ArgoCD
* Recommended Kubernetes learning resource: https://leanpub.com/thekubernetesbook .  Feel free to purchase and expense; there are other (paper, audio, Kindle) versions available via https://nigelpoulton.com/books/, although not all of them get the free updates that the ebook does.

**Comment by robrap** [comment]
@jmbowman: Based on our discussions, I moved https://github.com/openedx/edx-platform/issues/31517 on to our board. Do you want that ticket to wait on this ticket, or is it a clear next step already?

**Comment by jmbowman** [comment]
It can proceed in parallel; it may not end up being the top priority task once the plan is fleshed out, but it's one that we definitely want to get done.

**Comment by timmc-edx** [comment]
OK, I've read through SRE's CMS epic. The only thing that I think is missing is the codejail work, which we can start work on independently.
