### ISSUE TITLE
Fix Django 4.0 and 4.1 removal warnings in course-discovery

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#431]
In order to have support for Django 4.2, we first need to fix RemovedInDjango40Warning and RemovedInDjango41Warning in the course-discovery.

Latest run URL: https://github.com/openedx/course-discovery/actions/runs/6066521644/job/16457207503 

Note: Tests are running in 6 shards, verify that all warnings are fixed.

**Comment by UsamaSadiq** [comment]
PR for this issue https://github.com/openedx/course-discovery/pull/4091
