### ISSUE TITLE
Add Django 4.2 in CI in course-discovery

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#432]
In order to have support for Django 4.2, we first need to run tests on Django 4.2 in the discovery service. For updating CI, we should run tox and GitHub actions modernizers.

Tox Modernizer: [tox_moderniser_django42.py](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/codemods/django42/tox_moderniser_django42.py)

Github Action Modernizer: [github_actions_modernizer_django42.py](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/codemods/django42/github_actions_modernizer_django42.py)

```[tasklist]
### A/C
- [ ] Run tests with Django 4.2
- [ ] Fix all test failures with Django 4.2 (if any, for complex failures create separate tickets)
- [ ] After merging, ask the owning squad to add Django 4.2 tests in branch protection rules
```

**Comment by UsamaSadiq** [comment]
PR in progress for Django 4.2 upgrade https://github.com/openedx/course-discovery/pull/4088.

**Comment by UsamaSadiq** [comment]
Merged PR https://github.com/openedx/course-discovery/pull/4101 for this change.
