### ISSUE TITLE
Fix OwnershipSync bug where edx-platform diffs for top-level directories not detected

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#46]
## Background:

While working on https://github.com/edx/edx-arch-experiments/issues/45, when `common/lib/xmodule` moved to top-level `xmodule`, the spreadsheet sync job did not seem to fail whether it contained the new `xmodule` listing or not. I presume there is a bug in https://github.com/edx/jenkins-job-dsl-internal/blob/1c2a7e55ea9227aca05b40be0ee3fbce073302ea/resources/ownership-sync/sync_edx_platform.py#L34-L36 somewhere that skips these diffs by mistake.

We know it works for new djangoapps, so this may not be urgent, because these top-level directories do not often change.

## Question:

- - Do we want to close as Won't Do? Do we think this is worth any effort at this point, especially with ownership information possibly moving?

## Acceptance Criteria:

- [ ] Verify, find and fix issue with not detecting diffs for top-level directories.

**Comment by robrap** [comment]
Note: the `./common/lib` directory will soon be deleted, as part of https://2u-internal.atlassian.net/browse/BOM-2575. Once it is deleted, we can confirm if the Jenkins job fails to detect this change and report that this directory needs to be deleted.
 
1. We can update this ticket with additional information once we learn that either way.
2. Either way, we'll need to remove `./common/lib` row from the spreadsheet.

**Comment by timmc-edx** [comment]
Looks like this is done now, with `./common/lib` having been removed from the spreadsheet on 2022-09-22.

**Comment by robrap** [comment]
@timmc-edx: That particular row has been deleted, but this issue is not complete. This is still not auto-detected, and an easy way to test is by adding a fake row with this (or any other fake) directory, and seeing that the job does not fail or complain.

**Comment by jristau1984** [comment]
Closing due to low priority and age.
