### ISSUE TITLE
Create a runbook for granting Confluent access

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#466]
There are a particular set of roles we grant people who request Confluent access. We should create a runbook for what to do when someone asks.
We may also want a separate ticket for transferring this runbook to whichever team should actually own this (helpdesk?).

**Comment by rgraber** [comment]
Going forward HelpDesk is giving people access via OneLogin but we're still assigning the roles

**Comment by robrap** [comment]
This is all set. Thanks @rgraber. I'll close it.
