### ISSUE TITLE
Add GitHub app credentials to openedx/devstack so that we can auto-add issues to projects

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#467]
Arch-BOM needs a way to get new openedx/devstack issues added to our GH project (https://github.com/orgs/edx/projects/11). We tried using the openedx [add-to-project.yml reusable workflow](https://github.com/openedx/devstack/pull/1184/files), but it can't use the openedx org secrets to manipulate edx org projects. (Specifically, all we know is that the openedx org has org-wide secrets `GRAPHQL_AUTH_APP_ID` and `GRAPHQL_AUTH_APP_PEM` but the action failed with a permission error.)

It seems like we need some different GitHub app credentials. We'll need to add these to the openedx/devstack repo secrets under different names, and they'll need read/write access to edx projects. (2U will likely be able to reuse this GH app for a number of teams that want to keep track of issues on GitHub instead of on Jira.)

**Comment by adzuci** [comment]
We looked at this in SRE Office Hours and see this action uses a graphql app key in the openedx org which then creates overly permissive tokens dynamically: https://github.com/openedx/.github/blame/master/.github/workflows/add-issue-to-a-project.yml#L34

We also looked at https://github.blog/changelog/2023-01-19-github-issues-january-19th-update/

![image](https://github.com/edx/edx-arch-experiments/assets/278814/42f01e7b-d88d-4226-b3b1-bd35523c251f)

**Comment by adzuci** [comment]
We did find that we can do this: https://github.com/orgs/edx/projects/11/workflows/13199169

![image](https://github.com/edx/edx-arch-experiments/assets/278814/0f304613-7cbc-44a0-b189-dfb9bc95494f)

**Comment by rgraber** [comment]
Closing this as we have confirmed that new devstack issues make it onto the arch bom board.
