### ISSUE TITLE
[Consuming][Infra] Run discovery consumer command on prod

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#47]
A/C

- [x] All concerned parties have been informed that the consumer is being deployed to prod (see How We Announce)
- [x] The consumer management command for course-discovery is running in production
- [x] Documentation for how to use the event bus has been updated with any findings from the launch

Implementation details:

Update this line: https://github.com/edx/edx-internal/blob/c250fee78175e173eaf4960130258b8b4f02de21/argocd/applications/course-discovery/prod-config.yaml#L58 to be `./manage.py consume_event -t course-catalog-info-changed -g course_discovery_prod -s org.openedx.content_authoring.course.catalog_info.changed.v1` . You will actually need to use that exact topic and group id.

Add all the configuration variables here: https://github.com/edx/edx-internal/blob/c250fee78175e173eaf4960130258b8b4f02de21/argocd/applications/course-discovery/prod-config.yaml#L29 . The easiest way to do this will be to copy over the settings from stage-config.yaml and update them to use the correct values for prod (in particular the database/memcache configs).

Update the secret version to the latest version in the vault

**Comment by robrap** [comment]
@rgraber: Can you confirm if this is ready to be groomed and potentially worked on by someone else, or if you have more pre-grooming? It think the Description needs to be updated either way. Also, we could have the AC be "Pair with Becca", unless we think you should just do it, and it isn't useful for educating.

**Comment by rgraber** [comment]
Updated the description. I think anyone could pick this up and it might be useful for other people to see what the container looks like and where we manage configs for k8s.
