### ISSUE TITLE
Add event bus consumers for edx-platform

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#474]
A new exams IDA will be producing events for the LMS to consume: https://github.com/openedx/openedx-events/pull/268

We'll need to revive the edxapp consumer work in order to support this.

**Comment by rgraber** [comment]
We're going to reach out and ask Alie what level of support she and her team need on this before prioritizing/grooming/picking up.

**Comment by rgraber** [comment]
Should we keep this on our board given that another team is working on it?
