### ISSUE TITLE
How can BOM squads get proper access to all repos?

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#475]
While doing some DEPR work, I ran into the following two issues:

https://github.com/openedx/edx-notes-api/pull/350
- Required approval from openedx/content-aurora
https://github.com/openedx/enterprise-access/pull/294
- The base branch restricts merging to authorized users.

Note that another enterprise repo did not have this issue.

Questions:
- Would the owners refuse to provide more access to BOM squads, or does this just require tuning github settings?
- Do we have recommendations for how to best tune the settings for our teams?
- If we won't get more access, what is the simplest process for getting our needs met?
  - It is probably to follow the [Maintenance Board GitHub Project process](https://openedx.atlassian.net/wiki/spaces/AC/pages/3664904195/Maintenance+Board+GitHub+Project),  but that feels like a lot of work, especially for one-line PRs.
  - I wonder if more of the Maintenance Board Github process could be automated, so that you could add a unified label (e.g. “needs maintainer attention”) and maybe a comment about what is needed, and the rest of the fields could be filled in automatically, so no one has to lookup the owner of each repo (as an example).

Next step:
Move relevant details into https://github.com/edx/open-source-process-wg/issues/129

**Comment by robrap** [comment]
I loved the relevant information to https://github.com/edx/open-source-process-wg/issues/129#issuecomment-1773518658. I guess I'll close this ticket.
