### ISSUE TITLE
Cleanup repo health job from Jenkins

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#480]
As we have migrated the repo health job from Jenkins to Github Action in https://github.com/edx/edx-arch-experiments/issues/66, we missed removing the old Job from the Jenkins server. So we need to remove both the job from Jenkins and the code that is there to support the job. Create an SRE ticket if needed to remove job from Jenkins.

Code (current job): https://github.com/edx/jenkins-job-dsl/blob/master/devops/jobs/CreateRepoHealthJobs.groovy

Delete any script related with above mentioned code.

**Comment by UsamaSadiq** [comment]
Follow up [issue](https://2u-internal.atlassian.net/jira/servicedesk/projects/DOS/queues/issue/DOS-4263) created for the SRE team to remove the scheduled Jenkins repo health build.
