### ISSUE TITLE
Rotate MaxMind API key

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#489]
A/C:

- [x] Create new MaxMind account and store the login credentials in an appropriate place
- [x] Create a new API key for the GeoLite product and share it with SRE
- [x] Ensure that we have instructions for rotating this key in the future

We want to rotate the API key used for downloading the MaxMind GeoLite database and ensure that we have the ability to rotate it more easily in the future. This should be pretty straightforward as GeoLite is a free, self-serve product so we don't need to re-establish a vendor relationship.

Notes:

- GeoLite: https://dev.maxmind.com/geoip/geolite2-free-geolocation-data
- Jenkins job: https://tools-edx-jenkins.edx.org/job/geoipupdate/
  - Backing script: https://github.com/openedx/ecommerce-scripts/blob/master/geoipupdate/pull.py
  - Example PR created by this job: https://github.com/openedx/edx-platform/pull/32006
- Some kind of possibly-related GitHub team: https://github.com/orgs/edx/teams/jenkins-tools-geoipupdate

**Comment by rgraber** [comment]
How to rotate is now documented here: https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/19279194/How+To+Rotate+Keys#GeoLite-API-key
