### ISSUE TITLE
Review and categorize on-call tickets

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#49]
Review and categorize existing on-call tickets into milestone(s) such that we could prioritize as a team.
- Clarify (through labels, or some means) which tickets are to reduce on-call toil, vs which tickets are just BOM ownership work that had no home.
- Search GitHub issues with on-call label.
- Search JIRA tickets: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16387065/On-Call+Arch-BOM#On-call-Improvements.
- Should we move JIRA tickets that were "prioritized" (i.e. above the line)? Note: if the tickets contain private info, we may need to reference the JIRA ticket.

**Comment by robrap** [comment]
Note: I was hoping to do this while on-call, but did not get to it. Do we want to leave this as a ticket on the board, or move it to backlog and do it during a warm down phase from active work?

**Comment by robrap** [comment]
Note: We may need to ticket looking at the rest of the backlog as well: https://2u-internal.atlassian.net/jira/software/projects/ARCHBOM/boards/612/backlog

**Comment by jristau1984** [comment]
First improvement: Remove the "P2 - On call Routine" priority option

- [ ] Review the content in the "on-call" label, and ensure it is appropriate to leverage
- [ ] Add "on-call" label to all tickets in this status
- [ ] Remove the status from all applicable items
- [ ] Remove the status from the project config

**Comment by jristau1984** [comment]
I was unable to apply the on-call label to 3 of the 20 items.  This is due to 
* one being a PR in devstack repo where that label does not exist.
* one being in the ecommerce-scripts repo where that label does not exist.
* one being in the edx-platform repo where that label does not exist.

**Comment by jristau1984** [comment]
Second improvement: Remove the "On-Call" status option

- [ ]  Add "on-call" label to all tickets in this status (7 items)
- [ ]  Update the " On-call" items on the board to "Prioritized"
- [ ]  Remove the status from all applicable items
- [ ]  Remove the status from the project config

**Comment by jristau1984** [comment]
https://github.com/openedx/edx-platform/issues/32671 is the only remaining on-call item that cannot be labelled.  Given that it is a year old and has had lots of activity on it, I presume this should just have the on-call label dropped?  @robrap any thoughts on how to deal with this lingering item?

**Comment by jristau1984** [comment]
I have transferred about 1/3 of the Jira backlog into Github.  This will continue in my free time until they are all moved and in a status that allows them to be re-reviewed by the team.
