### ISSUE TITLE
Tighten or deny JWTs

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#492]
By design, JWTs are acceptable as long as they live.

There is a ticket concerning:
1. Having the JWTs live for a shorter time, and
2. Adding a capability to deny JWTs that haven't yet expired.

To discuss in more detail, please use private 2U linked ticket instead: https://2u-internal.atlassian.net/browse/ARCHBOM-2172

**Comment by timmc-edx** [comment]
This is a low priority for the team -- we may work on it in the future, but for now we're just going to leave the Jira ticket open for tracking and close this one unless and until we have a specific plan.
