### ISSUE TITLE
Clean up edxapp newrelic config to .ini

### ISSUE THREAD

**Issue by adzuci** [edx/edx-arch-experiments#493]
We'd like to eventually clean-up the following on the configuration repo that has not been forked to edx.
-------------

We would like to look at config in New Relic here https://onenr.io/0BQ1zzbmXwx and add relevant config to https://github.com/openedx/configuration/blob/master/playbooks/roles/edxapp/templates/newrelic.ini.j2

Note this config file is used for both CMS and LMS

Example config:

```
django.http.response:Http404
django.core.exceptions:PermissionDenied
django.db.utils:IntegrityError
lms.djangoapps.courseware.exceptions:CourseAccessRedirect
lms.djangoapps.courseware.exceptions:Redirect
django_ratelimit.exceptions:Ratelimited
rest_framework.exceptions:AuthenticationFailed
rest_framework.exceptions:NotAuthenticated
rest_framework.exceptions:PermissionDenied
rest_framework.exceptions:Throttled
social.exceptions:AuthCanceled
```

**Comment by robrap** [comment]
Instead, this is going to be a clean-up task at some point to delete these files once we are no longer using New Relic.

**Comment by robrap** [comment]
This was completed as part of another ticket.
