### ISSUE TITLE
Auto add arch-bom repo issues to arch-bom project

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#494]
Acceptance Criteria:
- [x] Configure github to have arch-bom owned repo issues auto-added to arch-bom project.

Notes:
- Use ownership spreadsheet to find arch-bom owned repos.
- Follow how-to: https://openedx.atlassian.net/wiki/spaces/AC/pages/3710451733/How+to+have+issues+and+pull+requests+added+to+GitHub+Projects
  - Should be configured same as devstack repo, which has already been completed.

**Comment by timmc-edx** [comment]
Found all 38 repos by downloading TSV file and running: `ack 'edx\tarch-bom' ~/reference/repo-ownership.tsv | sed -e 's/^[^\t]*\thttps:\/\/github\.com\///' -e 's/\t.*//' | sort`

**Comment by timmc-edx** [comment]
I captured GitHub's network calls and replayed them, parametrized, but it turns out we can only have 20 instances of this workflow in the project. :-(

**Comment by timmc-edx** [comment]
We ended up selecting 18 repos -- those marked Medium or High in the ownership spreadsheet, along with edx-lint and edx-arch-experiments -- and I've set the workflows to match that list.
