### ISSUE TITLE
Retrieve Kafka API and Schema Registry keys/secrets from terraform state

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#500]
I recently added a bunch of API keys to Confluent with https://github.com/edx/terraform/pull/6272/files. I need to retrieve the api and key values that were created for 
"confluent_api_key" "schema-api-key-temp" and
"confluent_api_key" "edx_test_runner_dev"
 so I can test and make sure they have all the correct permissions.
Note that in the future you may get these sorts of requests from anyone setting up a new event bus workflow since we want them to configure the API keys via terraform.

**Comment by rgraber** [comment]
This is blocked on SRE response

**Comment by matthugs** [comment]
Sorry for the slow response; we've gotten these for you in Keeper now
