### ISSUE TITLE
Figure out and document the process for dealing with owned-repo PRs (existing and new)

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#502]
Ned has generated a list of open PRs against arch-bom-owned repos here: https://nedbat.github.io/exopublish/exo-people-60.html#team-2u-arch-bom. For each PR, we should categorize it as MERGE, CLOSE, or GROOM. The list of PRs to merge/close should be sent to Ned as there are some intermediate steps required. PRs that require more attention/grooming should be added to the arch-bom board for prioritization and grooming.

**Comment by rgraber** [comment]
Adding PRs to https://docs.google.com/spreadsheets/d/1ko9oQ8ltg7uBpR8GW5nuoVWGGA9WgGJirB6VxSWq5C4/edit#gid=0

**Comment by robrap** [comment]
Marking this as closed. This is outdated, and docs have been updated here: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/edit-v2/16387065#PR-Triage%2FReview. Additionally, it is somewhat replaced by https://github.com/edx/edx-arch-experiments/issues/816.
