### ISSUE TITLE
[Discovery] Get devspace registrar working with a minimalist helm chart

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#507]
A/C

- [ ] We can start registrar using the minimal devspace helm chart
  - [ ] It still needs to use the registrar service *image*, or at least the code, need to figure out how to do that 

As a follow up to https://github.com/edx/edx-arch-experiments/issues/470: While the other ticket focuses on using the existing edx production helm charts, we would like to try to see if we can use this with the minimalist devspace-provided helm chart and see if we can bring up the service that way instead.

During `devspace init`, after selecting 'helm' for deployments, select 'No' when asked about having an existing helm chart. 

Tech note:
We tried to get the devspace helm chart to point to the existing registrar dev image but it only brought up an empty python image. We think this is a configuration problem.

**Comment by jristau1984** [comment]
Closing this specific slice of https://github.com/edx/edx-arch-experiments/issues/471, but keeping https://github.com/edx/edx-arch-experiments/issues/471 open in the backlog for future consideration.
