### ISSUE TITLE
[Abstraction] Move event bus key related code

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#51]
## Background

The `event-bus-kafka` currently contains code that deals with event bus keys and avro, all of which is independent of the Kafka technology choice. Relocating this code to the `openedx-events` repo would enable these helpers to be used by any future technology implementation. 

## Acceptance Criteria:

- [ ] Move event bus key helpers (and tests) from the `event-bus-kafka` to the `openedx-events` repo.

## Notes/Questions

- See https://github.com/openedx/event-bus-kafka/blob/09a0a4e249524fb83bf4782a0ae106b2a4c48a8e/edx_event_bus_kafka/publishing/event_producer.py#L27-L105 for the functions to be moved.
- Refactor/rename code as appropriate for its new home. Should anything move into existing classes or new classes?
- Would `event_bus_key` be more explicit than `event_key` for some naming?

**Comment by robrap** [comment]
@rgraber @timmc-edx: I'm trying to understand what "[Abstraction]" tickets can be closed at this point. I only see extract_event_key (the linked function above) used in event-bus-kafka, and not in redis or openedx-events, according to this search: https://github.com/search?q=org%3Aopenedx+extract_event_key&type=code. Do we know if this functionality was in fact used for Kafka-only, or was it renamed and re-implemented in one of the other two libraries?

**Comment by timmc-edx** [comment]
It looks like the Redis implementation doesn't use or create event keys, so we can probably just close this. If someone makes a new implementation and wants those utilities, we can do a refactor at that time.

**Comment by robrap** [comment]
Thanks @timmc-edx. I don't remember what this is all about, but I agree that this doesn't seem to be needed for an abstraction layer, so I'm going to close this out.
