### ISSUE TITLE
Automatically add new issues in Arbi-BOM-owned repos to Arbi-BOM project

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#512]
As we start to rely more on GitHub Issues and less on Jira, and given the number of repos we own, any new issues opened in any repo we own should automatically be put on the Arbi-BOM project for triage.  Documentation on how to do this lives at https://openedx.atlassian.net/wiki/spaces/AC/pages/3710451733/How+to+have+issues+and+pull+requests+added+to+GitHub+Projects#Project-auto-add .
We should also go through and add any existing issues to our project and triage or delete as necessary.

## Acceptance Criteria

- [x] New issues added to Arbi-BOM-owned repos get automatically added to the Arbi-BOM board backlog
- [ ] Existing issues in Arbi-BOM-owned repos are either closed or added to the Arbi-BOM board backlog, as appropriate

**Comment by jristau1984** [comment]
I added 9 new workflows to the Arbi-BOM project, which will bring new issues for all owned repos into the project.  There are still a large amount of existing issues that are not there (almost 100).
