### ISSUE TITLE
[MOVED] Determine a dependency versioning strategy for event-bus implementations

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#52]
**Issue moved** to https://github.com/openedx/openedx-events/issues/88

----

The `edx_event_bus_kafka` dependency will be specified and pinned in a file _outside_ of each IDA that uses it, since openedx-events will load the implementation by looking up a module reference in the IDA's config. This means that dependency version changes on the library will not be versioned with the IDA (i.e. in the requirements/base.txt files) and we'll need some sort of expand-contract approach to API changes.

For example, we might need to do something like this:

1. Add a new `KafkaProducer` class in event-bus-kafka and delegate the existing `send_to_event_bus` to use it
2. Switch the producer code in Studio to use the new class
3. Delete the `send_to_event_bus` function from event-bus-kafka

## Acceptance Criteria

- [ ] Document how-to for these upgrades in appropriate places.

**Comment by robrap** [comment]
Wondering about ways to handle `make upgrade` with private dependencies. Is there any relation to Cale's proposal to get edx-platform as a versioned dependency? Could we then have another set of private dependencies that rely on this edx-platform version and checks for conflicts and is upgraded separately? No worries if this makes no sense. :)

**Comment by timmc-edx** [comment]
It turns out we have a collection of related dependency-related issues:
- A bunch of our repos will depend on event-bus-kafka but won't be able to declare it directly, and event-bus-kafka has its own dependencies that might cause deploy-time version conflicts.
- We'll have to do expand-contract deploys with event-bus-kafka as a result, and won't have safeguards. Maybe the same for all other deployers, eventually.
- There's a weird sort-of-bidirectional dependency between openedx-events and event-bus-kafka: The second declares a dependency on the first, but the first has an interface dependency on the second.

One thought I had is that we might just want to pack event-bus-kafka _into_ openedx-events as a PEP-508 "extras" package, so we can include `openedx-events[kafka]` in base.in. (And eventually have an extra for each implementation.) Or maybe rewrite the dependency files to add the `[kafka]` part at AMI build time? It doesn't solve all the problems, but it would at least allow the interface to be versioned.

(You could even have a special CI workflow file on IDAs that confirms that none of the various extras' dependencies would conflict with the IDA's compiled requirements files.)

**Comment by timmc-edx** [comment]
Moved to https://github.com/openedx/openedx-events/issues/88
