### ISSUE TITLE
Review Percona's DB optimization recommendations

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#520]
In https://2u-internal.atlassian.net/browse/GSRE-963 (2U-internal issue) there is a PDF draft of recommendations from Percona for optimizing the main LMS/Studio MySQL database defined in edx-platform.  We should review these and determine:

* Roughly how useful each one would be
* Roughly how difficult each one would be
* A rough prioritization of the order in which we'd want to tackle the ones worth pursuing

We have a 34-hour batch of Percona consulting time remaining to ask questions about their recommendations, to be used sometime within the next year (maybe November 2024?).

**Comment by rgraber** [comment]
Blocked on the first maintenance WG meetup

**Comment by timmc-edx** [comment]
Becca's writeup: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/718995676/DB+Optimization

**Comment by timmc-edx** [comment]
Remaining work: Share writeup with Axim so they can make an extract suitable for the community.

**Comment by robrap** [comment]
Have discussed with Dave O., who may be able to look at this in March.

**Comment by jristau1984** [comment]
The findings have been reivewed, but the horus were given to another team inside of 2U that had a pressing need.
