### ISSUE TITLE
SRE Access to Confluent Cloud 

### ISSUE THREAD

**Issue by jdmulloy** [edx/edx-arch-experiments#523]
I am able to login to Confluent via OneLoging, but when I get in I get a page saying I don't have access to any resources in this organization. Please grant me and the rest of the SRE team access to Confluent.

![image](https://github.com/edx/edx-arch-experiments/assets/3395292/6d6b0489-a0b6-4a7d-9ec7-0d17e303047b)

**Comment by matthugs** [comment]
List of users in question:

- aryaboy@2u.com
- atrepca@2u.com
- aali1@2u.com
- cdunda@2u.com
- cmontanaro@2u.com
- cphillips@2u.com
- dboyd@2u.com
- dstreby@2u.com
- fumer@2u.com
- hlotze@2u.com
- sabdi@2u.com
- jmulloy@2u.com
- mfraser@2u.com
- mhughes@2u.com
- mdesmarest@2u.com
- mshahzad@2u.com
- nmoy@2u.com
- sali@2u.com
- sswanepoel@2u.com
- tthompson2@2u.com
- wgroenewald@2u.com

**Comment by matthugs** [comment]
previously commented the full Global SRE group's emails, which can be found internally in [this spreadsheet](https://docs.google.com/spreadsheets/d/1CTeK9Hp08CfxU5M3C9P_hUCIjYNEFd1AFAT1LzHwwuM/edit?usp=sharing)

**Comment by adzuci** [comment]
Note in case it saves time, at least Charles, Trepca, Ryaboy, Matt and I have already been given orgadmin access.  I was planning to pair with Ryaboy to walk through granting the rest of the team access, but think I forgot to file a ticket to do so.  Any help provisioning access is appreciated.

**Comment by rgraber** [comment]
Before I can grant the correct roles anyone who hasn't already done so will need to email helpdesk for OneLogin access.

**Comment by rgraber** [comment]
@Ali-D-Akbar @CMontanaro-11 @the-real-cphillips @dfboyd @HeinrichL93  @farhanumar @ohnickmoy @theonlysinjin @thomty  @wgroenewald  I still don't see your emails in Confluent. Have you gotten access via OneLogin?

**Comment by the-real-cphillips** [comment]
@rgraber wasn't aware I even was granted access.  looks like I see it in OL though.  I do get the same thing as @jdmulloy though, "no resources in organization" message

**Comment by rgraber** [comment]
> @rgraber wasn't aware I even was granted access. looks like I see it in OL though. I do get the same thing as @jdmulloy though, "no resources in organization" message

It's a 2-step process. Now that you have signed in with OneLogin I can grant you the relevant permissions.

**Comment by farhanumar** [comment]
@rgraber I see it in OL and was able to sign in but i have no role assigned, so i cannot see any resources listed in the confluent console. I might need a ticket with support.

**Comment by rgraber** [comment]
Nope, that's me. I'll give you the correct roles

**Comment by rgraber** [comment]
@farhanumar you should be all set
