### ISSUE TITLE
Rotate Confluence docs

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#531]
**Acceptance Criteria:**
- [ ] All Confluence docs arch-bom owns and archives on a quarterly basis should be archived and refreshed for CY2024-Q1
    - [x] Parking lot
    - [x] Retro
    - [x] On-call log
- [x] Create a How We Rotate page in Confluence with the instructions for how to do this in the future
    - https://2u-internal.atlassian.net/wiki/spaces/AT/pages/774176808/How+we+rotate+confluence+pages+BOM

**Notes:**
- Jeremy recommends creating a fresh page as the new active page in order to drop the history from the page, which has slowed it down in the past.
  - This requires creating a new parent page, and moving all the archived pages. I think we could probably create a new Archive parent for each type of doc, so we don't need to move/reorder all the individual docs each time, but just the single Archive parent.
  - This also means updating Calendar invites, bookmarks, subpages, and inbound links.

**Comment by timmc-edx** [comment]
Done, although we won't be doing it this way again in the future.
