### ISSUE TITLE
Get usage list for openedx/configuration

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#540]
A/C:

- [x] Comment on [configuration DEPR](https://github.com/openedx/public-engineering/issues/51#issuecomment-1910568331) with remaining references

We need to respond to: https://github.com/openedx/public-engineering/issues/51#issuecomment-1910568331, and document what we are using in openedx/configuration, or from where.

1. This likely includes a list of services that are not yet in k8s.
2. Are there other uses? How do we find them? (e.g. Diana mentioned Prospectus)

References to look for:

- Repo references: `edx/configuration` or `openedx/configuration`

**Comment by dianakhuang** [comment]
Containerization Project Roadmap: https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/19238579/Django+Containerization+Project+Plan only edx-platform and xqueue remain.

I'll check in on prospectus, but I suspect it is still using some of this workflow.

The other "big" use case is sandboxes, which also uses Ansible.

**Comment by dianakhuang** [comment]
Prospectus does still use configuration. There's a lot of hits here, but I suspect we should go through this search to get an inventory: https://github.com/search?q=repo%3Aedx%2Fedx-internal+edx%2Fconfiguration+OR+openedx%2Fconfiguration&type=code

**Comment by robrap** [comment]
@dianakhuang: Also, what projects might not be in the Containerization Project Roadmap? Insights? Other? We may be able to review app infrastructure in New Relic to determine.

**Comment by dianakhuang** [comment]
Yeah, Insights is definitely not listed on the roadmap. We should try to get a list of what other deployments might still be using configuration. I think our ultimate goal for this DEPR is to get a fork back into the `edx` org and update all our references to the `openedx` version
