### ISSUE TITLE
Figure out how to integrate edx-atlas (new translation system) into our build process

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#548]
Background

AXIM has moved off of having translations merged directly into various repos and into a centralized repo: https://github.com/openedx/openedx-translations We would like to ensure that we still get updated translations.

Acceptance Criteria
- [x] edxapp is now deployed with translations from openedx-translations
- [x] Documentation on how to get translations built for MFEs and other IDAs
- [x] Report out details of the new process

Implementation Details
- The OEP describing the new process: https://docs.openedx.org/projects/openedx-proposals/en/latest/architectural-decisions/oep-0058-arch-translations-management.html
- Description of new command for pulling translations: https://discuss.openedx.org/t/pulling-translations-for-non-tutor-deployments/12365
- Tool for pulling translations: https://github.com/openedx/openedx-atlas 
- I believe for edx-platform and several other MFEs, this is process is already set behind a feature flag and we need to figure out what combination of flags to enable and when.
- Spreadsheet of repos that have translations in `openedx-translations`: https://docs.google.com/spreadsheets/d/1jKZqkdN05O9bmtti5FohG6Y1dGxWAr101HzvOp1rBZo/edit#gid=0 (public file)

**Comment by timmc-edx** [comment]
I think the natural place for pulling translations in edx-platform will be in the Ansible code that is already installing Python requirements. But for that to work, we need i18n_tools to be installed at the base layer: https://github.com/openedx/edx-platform/pull/34285

**Comment by timmc-edx** [comment]
Hopefully this will work for edx-platform: https://github.com/edx/edx-arch-experiments/issues/548

**Comment by timmc-edx** [comment]
I believe the process for IDAs looks like this:

1. Ensure that `openedx-atlas` Python package is included in the base requirements
2. Find a place in your deployment pipeline where the repo code is checked out and Python dependencies have been installed. (This includes private dependencies, if your repo relies on dynamic discovery of translation-requiring dependencies, as is the case for edx-platform.)
3. Add a build step that runs `OPENEDX_ATLAS_PULL=true make pull_translations`. This will overwrite translations in the checked-out code.
