### ISSUE TITLE
Bump global constraint of Django in edx-lint

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#552]
We have a global constraint on Django to keep the version in every repo at 3.2. But as we have upgraded Django to version 4.2 in almost all of the IDAs including the edx-platform we now need to bump that constraint to `Django<5.0`. 

Also, add local constraints into the following IDAs if not already there, since they aren't yet upgraded. 

```[tasklist]
### Repos not yet upgraded
- [x] [edx/sanctions](https://github.com/edx/sanctions) [PR ready for merge]
- [x] [edx/ai-translations](https://github.com/edx/ai-translations) [Django 4.2 upgrade PR in team review]
- [x] [openedx/ecommerce](https://github.com/openedx/ecommerce)
- [x] [edx/subscriptions](https://github.com/edx/subscriptions) [PR merged]
- [x] [edx/commerce-coordinator](https://github.com/edx/commerce-coordinator) [Local constraint already present]
- [x] [edx/edx-exams](https://github.com/edx/edx-exams) [PR ready for review]
```

**Comment by UsamaSadiq** [comment]
Created PRs for the pending repos to add local django constraint so they don't get affected when upgrading the global django constraint.

**Comment by UsamaSadiq** [comment]
Global Django constraint has been updated in the PR https://github.com/openedx/edx-lint/pull/403.

**Comment by jristau1984** [comment]
Since Django 4.2 is complete, this work is done.  Just needs the paperwork to be tidied up.
