### ISSUE TITLE
Process changes for getting updated owners/maintainers in the ownership spreadsheet

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#555]
**Context**

Due to our recent reorganization, and while working with Axim on changes in maintainers, our tracking and documentation are not up to date.

**Acceptance Criteria:**

- [ ] Clear documentation about how ownership is tracked.
- [ ] Update the ownership spreadsheet and/or Ticket(s) as-needed for updating the spreadsheet and/or adding automation.

**Thoughts/Questions:**

- Documentation should cover manual steps required, and could point to tickets for automating any steps.
- There is existing documentation in the ownership spreadsheet README and links to Confluence documents around ownership that should be updated.
- The [squads tab](https://docs.google.com/spreadsheets/d/1qpWfbPYLSaE_deaumWSEZfz91CshWd3v3B7xhOk5M4U/edit#gid=756435872) of the ownership spreadsheet has outdated teams, people contacts, and probably other team-related metadata.
  - We should prioritize fixing [squads used for edx-platform alerting](https://github.com/edx/edx-internal/blob/1f467fffa504ebc88f56cf53b34455650e8fc0c5/edx-remote-config/prod/lms.yml#L474-L497). For example, is anyone getting data-de alerts?
- We need the spreadsheet the address the difference between 2U owner (responder, or whatever we want to call this) and community maintainer.
  - There may be services, MFEs, repos, edx-platform apps, etc. that we don't maintain, but we still deploy to production and need a clear owner who is responsible.
- We need a plan around the various sheets under _Resources_ below.
  - Will we continue to just reference the single legacy ownership spreadsheet, and are the rest of the resources just transitional? Other?
  - Do we need to get catalog-info.yaml owner information into our spreadsheet?
  - Do we need to get edx-platform app ownership information into CODEOWNERS?

**Resources:**

- [2U Ownership Spreadsheet](https://docs.google.com/spreadsheets/d/1qpWfbPYLSaE_deaumWSEZfz91CshWd3v3B7xhOk5M4U/edit#gid=756435872)
- [Axim Repo and Maintenance Spreadsheet](https://docs.google.com/spreadsheets/d/1rMwbRldYwp-xPsAG2vijqwB__9M7P2AgjDxX31G7ucA/edit#gid=0)
  - Column with daily sync to catalog-info.yaml owner (final source of truth)
- [LP Repo/app Ownership Spreadsheet](https://docs.google.com/spreadsheets/d/1LOBZdK9YYtZ6s9E2Am7S_6vEGonYNwA97sjOhjs63Bk/edit#gid=1990273504)

**Comment by robrap** [comment]
Additional Notes:

- The spreadsheet has a new "Repo Maintainer" column, with values of: 2U, Community, and Blank.
  - Is this a permanent or transitional column?
  - What do blanks mean?
  - The README probably needs to be updated.
  - We may want to consider splitting out legacy owner? Or do we want a 2U owner/contact for everything, and do we want 2U teams to start with the internal contact before going to the actual maintainer regarding issues?
- Reminder that we should have one or more communications to share updates and how-to use the updated spreadsheet.

**Comment by jristau1984** [comment]
@robrap -
1. I think it can be a permanent column... I would prefer it moving closer to the left, but I dont want to break automation.
2. Currently, blank entries in the Maintainer column map to repos that are in the @edx org.
3. Probably, I did not check the readme.  I will do that.
4. I think the owner/contact column can eventually become "show the maintainer column value if it is populated, and if not show a hardcoded value"... I want to get the "2U" label in the Maintainer column to be more granular than that first.  Does that make sense?

Updates are lacking, would this just go to the #edx-ownership channel?

**Comment by robrap** [comment]
@jristau1984 
1. I risked breaking automation, and moved it next to the org column. Hopefully people will use named columns. We can make this part of the inform.
2. There are edx org rows with blanks. We may consider using "-" for edx rows, so Blank can mean it doesn't yet contain a value?
3. Thanks.
4. It think the set of columns we ultimately want is in-flux, but this is a good step in the right direction. We may need more discussion on all the different variations of monitoring responder, or internal-contact, or maintainer, etc.

- Communicating in #edx-ownership channel for now sounds great.

**Comment by jristau1984** [comment]
Bullet 2 is done.  Bullet 3 is done.  Communication is done.

**Comment by jristau1984** [comment]
I think this is done, but would love a review if anyone has a few minutes to look over the bullets and see if the updates are sufficient.

**Comment by robrap** [comment]
@jristau1984: Thanks for all the work on this. I think this can be closed. The main outstanding items we might consider ticketing separately are:
1. Do we need to get catalog-info.yaml owner information into our spreadsheet? (Does Axim already have automation for this they can share?) In the short term, maybe we add a link to backstage from the maintainer column notes? Having this in the spreadsheet would make it easier to know if we are actually in-sync with the community version or not.
2. Do we need to get edx-platform app ownership information into CODEOWNERS? (We have de-prioritized this work, and can ticket when and if we wish, so I'd skip this one.)
