### ISSUE TITLE
Clean up GitHub automation for issues that are no longer owned by arch-bom

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#560]
The GitHub automation automatically puts issues onto our board for repos we own. Now that we have shrunk the list of repos we own, we should update the automation to match it.

A/C:

- [x] Repos we don't own are no longer in automation
- [ ] ~~If there's now room for more repos, add the highest priority ones that are missing. (Github imposes a limit on how many we can have.)~~

Notes:

- Original ticket for auto-adding issues to the board: https://github.com/edx/edx-arch-experiments/issues/494

**Comment by robrap** [comment]
https://github.com/openedx/event-routing-backends/issues/423 is an example ticket that we shouldn't need to prioritize, because we don't own this repo any more.

**Comment by robrap** [comment]
[open question] Do we want or not want to watch edx-platform?

**Comment by robrap** [comment]
The project workflows for repos we no longer own have been removed.
