### ISSUE TITLE
Recreate dashboards and alerts in Datadog

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#572]
AC:

- [ ] Highest priority alerts and dashboards are re-created
- [ ] Tickets for recreating remaining alerts and dashboards
- [ ] Documentation written to guide other teams in doing the same

**Comment by robrap** [comment]
I'm closing this ticket. It will be ticketed for arch-bom as needed in https://github.com/edx/edx-arch-experiments/issues/642.
