### ISSUE TITLE
Datadog generic APM in edxapp stage

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#574]
AC:

- [x] LMS and CMS on stage reporting to both NR and DD
- [x] DD receiving at least basic Django traces

Implementation notes:

- If we go with OpenTelemetry:
  - pip install opentelemetry packages including Django contrib
  - Configure for reporting to Datadog via agent (using env vars)
  - Add opentelemetry wrapper
- If we go with ddtrace-run:
  - Add ddtrace-run wrapper
- Either way:
  - Install and configure datadog agent

**Comment by timmc-edx** [comment]
Ansible testing notes:

- sandbox name `timdd`
- Use configuration repo branch `timmc/opentelemetry`
- uncheck most services
- include newrelic

**Comment by robrap** [comment]
@timmc-edx: Before closing this ticket, could you either switch to `env:[prod|stage|prod-edge]` (to get better default functionality from DD, which defaults to prod for each service), or could you ticket this update? Thank you.

**Comment by timmc-edx** [comment]
Sure: https://github.com/edx/edx-internal/pull/10557
