### ISSUE TITLE
Observability Migration epic

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#577]
**UPDATE:** I did add a comment that we might want to create a doc clean-up ticket.

This epic is mostly to provide a list of resources used in planning any migration work.

_Important: All docs should be considered WIP and incomplete at this point._

**Arch-BOM generated docs:**

* [New Relic to Datadog Migration Plan](https://docs.google.com/document/d/1E697h8kYwMspIKr2MOtQLyn1V5YtXT93Sxka-vc9FUY/edit#heading=h.6mrwcuu6mg87)
* [New Relic to Datadog tasks spreadsheet](https://docs.google.com/spreadsheets/d/105gLHkjgm9kD3WA23qRcmhzmsYTfyXrHsQRl-5B5wTs/edit#gid=0)
  * [Arch-BOM migration tasks in Github](https://github.com/orgs/edx/projects/11/views/11?filterQuery=epic%3A%22Migration+to+Datadog%22) (which need cleanup)
* [Datadog questions spreadsheet](https://docs.google.com/spreadsheets/d/1XlkASZOeNNi4jEgbWSKrCzR-pwvb6Hmmh_TaHtHCYuk/edit#gid=0)

**Other documents:**

* _(SRE)_ [Transitioning from New Relic to Datadog confluence doc](https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/861372422/New+Relic+to+Datadog+Migration)
* _(new)_ [Recommendation: Observability Solution](https://docs.google.com/document/d/1pvlnjR-Myo4dbyUP2egKU65FRCozBO5yjzy1NwpN8iA/edit#heading=h.eg5yp9n9s3d3) (includes ATAM link)
* _(New Relic prepared)_ [Datadog to New Relic Migration Plan](https://docs.google.com/document/d/1L5tsde7UsORQPIJWgYeu91iKtDRsM6pF/edit#heading=h.gjdgxs)

**Comment by robrap** [comment]
I moved this to the Future epic. I don't know that we need epic tasks any more. However, we might want a task for cleaning up the old SRE docs.

**Comment by jristau1984** [comment]
I have checked that all of the linked docs above are accurate (maybe not fully up to date, but accurate enough IMO) and all useful content is linked from wiki pages that have been considered source material for the org.  I will update the epic description to point to this wiki: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/997884079/Migrate+from+Newrelic+to+Datadog

I will consider this the final act needed to consicer this "epic ticket" complete.  @robrap any objections here?
