### ISSUE TITLE
Run pull_translations in Devstack images

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#579]
New devstack builds are getting a blank login page until the dev runs `make pull_translations` in lms-shell.

**Comment by mfarhan943** [comment]
I pulled the latest image and tested it locally, and I didn’t encounter any issues with the login page.

**Comment by mfarhan943** [comment]
@timmc-edx , could you please close this issue? We couldn't reproduce the problem locally.
