### ISSUE TITLE
Configure app-permissions repo to handle updated compliance needs

### ISSUE THREAD

**Issue by jristau1984** [edx/edx-arch-experiments#582]
We need to implement the new requirements below.

![Image](https://github.com/edx/edx-arch-experiments/assets/11785886/90815d00-a9ab-41ee-be2b-aff5750fc860)

This includes (but may not be limited to):
- Generating some policy documentation regarding the use cases for changing app-permissions.  Some will need to be for BOM team and some will need to be for Helpdesk/IT.
- Updating engineering related docs, and communicating out this change.
- Updating the app-permissions repo settings to enforce the new requirements
- Creating a plan and follow up item for performing an audit of the content in Q2.

**Comment by robrap** [comment]
@jristau1984: We'd like to move this to the backlog, but not sure if it will get lost there.

**Comment by jristau1984** [comment]
Can we ask IT/Helpdesk to reorganize the permissions files to make this less of a manual filtering exercise?

**Comment by jristau1984** [comment]
This is no longer a priority after Chapter 11.
