### ISSUE TITLE
[DEPR-2U] [Discovery] How do we build devstack images post devstack-deprecation?

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#587]
Original DEPR:

- https://github.com/openedx/public-engineering/issues/263

I believe devstack images are built in the repositories themselves as a GitHub action. Part of this deprecation will be to remove those actions. We will probably want to build these images in the devstack repo if that's the case.

Acceptance Criteria
- alternative plan to build images through devstack repo's GitHub actions
- move edx-platform to using it

Implementation Notes
- verify that we actually know how these images are getting built
- find out if these images are used as the base for the production images used for k8s deploys

**Comment by robrap** [comment]
@dianakhuang: Another that needs a due date.

**Comment by UsamaSadiq** [comment]
Created the [discovery document](https://2u-internal.atlassian.net/wiki/spaces/AT/pages/1263829106/Discovery+Handling+devstack+images+post+devstack-deprecation)[2U-internal only] after analyzing the required changes and potential solutions by having a discussion with SRE team.

**Comment by UsamaSadiq** [comment]
Marking this discovery issue as completed since we've investigated and finalized the approach to handle the Dockerfiles currently present in the IDAs. PR for each IDA will be created and linked with this issue only for tracking purposes.
