### ISSUE TITLE
Finish Open edX Core Google Groups

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#59]
The following four groups now exist, and @jmbowman should be the owner.
- edx_fed-bom@2u.com 
- fed-bom@edx.org 
- edx_platform-qa@2u.com 
- platform-qa@edx.org

Acceptance Criteria:
- [x] Update the lists with the team members. (Note: one team group can point to the other like the arch-bom groups.)
- [x] Inform teams of the new google group(s).

**Comment by jmbowman** [comment]
Everybody finally got their 2U emails sorted out, so I've finished updating the list membership.
