### ISSUE TITLE
[Synthetics] Prepare for synthetics migration

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#599]
**Notes**

- [ ] Migrate an example of each test type, and create helper doc during the migration.
- [ ] Broken Link tests (in NR) might just be for website team. We don't know how those will be implemented.
- [x] Create a dump of tests from NR to track the migration, and to capture details of tests that are disabled, for historical purposes.
- [ ] In the [NR Synthetics UI](https://onenr.io/0BQ15lDaMQx) (enabled tests only), I see:
  - Step Monitor
  - Broken Links
    - Austin said maybe there is a way to handle this in DD??? (https://twou.slack.com/archives/C06QEAJHLC9/p1715258766233479)
  -[ ] Although these tests are enabled, who are the owners and are they actively being used? Does that matter for what we choose? Identify the owner and necessity of each synthetic test.
- [ ] DD FAQ: What counts as an API test run? HTTP, SSL, DNS, TCP, and ICMP all fall under API test billing. Each hit being made on your endpoint counts as a single test run. If a test is set to run from 3 locations every minute, the test will count as 180 test runs in an hour.
- [ ] Ping checks were free in New Relic. Is there a free alternative, or will these now be paid-for synthetics?
  - Austin from DD supplied this [ping check doc](https://docs.datadoghq.com/integrations/ping/). I don't think this gets us the same thing. Austin also said there might be a way to use a free DD monitor, but how?

**Comment by robrap** [comment]
@robrap: Reminder to clean this up.

**Comment by robrap** [comment]
@jristau1984: When you return, you can take over this ticket and update it as you see fit.

**Comment by jristau1984** [comment]
Do we have a CloudWatch option for broken link testing? https://aws.amazon.com/blogs/mt/cloudwatch-synthetics-to-find-broken-links-on-your-website/

**Comment by robrap** [comment]
@jristau1984: Is this ticket up-to-date? I am moving it to in-progress, but you can move it elsewhere or break it up as-needed. Thanks.

**Comment by jristau1984** [comment]
This ticket is up to date, as of when I handed this workstream over to Simon.  I have made no additional progress since then.

**Comment by robrap** [comment]
Should this ticket be assigned to @schenedx instead? Also, @schenedx, maybe you can include Synthetics progress updates in your stand-up updates?

**Comment by jristau1984** [comment]
> [Drafted plan] Synthetic migrations:
Although we have ~50 synthetic tests within Newrelic, only 6 are with alert conditions, which means they will alert certain groups or people when the tests fail.
Within the 6 synthetics, there are only 4 enabled tests within newrelic, 3 are for SRE technology, 1 for Enterprise.
I think I want to help migrate the 3 SRE technology. I'd love to have someone in Enterprise to migrate the admin plotly synthetic test. 
For rest of it, we will abandon and they can get rebuild from scratch in Datadog.

**Comment by timmc-edx** [comment]
Closing because this ticket would only be useful for tracking parts that Arch-BOM owns (and we're all set on synthetics).
