### ISSUE TITLE
[Consumer] [Infra] Make sure discovery event consumer can get information from ecommerce

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#60]
When an event updates the end date of a course run, the event consumer loop breaks because it is trying to talk to ecommerce: 
`https://github.com/openedx/openedx-events/blob/508fa14622baab416882aa170a1df092c2db39c5/openedx_events/content_authoring/data.py#L37`

We need to configure the consumer to talk to ecommerce, or figure out another way around this. I don't think we can just use RCM for backup because we only ping ecommerce if the end date has changed, so if an event updates the end date but doesn't update ecommerce, RCM will not realize the end date has changed.

**Comment by robrap** [comment]
This is an interesting scenario. In the short-term, the simplest solution may be a celery task to make the call to ecommerce. Longer term, should ecommerce just be publishing price changes? But that might be complex, and requires rigor for SOX compliance. We can discuss further.

**Comment by robrap** [comment]
Becca did this and tested it.
