### ISSUE TITLE
[bug] Figure out what happened to the credentials service last Friday

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#606]
We saw an outage on credentials on Friday, April 19. Turning off DD support on credentials caused a recovery, but we're not sure DD was the cause of the issue. We want to understand what bad interaction with DD caused the outage.

Acceptance Criteria
- create an RCA page to track the timeline of what happened
- if at all possible find the cause so we can understand what happened.

**Comment by dianakhuang** [comment]
RCA page: https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/989364447/RCA+Credentials+Service+went+down

**Comment by robrap** [comment]
The ticket https://help.datadoghq.com/hc/en-us/requests/1661715 includes two issues at this time:
1. A DD trace log message found across services, and
2. Resolving why the Credentials service fell over, which we now think might be independent of the log messages noted in point 1.

**Comment by timmc-edx** [comment]
Ticket for the traceparent errors: https://github.com/edx/edx-arch-experiments/issues/607

**Comment by dianakhuang** [comment]
We managed to bring down stage credentials by triggering a large regrade, so we think something about a celery job making calls to credentials with datadog enabled causes credentials to crash and not recover. I suspect it's basically acting as a DOS attack on credentials.

**Comment by dianakhuang** [comment]
We tested this again with New Relic disabled, and the credentials service remained up. It seems like this is another bad interaction between New Relic and DataDog when run at the same time.

**Comment by dianakhuang** [comment]
There's a possibility that there's also a weird interaction between Datadog and New Relic on in the celery workers on the LMS and the credentials service, but we didn't do any experiments on this and I'm leaving this info to aperture to figure out in their migration plan for credentials.
