### ISSUE TITLE
Intermittent "invalid w3c traceparent" error logs from Datadog

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#607]
We're seeing bursts of errors like this in some servers, such as this in the discovery logs:

```
2024-04-22 15:49:05,172 ERROR 45 [ddtrace.propagation.http] http.py:787 - received invalid w3c traceparent: 00-662686f0000000002a48942471524dcd-79bb7e96771c8fd1-01,00-f445bcafd82f1f4160b24362df2c6eaa-ddf4f949c0b28f34-01
Traceback (most recent call last):
  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/ddtrace/propagation/http.py", line 785, in _extract
    trace_id, span_id, trace_flag = _TraceContext._get_traceparent_values(tp)
  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/ddtrace/propagation/http.py", line 664, in _get_traceparent_values
    raise ValueError("Invalid traceparent version: %s" % tp)
ValueError: Invalid traceparent version: 00-662686f0000000002a48942471524dcd-79bb7e96771c8fd1-01,00-f445bcafd82f1f4160b24362df2c6eaa-ddf4f949c0b28f34-01
```

https://github.com/DataDog/dd-trace-py/issues/6831 is possibly related, but might be a different cause with the same symptom.

Private ticket with DD: https://help.datadoghq.com/hc/en-us/requests/1661715

**Comment by timmc-edx** [comment]
Drilling into one instance on `container:subscriptions`, host `i-01dccbf58d892a9ef`, I find two identical error traces 1 ms apart, both apparently triggered by the same request: `[2024-04-23 20:41:59 +0000] [132] [INFO] GET /api/v1/stripe-subscription/`. No other HTTP traffic occurred in the 3 seconds beforehand, and if I exclude /health calls, then nothing happened in the 50 seconds beforehand. (Before that was another call to `/api/v1/stripe-subscription/`, apparently triggering _tens_ of instances of this error.)

The focal instance can be identified as belonging to trace_id 66281d15000000002ea67b8ad437b563, originating in an LMS page view or API call. The span making the call to subscriptions was `lms.djangoapps.learner_dashboard.program_views.program_listing`. Inferred source locations: [view](
https://github.com/openedx/edx-platform/blob/bf19fe237c5a54b8e75c0c58dda2588dffc0cdcc/lms/djangoapps/learner_dashboard/program_views.py#L24), [API call](https://github.com/openedx/edx-platform/blob/bf19fe237c5a54b8e75c0c58dda2588dffc0cdcc/openedx/core/djangoapps/programs/utils.py#L1094).

**Comment by timmc-edx** [comment]
I was able to reproduce the error on Edge by logging in to LMS via email and password (not my 2U SSO account), then going to CMS and logging in via LMS.

More debugging info:

- To navigate from a log message to a trace: In the error message `Invalid traceparent version: 00-662686f0000000002a48942471524dcd-79bb7e96771c8fd1` the first nontrivial run of hexadecimal is the trace ID. It can be looked up by `trace_id:662686f0000000002a48942471524dcd` or directly entered into a URL like <https://app.datadoghq.com/apm/trace/662686f0000000002a48942471524dcd>.
- Filtering the span list by `/` helps exclude all of the middleware and DB calls so you can see which HTTP requests were involved in the distributed trace.

**Comment by timmc-edx** [comment]
:heavy_check_mark: With New Relic APM disabled in Edge edxapp, a DD log tail for `"invalid w3c traceparent" env:prod-edge` no longer shows any hits when I perform a CMS SSO login. So it does appear to be an interference issue.

**Comment by robrap** [comment]
We think this is due to NR, and we'll reopen if we are wrong.
