### ISSUE TITLE
Disable DD APM on prod after POV data collection

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#608]
Now that we've collected host and span count data, we want to disable DD APM in prod (not stage or edge) until such time as we want to migrate. (Double-instrumentation hurts performance.)

A/C:

- [x] Disable DD APM (not infra) in prod k8s & ec2: https://github.com/edx/edx-internal/pull/10683
- [ ] Ensure all the prod deploys go out
- [ ] Update spreadsheet with current stage, prod, edge status

**Comment by robrap** [comment]
This has been communicated to owning teams, and owning teams may-or-may not deploy.
