### ISSUE TITLE
Get xqueue running on Python 3.12

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#613]
XQueue has been updated for Python 3.12. https://github.com/openedx/xqueue/pull/932

I believe this means we need to do two things:
- get edx.org build pipelines running 3.12 for xqueue
- get devstack running xqueue on 3.12

**Comment by robrap** [comment]
@dianakhuang: Why is this an arch-bom ticket and not an Aurora ticket?

**Comment by dianakhuang** [comment]
I think it was because it was outcome of a DEPR conversation, but I think you're right that this should go to Aurora.

**Comment by jristau1984** [comment]
Let's just move the reported issue to AU jira project and close this issue.  Thanks in advance, @dianakhuang !

**Comment by dianakhuang** [comment]
Created https://2u-internal.atlassian.net/browse/AU-2148
