### ISSUE TITLE
[APM][Spans] Discovery on tuning and using APM spans in Django

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#614]
In New Relic it is very simple to get counts for various types of requests using NRQL. This ticket is about understanding how to get the same type of information from DD. This ticket is for learning (and teaching) how to configure and use DD appropriately.

Acceptance Criteria:
- [ ] Determine how and if we can use DD to solve similar APM use cases we've solved in NR.
- [ ] Document findings. Ultimately in Confluence, but can just be on this ticket to start.
- [ ] Either adjust and document span retention appropriately, or task follow-up for that tuning.

Questions/Thoughts:
- Through the APM Trace Explorer, next to the search bar, we can search for Service Entry Spans or All Spans. 
  - We are configured to index 100% of Service Entry Spans. 
  - We will **not** be able to index 100% of All Spans due to cost.
  - [Example DD traces for all Edge Service Entry spans](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aprod-edge%20&agg_m=count&agg_m_source=base&agg_q=%40http.path_group&agg_q_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=true&historicalData=true&messageDisplay=inline&query_translation_version=v0&sort=desc&spanType=service-entry&top_n=1000&top_o=top&traceQuery=&view=spans&viz=toplist&x_missing=true&start=1714486146624&end=1714487046624&paused=false) 
    - May want to try `service:edxapp-lms`. In addition to HTTP Path Group, there may be other attributes that help us.
  - Reviewing "Live - Past 15 minutes" should provide all ingested spans, and not just those we've configured for index, but that needs to be confirmed. 
    - If we can see the right data in the Live view, but not in the other non-live calendar views, we may be able to tune indexing appropriately.
  - Review DD docs + probably requires direct help from DD.
- [Example NRQL query for Service Edge LMS requests for comparison](https://onenr.io/0qwLM51VzR5)
- Is it possible that double instrumentation (NR+DD) messes with DD's ability to collect spans appropriately.
  - Do we see data in DD that better matches what we see in NR (in-general) during the time we dropped NR from Edge LMS (when we look at `service:exapp-lms` spans). 
  - See Tim's Edge ticket for specific times.

**Comment by robrap** [comment]
- Here is a [Slack thread in the DD channel ](https://twou.slack.com/archives/C06QEAJHLC9/p1714498565282719?thread_ts=1714414114.047459&cid=C06QEAJHLC9) related to this topic.

The following is from Slack in a private thread:
> I'm adding the following thoughts for you if and when they are useful:
> - According to DD UI, a Service Entry span is equivalent to a request.
> - The service we are comparing is the edX LMS in Edge: service:edxapp-lms env:prod-edge.
> - The request count in DD (Service Entry spans)  and NR (Transactions) for /event requests and /api/notifications/count/ are <FILL IN FROM SCREENSHOTS>.
> - We are currently indexing 100% of the Service Entry spans. We are excluding heartbeat only.

The Slack thread discussed creating a DD support ticket. We should add a link once that exists.

@dianakhuang:
1. Can you please create the support ticket?
2. Can we do a Stage experiment to prove whether NR+DD seems to be affecting the spans? We could do an experiment as I described in the thread: a) manually hit some request a number of times and ensure we can see it in both NR and DD. Presumably, we should see it less in DD (if at all), but we should choose a path we can see in DD in Edge. b) We can disable NR in Stage and retest manually to see if the spans start appearing and the count matches the number of requests we manually make. We could even use curl in a loop to make 100 requests, or something of that nature.
3. Can you update the AC in prep for grooming, unless you want to just do that together?

**Comment by robrap** [comment]
@dianakhuang: As mentioned above, I moved this ticket into in-progress, but it still isn't groomed and we should do that. Can you remind us in an arch-bom stand-up? Additionally, this ticket should result in documentation and span index (retention) tuning, which may happen as part of this ticket or as a follow-up. 

I am also adding a copy of the Slack discussion:

Robert Raposa
  [1 hour ago](https://twou.slack.com/archives/C06QEAJHLC9/p1714578059187489?thread_ts=1714414114.047459&cid=C06QEAJHLC9)
Two updates:
I noticed that the Service Catalog defaults to operation:django.request. That may be a useful tag for your ongoing work.
[@tmccormack](https://twou.slack.com/team/U02MBR5UUNR)
 opened a separate DD support ticket (I don't have the link) about how DD might improve Django tracing. This may be related in general, or may help with additional more exceptional cases. The cases should certainly be cross-linked.
FYI: 
[@dhuang](https://twou.slack.com/team/U02MBR2UE9K)

Tim McCormack
  [1 hour ago](https://twou.slack.com/archives/C06QEAJHLC9/p1714578195599249?thread_ts=1714414114.047459&cid=C06QEAJHLC9)
http://help.datadoghq.com/hc/requests/1671117 is more about extracting information from ddtrace-py from Python code than about tracing overall, although yeah, there may be some relationship.

Robert Raposa
  [1 hour ago](https://twou.slack.com/archives/C06QEAJHLC9/p1714578369944419?thread_ts=1714414114.047459&cid=C06QEAJHLC9)
Also, 
[@dhuang](https://twou.slack.com/team/U02MBR2UE9K)
, can you see if the counts for the Resources on the [Service Catalog page for Edge LMS](https://app.datadoghq.com/apm/services/edxapp-lms/operations/django.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=prod-edge&fromUser=false&groupMapByOperation=null&isInferred=false&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap50%29%2CtopN%3A%215%29%2Cversion%3A%211%29&s3BucketDetails=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&view=spans&start=1714574591977&end=1714578191977&paused=false) seem more accurate than the spans? Also, we need to understand from DD if this data is driven from spans, or if DD is also creating separate metrics that drive this page. Thank you.

Robert Raposa
  [1 hour ago](https://twou.slack.com/archives/C06QEAJHLC9/p1714579004467769?thread_ts=1714414114.047459&cid=C06QEAJHLC9)
Additional thoughts (and then I'm moving on):
If you use the Service Catalog to get to traces, it searches "All Spans" with the following search: `env:prod-edge operation_name:django.request service:edxapp-lms`.
It may be that rather than relying on "Service Entry spans" for the retention rule, we need a rule to pull in 100% of "All Spans" for operation_name:django.request. It may be that for whatever reason, the DD instrumentation is not yet? coded to allow these to be Service Entry spans, even though in theory they are the requests.

Robert Raposa
  [33 minutes ago](https://twou.slack.com/archives/C06QEAJHLC9/p1714580683704359?thread_ts=1714414114.047459&cid=C06QEAJHLC9)
I was considering tuning our span retention rules, but I wanted to create one to first exclude health-checks/heartbeats, but I couldn't get an appropriate search working. Here is a [search attempt in DD](https://app.datadoghq.com/apm/traces?query=aws_account_name%3A_edx%2A%20%28-%40http.path_group%3A%22%2Fheartbeat%22%20OR%20-%40http.path_group%3A%22%2Fheartbeat%2F%22%20OR%20-%40http.path_group%3A%22%2Fhealth%22%20OR%20-%40http.path_group%3A%22%2Fhealth%2F%22%20OR%20-%40http.path_group%3A%22%2Fhealth%2F%24%22%29%20%28%40http.path_group%3A%2Aheartbeat%2A%20OR%20%40http.path_group%3A%2Ahealth%2A%29&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2C%40_span.count%2C%40_duration.by_service%2C%40http.path_group&fromUser=true&graphType=flamegraph&historicalData=true&query_translation_version=v0&refresh_mode=sliding&shouldShowLegend=true&sort=time&spanType=all&traceQuery=&view=spans&from_ts=1714574957911&start=1714579458032&end=1714580358032&to_ts=1714578557911&live=true&paused=true), but it is still showing results that I think should be filtered out. This is using the following search (in All Spans):
```
aws_account_name:_edx* (-@http.path_group:"/heartbeat" OR -@http.path_group:"/heartbeat/" OR -@http.path_group:"/health" OR -@http.path_group:"/health/" OR -@http.path_group:"/health/$") (@http.path_group:*heartbeat* OR @http.path_group:*health*) 
```

Robert Raposa
  [27 minutes ago](https://twou.slack.com/archives/C06QEAJHLC9/p1714581041521989?thread_ts=1714414114.047459&cid=C06QEAJHLC9)
[@dhuang](https://twou.slack.com/team/U02MBR2UE9K)
: Some other operations I found that might affect our final retention rules:
```
django.request rack.request sinatra.request 
```

**Comment by dianakhuang** [comment]
Looking into the [Service Catalog page](https://app.datadoghq.com/apm/services/edxapp-lms/operations/django.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=prod-edge&fromUser=false&groupMapByOperation=null&isInferred=false&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap50%29%2CtopN%3A%215%29%2Cversion%3A%211%29&s3BucketDetails=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&view=spans&start=1714574591977&end=1714578191977&paused=false) seems to result in similar (but not identical) results over a one hour time span.



![Image](https://github.com/edx/edx-arch-experiments/assets/2952947/4b2d6431-edaa-484d-9d4d-b6c342058864)
![Image](https://github.com/edx/edx-arch-experiments/assets/2952947/be561d4f-d661-4db2-b65a-a692e9844f60)

**Comment by robrap** [comment]
We've made some progress related to this through Office Hours, etc.
