### ISSUE TITLE
[APM] Remove direct references to newrelic

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#621]
We have some code in edx-platform (and possibly elsewhere) that directly imports and uses `newrelic` rather than going through edx-django-utils (e.g. [in StaticContentServer](https://github.com/openedx/edx-platform/blob/98dd95122534b6c118d912cf569c6c9e2e60ab25/openedx/core/djangoapps/contentserver/middleware.py#L102)). These all need to be switched over to edx-django-utils.

A/C:

- [x] Remaining `newrelic` references in codebase identified
- [x] References replaced with edx_django_utils calls or ticketed for dealing with later

Worklist:

- [x] `newrelic` refs in edxapp: https://github.com/openedx/edx-platform/pull/34781
- [x] Inform owning teams about other instances of `import.*newrelic` or `newrelic.*import`:
  - [x] openedx/ecommerce -- purchase
  - [x] openedx/edx-ace -- infinity
  - [x] openedx/xqueue -- aurora
  - [x] openedx/edx-notes-api -- aurora
  - [x] openedx/course-discovery -- phoenix
  - [x] edx/edx-analytics-dashboard -- cosmonauts
- [x] Determine what to do with edx_django_utils features that only support NR
  - For example: https://github.com/openedx/edx-platform/blob/d3ffb3e88270ee6ac8a7b45eeff9d5aec4a5726d/lms/djangoapps/courseware/block_render.py#L941
  - Filed https://github.com/openedx/edx-django-utils/issues/419 to cover this.

**Comment by robrap** [comment]
Maybe most of this should be about informing maintainers?

**Comment by timmc-edx** [comment]
Yeah. I've gone ahead and just notified each team; they can migrate on their own schedule. I think the only thing left is this `set_monitoring_transaction_name` issue and I'm inclined to suggest that the owning team of the relying code should plan to set a new span tag and use that instead in their new dashboards and alerts (and we can deprecate that from e-d-u.)

**Comment by robrap** [comment]
> I think the only thing left is this `set_monitoring_transaction_name` issue ...

Could we just document that as not being available for certain backends, in addition to your intended communications?

**Comment by timmc-edx** [comment]
It's already documented: https://github.com/openedx/edx-django-utils/tree/master/edx_django_utils/monitoring#choice-of-monitoring-tools

I haven't gone through and checked if other such newrelic-specific functions are used in the codebase, though.

**Comment by timmc-edx** [comment]
Filed https://github.com/openedx/edx-django-utils/issues/419 to cover the remaining NR-specific functions.
