### ISSUE TITLE
Clone configuration repository into the edx organization

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#622]
As the configuration repository will be deprecated and archived in the openedx organization, but we're still using it for our deployments, we want to clone the repository for edx.org/2U use cases. The deprecation and archival is scheduled to happen on May 9. See the DEPR ticket for more information: https://github.com/openedx/public-engineering/issues/51

Acceptance Criteria
- [x] configuration repo exists in the edx org
- [x] all deployments/usages point to the edx org version
- [x] this migration has been communicated out to the 2U open edx developers

Implementation Details
- Follow the runbook: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/958595796/Forking+repos+back+into+edx+GitHub+org
- Verify that this doesn't affect devstack

**Comment by robrap** [comment]
Yay!
