### ISSUE TITLE
[Alerts] Determine how to implement baseline/threshold based alerts in DD

### ISSUE THREAD

**Issue by alangsto** [edx/edx-arch-experiments#624]
In New Relic, alert conditions can be configured to alert based on a dynamic baseline: https://newrelic.com/blog/nerdlog/nrql-baseline-alerts-ga. 

Does Datadog have an equivalent?

**Comment by robrap** [comment]
@alangsto: It seems you and others are all making alerts with or without this ticket at this point, so should we just close it?

**Comment by alangsto** [comment]
Yes, I believe we can close this.
