### ISSUE TITLE
[Alerts] Mark which alert policies and dashboards are related to edx-platform

### ISSUE THREAD

**Issue by alangsto** [edx/edx-arch-experiments#626]
Datadog and New Relic can not both be enabled for edx-platform for a long period of time. Because of this, we would like to ensure that all alerts and dashboards for monitoring edx-platform have been migrated to Datadog so that the New Relic to Datadog cutover can be performed quickly. 

AC: 

- Add a new field to https://docs.google.com/spreadsheets/d/1sh9eE-vT5JysI4BAx_qlkhzZ0hEujM_B18qL4XQoq1k/edit#gid=2006183003 to denote whether or not the alert policy is for edx-platform.
- Add a similar column to the dashboard migration sheet.

**Comment by robrap** [comment]
Additional notes:
- Using the search script to search for "edx-edxapp" should find many alerts and dashboards.
- The search script could be used to find the app id and entity guid for each of these apps, but this may turn up less.
  - Using https://onenr.io/0Bj3xXyJbQX, you can click the `...` to get the metadata for each app (Prod/Stage/Edge x LMS/CMS x Workers).
    - The App id and Entity GUID could be used.
 - The [APM Conditions sheet](https://docs.google.com/spreadsheets/d/14pSgimMnnrpvKdag0JFvlfkj9Y_HVO8atDaBdpor_c4/edit#gid=1435682896) uses the app id, and is more likely to turn up matches than NRQL.

**Comment by robrap** [comment]
Note: We think that we may need to disable NR disable LMS, CMS and Edxapp-Workers. So we should include other entity and app ids as well.

**Comment by robrap** [comment]
Please supply the final search that was used on this ticket. It should contain all the ids, etc. that we matched against.

**Comment by alangsto** [comment]
This is the search I ran: `python3 edx_django_utils/monitoring/scripts/new_relic_search.py --regex ".*edx-edxapp.*"`

**Comment by robrap** [comment]
@iamsobanjaved: Can this be closed? Also, can you copy your related Slack comments to this ticket? Thank you.

**Comment by jristau1984** [comment]
Here is the thread about this work: https://twou.slack.com/archives/C04B987KHK5/p1716299825839489

Relevant comments for posterity:

> Muhammad Soban Javed
  9 days ago
This is the gist that has the results of this regex, this includes app ids, entity guids, and edxapp keyword
'.*(ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDMzNDMzMjc|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDM2NjM1ODM|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDM0MTU2ODc|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDY5MTM3NDUzOA|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDY5MTM3NDU3Mw|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDMzNDU0Mjc|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDY5MTM3NDQ4NA|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDY5MTM3NDQ5Mg|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDMzOTY0OTk2|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDMyODI1OTU|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDY5MTMxMTAyNw|ODgxNzh8QVBNfEFQUExJQ0FUSU9OfDY5MTMxMTA0Mw|3343327|3663583|3415687|691374538|691374573|3345427|691374484|691374492|33964996|3282595|691311027|691311043|edxapp).*'
https://gist.github.com/iamsobanjaved/f8c88db8409085f20624580853e6d9f4 (edited) 
Updated the gist, and also included code_owner keyword in the regex, it found 2 more policies and 6 more dashboards
Updated the spreadsheet as pert the search script results.
