### ISSUE TITLE
[Alerts] Create Datadog alert for edx-platform edge to learn about alerting

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#628]
A/C:

- [x] One edxapp Edge alert policy migrated from NR to DD
  - Include both performance and error related conditions—[prod-edge-edxapp-lms-arch-bom](https://onenr.io/0Zw01bObERv) covers this.
  - May not need to transfer everything over—some conditions are duplicates or have been disabled.
- [x] New alert is informed by DD best practices
- [x] How-to documentation created or updated for alert migration
- [ ] Team alerts runbook updated
  - Moved this work to https://github.com/edx/edx-arch-experiments/issues/662

We'll use Edge because it has DD enabled already and actually has traffic.

----

# Created monitors

## Error rate

- https://app.datadoghq.com/monitors/144647801
  - Error burst, same params as in New Relic
  - Multi-monitor across all environments, but `env:stg` is downgraded to a P2
- https://app.datadoghq.com/monitors/145005984
  - Same as above, but for sustained lower rate

## Apdex

Datadog doesn't have to a way to break out apdex by custom span tags, so I reimplemented the [apdex formula](https://docs.datadoghq.com/tracing/guide/configure_an_apdex_for_your_traces_with_datadog_apm/) in Trace Analytics.

Given a base filter `env:(prod OR edge) service:edx-edxapp-lms operation_name:django.request @code_owner_squad:arch-bom` (over service entry spans) we can define three queries:

- a: `<BASE> -@http.status_code:5* @duration:[0ms TO 400ms]`
- b: `<BASE> -@http.status_code:5* @duration:[401ms TO 1600ms]`
- c: `<BASE>`

And then alert on `(a + b/2) / c < 0.8` over 15 minutes: https://app.datadoghq.com/monitors/145167039 Here I've chosen 400 ms as the apdex T value; we're using 2 seconds in New Relic but that's way too high. I set 0.85 as the recovery threshold to add some hysteresis.

**Comment by robrap** [comment]
@timmc-edx: I started a [Slack thread](https://twou.slack.com/archives/C06QEAJHLC9/p1715108741613439) with DD about getting a best practice doc. Also, it looks like @alangsto started some [how-to docs on monitors here](https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/1008500757/How+to+migrate+from+New+Relic+to+Datadog#Create-Monitor-in-Datadog).

@alangsto: [inform] Tim is working on arch-bom alerts in this ticket.

**Comment by robrap** [comment]
@timmc-edx: I'm wondering if these supporting runbooks have dashboards, and if it would be useful migrate those dashboards as part of this ticket, or if we should spin off a separate ticket for dashboards. Let me know your thoughts. Thanks.

**Comment by timmc-edx** [comment]
I think we should ticket dashboards separately.

**Comment by timmc-edx** [comment]
Notes:

These conditions are currently enabled in the NR policy; the disabled ones are "baseline" error rate alerts that we replaced with static threshold alerts:

- BOM Edge LMS APM Apdex Burst
- BOM Edge LMS APM Apdex Sustained
- BOM Edge LMS APM Error Burst (1% over 10 min)
- BOM Edge LMS APM Error Sustained (0.1% over 60 min)
- BOM Edge LMS Workers High Error Rate

**Comment by timmc-edx** [comment]
I was using `@http.status_code:5*` for the error monitors but have switched to `status:error` to make it more general. However, this are almost identical, as `status:error` is only being evaluated on the service entry span, and when an error bubbles up that far, we produce a 500. (There are a handful of traces that have `status:error` and no response code but these are probably just incomplete traces.)

**Comment by robrap** [comment]
What is an incomplete trace, and is it the result of a bug? Can we ask DD about this, possibly in a support ticket?

**Comment by timmc-edx** [comment]
I can make a note to look into it further.
