### ISSUE TITLE
[DD] Create a RUM app for each frontend, and migrate them to DD for teams

### ISSUE THREAD

**Issue by jristau1984** [edx/edx-arch-experiments#636]
Please create a RUM app in DataDog for each MFE that needs to be moved, as documented in this sheet: https://docs.google.com/spreadsheets/d/1sh9eE-vT5JysI4BAx_qlkhzZ0hEujM_B18qL4XQoq1k/edit#gid=217925403

- Please update the list in the sheet if the data is not completely accurate!

**Comment by abdullahwaheed** [comment]
@jristau1984 should we open edx-internal PRs for each frontend repo as well alongside creating RUM applications? Owning teams can then review and merge those PRs whenever they want. It would help speed up the transition from NR to DD

**Comment by jristau1984** [comment]
I think Arbi-BOM should complete all Arbi-BOM owned tasks before doing any more work for other teams. 

Stack rank:
* Do the work needed to be done for things owned by Arbi-BOM
* Do the nice to have wokr for other teams that are lingering in their ownership

**Comment by jristau1984** [comment]
I will try to create tickets for the Arbi-BOM owned migration work that needs to happen today.

**Comment by jristau1984** [comment]
This is no longer needed.
