### ISSUE TITLE
[Docs] Write How to Use The Event Bus guide for other developers

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#64]
Acceptance criteria:

- [ ] A clear step-by-step guide on how to use the event bus for any given use case, including instructions on both development and deployment
- [ ] Links to further useful reading (ADRs, confluent docs, articles on event design, etc.)

**Comment by robrap** [comment]
* An initial private doc was started https://2u-internal.atlassian.net/wiki/spaces/AT/pages/174555142/How+to+Use+the+Event+Bus, but is WIP and needs review.
* A link was added from that page to a public how-to that was mostly an outline, but had some links: https://openedx.atlassian.net/wiki/spaces/AC/pages/3508699151/How-to+start+using+the+Event+Bus
* If sections of this make sense in a separate task (like Observability), we can create a new task.

**Comment by robrap** [comment]
@rgraber: We may need to groom, but this also seems in-progress and assigned to you???

**Comment by rgraber** [comment]
Moved to in progress and assigned to myself. My plan today is to finish up the private WIP, get eyes on it from our team and some other folks who have expressed interest, then try to separate out the public and private bits.
