### ISSUE TITLE
Fork several analytics repos so they can be used internally after archival

### ISSUE THREAD

**Issue by jristau1984** [edx/edx-arch-experiments#640]
https://twou.slack.com/archives/C04ACDVM6A1/p1715870768122069

Gerhard Lennox
Hi @here. Anyone able to assist with unarchiving a few repos for us on the openedx-unsupported github org. There was an oversight our end and we need to fork the required Repos. Current Analytics Exported is broken due to this. Apologies for the oversight.  they are actively used for Analytics Exporter

- https://github.com/openedx-unsupported/edx-analytics-configuration
- https://github.com/openedx-unsupported/edx-analytics-exporter
- https://github.com/openedx-unsupported/edx-analytics-pipeline

**Comment by robrap** [comment]
@timmc-edx @jristau1984: Is this ticket ready to close?

**Comment by timmc-edx** [comment]
Yep!

**Comment by timmc-edx** [comment]
Note: We'll need to restore these rows in the ownership spreadsheet next time the sync runs.
