### ISSUE TITLE
[Dashboard] Bring NR dashboards to DD

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#649]

**Comment by robrap** [comment]
@connorhaugh: Do you need/want this ticket, or is this all being tracked per team in separate tickets? If you want it, maybe clarify the ticket? Otherwise, feel free to close with a comment. Thank you.

**Comment by connorhaugh** [comment]
> Closed as this process will be tracked here: https://docs.google.com/spreadsheets/d/1sh9eE-vT5JysI4BAx_qlkhzZ0hEujM_B18qL4XQoq1k/edit#gid=1751279964
