### ISSUE TITLE
Complete required QA for event to turn on in Production

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#65]
Acceptance Criteria

- [ ] Get clear on what is required for testing
- [ ] Complete testing
- [ ] Document what we learn about discovery in the process

**Comment by robrap** [comment]
How does Dawoud's list of use cases align with how the event works? Curious about relationship to draft/published, etc.

**Comment by rgraber** [comment]
Blocking on phoenix discovery/testing.

**Comment by dianakhuang** [comment]
There's a question about the behavior of the `hidden` field and what it should be doing in in Studio that we need to resolve.

**Comment by robrap** [comment]
This was moved to Done, so I'm closing the ticket.
