### ISSUE TITLE
Update span ingest rules to better match what we wish to index

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#653]
We _may_ want to update our span ingest rules, but possibly not. 

- It is possible that some of our django.request spans are not being ingested due to rate limiting for other types of spans. This may get us all the spans that make up our django.request metrics.
- It is possible we might want to reduce ingest of heartbeats, but not sure.
- It is possible we might want to reduce other span ingest that isn't important, but this may not be important. Span ingest is not as costly as span index. 

This could easily be more complicated than it is worth, so we may choose to make no changes. This ticket is at least a place to document our thoughts.

Also see this DD support ticket with some relevant questions: https://help.datadoghq.com/hc/en-us/requests/1671099. Ask @robrap if you need access.

**Comment by robrap** [comment]
FYI: @pwnage101

**Comment by robrap** [comment]
From the support ticket:

> If no [tracer-side rules](https://docs.datadoghq.com/tracing/trace_pipeline/ingestion_mechanisms/?tab=java#in-tracing-libraries-user-defined-rules) are defined, the Agent will only accept 10 traces per second total. So no, it is not configured to ingest 100%. The Agent will apply a sampling priority to each span based on this rule. 
> 
> - If you do use a tracer side rule like DD_TRACE_SAMPLE_RATE, this will override the Agent's default ingestion mechanism. Once you set a tracer side rule, the new trace limit is 100 traces per second. You can modify this even further by increasing or decreasing it using DD_TRACE_RATE_LIMIT
> - You can set a per service sample rate (DD_TRACE_SAMPLING_RULES) or a global tracer limit (DD_TRACE_SAMPLE_RATE)
> - Regarding your Django scenario, you wouldn't necessarily set a rule on Django requests. You would set a sampling rule on the service:
>  ```
export DD_TRACE_SAMPLING_RULES='[{"service": "my-Django-service", "sample_rate": 1.0}]'
```
> - This would ingest 100% of the Django service traces up to 100 per second. (the 10 per second would no longer apply because the Agent default would be overridden)

**Comment by robrap** [comment]
Based on the support ticket comment, I'd like to highly consider adding a sampling rule for our main service with a higher sample rate, and then possibly we'll need the global sample rate to be set closer to 10 (the original) than 100. The support ticket is still ongoing, so there may be more details by the time we get to anything like this.

**Comment by pwnage101** [comment]
That would be the simplest thing to do (just ingest all traces), and if it works it works!

We might also consider a span-based sampling rule to ingest only the root span of anything that hasn't already been ingested as a full trace via head-based sampling.  That way, we don't incur the extra network/CPU overhead (including agent-to-agent coordination between django, mysql, memcache, etc.) to do the full work of collecting the full trace for the 11th+ request for that agent in that second.

```
export DD_SPAN_SAMPLING_RULES=[{"service": "edx-edxapp-lms", "name": "django.request", "sample_rate":1.0, "max_per_second": 50}]
```

The above means: "Use the default trace sample rate of 10 full traces per second per head.  If any trace WOULD get discarded (i.e. more than 10 requests per second), then check if the root span of the trace is equal to `django.request` and if so then ingest that root span only (but do not tell mysql, memcache, etc. to initiate span collection for this trace)."

**Comment by robrap** [comment]
@pwnage101:
1. According to the support ticket, `"sample_rate":1.0` is going to give 100 traces per second. The 10 traces per second is only the default with no other configuration.
2. What you are stating doesn't totally jive with my understanding of the support ticket. Would you mind both reading the support ticket and then adding any of your own thoughts to the support ticket to have DD confirm that your thinking is accurate? Thank you.

**Comment by pwnage101** [comment]
> According to the support ticket, "sample_rate":1.0 is going to give 100 traces per second. The 10 traces per second is only the default with no other configuration.

The context of what's said on the support ticket is all about adjustments to trace sampling rules via one or more of:
* `DD_TRACE_SAMPLING_RULES`
* `DD_TRACE_SAMPLE_RATE`
* `DD_TRACE_RATE_LIMIT`

And it aligns with my understanding.

**However**, what I'm talking about is `DD_SPAN_SAMPLING_RULES` which allows defining its own `max_per_second`.  By _layering_ additional span rules, we can have BOTH the 10 traces/second default plus the extra root trace sampling with a higher sampling cap.

**Comment by robrap** [comment]
Thanks @pwnage101. That is clear. Can we just add that to the support ticket to confirm your understanding? It’s not clear to me if even when adjusting only the setting you mentioned, whether the default for traces would change. Either way, we should be able to set these to make everything more explicit.

**Comment by robrap** [comment]
I don't think there is anything we need to do at this time, so I am closing this ticket.
