### ISSUE TITLE
Update APM spreadsheet service tag columns

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#657]
- The migration doc could probably have better instructions for updating Column I, J, and K (the service tag columns) in the APM [sheet in Datadog Migration Tracking](https://docs.google.com/spreadsheets/d/1sh9eE-vT5JysI4BAx_qlkhzZ0hEujM_B18qL4XQoq1k/edit#gid=0). 
- Searches that would help list across all services to help update the spreadsheet in a large batch may or may not be useful for individuals verifying per row.
- The columns read "Service tag", but we might want to verify the `env` tag as well. What about `version`?
- Issues found may be able to be made into new subtasks under https://2u-internal.atlassian.net/browse/GSRE-1629.
- One known issue is that `edx-edxapp` is going to be the tag (for now) across all edxapp services for Infrastructure only. 
  - SRE is working on this as part of https://2u-internal.atlassian.net/browse/GSRE-1631
- Can we get any arch-bom owned rows to be marked completed to move the needle on APM progress, and to demonstrate what needs to be done?

**Comment by robrap** [comment]
@jristau1984: Feel free to update this ticket with actual tasks, and updates from what you've learned/done so far. I assigned it to you and marked it in-progress.

**Comment by jristau1984** [comment]
I have gone through the APM, Infra, DD Team, resource_name, and Logs columns.  I have updated the status of each row,  with an appropriate link as needed.  I think this is the outcome that was desired with this ticket.

We decided to ignore `version` for our purposes, and teams can dig into that on their own as desired.
