### ISSUE TITLE
Migrate Arch-BOM dashboards

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#661]
# Acceptance Criteria

Migrate the following dashboards:
- [x] [LMS - Missing code_owner](https://one.newrelic.com/redirect/entity/ODgxNzh8VklafERBU0hCT0FSRHwxNTEyODA0)
- [x] [Safe Session User Mismatches](https://one.newrelic.com/redirect/entity/ODgxNzh8VklafERBU0hCT0FSRHxkYTo0OTA1NzE)
     - Safe Session User Mismatches / Safe Sessions 
- [x] [Codejail error breakdown (edX)](https://one.newrelic.com/redirect/entity/ODgxNzh8VklafERBU0hCT0FSRHwxMzA3NDQ1)
- [X] ~~[Event Bus Kafka overview](https://one.newrelic.com/redirect/entity/ODgxNzh8VklafERBU0hCT0FSRHxkYToyMTAzNjM4)~~ (Moved to Kafka ticket.)
- [x] [IPs and XFF - rate-limiting, other (Arch-BOM)](https://one.newrelic.com/redirect/entity/ODgxNzh8VklafERBU0hCT0FSRHxkYToxMDA0OTcz)

**Comment by dianakhuang** [comment]
DD missing code owner dashboard: https://app.datadoghq.com/dashboard/c9q-24y-fbe/lms---missing-codeowner?fromUser=true&refresh_mode=sliding&view=spans&from_ts=1714338169171&to_ts=1716930169171&live=true

**Comment by dianakhuang** [comment]
Codejail error breakdown: https://app.datadoghq.com/dashboard/qye-jtx-kjr/codejail-error-breakdown-edx

**Comment by dianakhuang** [comment]
All arch-bom dashboards: https://app.datadoghq.com/dashboard/lists?q=team%3Aarch-bom

**Comment by timmc-edx** [comment]
@dianakhuang I reviewed these, and I think https://app.datadoghq.com/dashboard/m3b-uvv-9w4 is the only one remaining for review (LMS alert diagnosis dashboard).

**Comment by dianakhuang** [comment]
@timmc-edx dashboard looks good to me. I think the documentation/runbook needs to be updated to help people diagnose errors, but I think that's partially on me as well.

**Comment by timmc-edx** [comment]
I converted the last of the New Relic links in https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/1083605119/Squad-owned+LMS+Datadog+alert+runbook although I think the on-dashboard docs are going to be the most helpful.
