### ISSUE TITLE
Migrate Arch-BOM alerts/monitors

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#662]
Acceptance Criteria:
- go through the [spreadsheet](https://docs.google.com/spreadsheets/d/1sh9eE-vT5JysI4BAx_qlkhzZ0hEujM_B18qL4XQoq1k/edit#gid=1917969301)
- migrate the alerts and alert policies to DataDog
- update runbooks to point to DataDog

Policies:
- [x] prod-edx-edxapp-lms-arch-bom - Mostly done as part of https://github.com/edx/edx-arch-experiments/issues/628 but will be converted to Terraform; runbook needs update @timmc-edx 
  - [X] create monitors (lms)
  - [x] create monitors (lms-workers)
  - [x] update runbook 
  - [x] review monitors and runbook
- [x] prod-edge-edxapp-lms-arch-bom - ditto @timmc-edx 
  - [X] create monitors (lms)
  - [x] create monitors (lms-workers)
  - [x] update runbook 
  - [x] review monitors and runbook
- [x] prod-edxapp-lms-arch-bom-backend-safety-net @dianakhuang 
  - [x] create monitors (in-progress)
  - [x] update runbook 
  - [x] review monitors and runbook
- [x] platform-arch-bom-event-bus-safety-net @robrap 
  - [x] create monitors (logs) (in-progress)
  - [x] ticket non-log monitors and runbooks (moved to https://github.com/edx/edx-arch-experiments/issues/658)
  - [x] review monitors and runbook
- [x] platform-arch-bom-ownership
  - [x] create monitors
  - [x] update runbook 
  - [x] review monitors and runbook
- [x] platform-arch-bom-code-owner-issues - @timmc-edx 
  - [x] create monitors
  - [x] update runbook 
  - [x] review monitors and runbook

After runbooks have been migrated:
- [x] Archive https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/19470837/Squad+Owned+LMS+New+Relic+Alert+Runbook

**Comment by robrap** [comment]
For event bus monitoring, migrate the following:
- Consumer error logs across multiple topics [P3]
- Producer error logs across multiple topics [P3]

Move the following monitors to the Kafka ticket:
- No event consumed in past day on any topic [P3]
- No event produced in past day on any topic [P3]
- TransactionErrors in consuming across topics [P3]

**Comment by timmc-edx** [comment]
Still to do:

- Migrate code-owner-issues alerts
- Perform a review on monitors and runbooks
