### ISSUE TITLE
Complete migration of arch-bom owned APM

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#671]
Acceptance Criteria:
- [x] Get all arch-bom owned [APM rows](https://docs.google.com/spreadsheets/d/1sh9eE-vT5JysI4BAx_qlkhzZ0hEujM_B18qL4XQoq1k/edit#gid=0) marked as completed (after completing the work).
  - [x] If rows don't belong, delete them. (Double-check New Relic for Messages (vs. Web))
- [x] Inform Cosmonauts about edx-exam-attempt-lifecycle-kafka-consumer rows now being assigned to them.

Question:
- [ ] Is [Slack inform](https://twou.slack.com/archives/C048L3Y9RDG/p1728662624018699) about ownership for Kafka event bus consumers good enough, or do we want to ensure we or teams add team ownership to DD? What about monitoring?

Notes:
- See https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/1008042104/How+to+use+Datadog+after+coming+from+New+Relic#Infrastructure

**Comment by jristau1984** [comment]
Most content has been migrated, but due to a series of discovered bugs that are logged with DD Support, we are going to keep this open and in Blocked until we can perform a final review of all the APM that should be migrated. (e.g. https://github.com/edx/edx-arch-experiments/issues/692)

**Comment by jristau1984** [comment]
Moving to backlog to declutter the board.  This cannot be implemented until at least the concatenation issue and Kafka instrumentation+monitors have been completed.

**Comment by robrap** [comment]
@jristau1984 @spencertiberi: I've finished what I wanted to do for arch-bom owned services. However, event bus consumers are services that arch-bom is sometimes concerned with, and let's discuss if we or Spencer (who I assigned this ticket to) should help get that part over the line. See Slack thread linked from Issue description.

**Comment by jristau1984** [comment]
I completed the assignment of team owners to all unassigned services.  Monitors may still be pending, but I could not get to the same list @robrap landed on so I will leave that for a different day.

**Comment by robrap** [comment]
@jristau1984: 
- Here is the list from the [Reliability tab of the Service Catalog](https://app.datadoghq.com/services?query=edx-&env=%2A&fromUser=true&lens=Reliability&sort=monitors&start=1731004263029&end=1731007863029).
- Should we do any follow-up on this with other teams to ensure there is appropriate monitoring, or do we just let that be a concern for each team and move on?

I believe this ticket as titled is ready to close, but we can decide if we want a separate ticket or action item or nothing. Thanks.

**Comment by jristau1984** [comment]
I am okay with calling this complete, since teams have been notified in the observability channel.

**Comment by robrap** [comment]
Closing as completed. Thanks.
