### ISSUE TITLE
Create arch-bom monitors for costly DD usage

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#675]
AC:
- [ ] Propose new monitors for arch-bom usage
- [ ] Implement new monitors for arch-bom usage

Notes:
- GSRE ticket for overall alerts, and also has doc links for usage monitors: https://2u-internal.atlassian.net/browse/GSRE-1721
- Here are edxapp-related items with the biggest cost implications:
  - APM Hosts (which may get renamed to Enterprise Hosts, so we also might want to alert on too few)
  - Indexed Logs
  - Index Spans
-  Here are all items with the biggest cost implications:
  - Infra Hosts (do we care, or is APM good enough?)
  - APM Hosts (which may get renamed to Enterprise Hosts, so we also might want to alert on too few)
  - Indexed Logs
  - Synthetics API Test Runs
  - RUM Sessions
  - Index Spans
- Do we want edxapp focused monitoring for usage?
- Do we want different permanent vs temporary monitors for DD rollout vs future stable DD?
- @timmc-edx looked into monitoring for increase in spans seen in Span Explorer, but we can't see that via any metrics.

**Comment by jristau1984** [comment]
If the team is okay with having SRE be the safety net for changes, and relying on their monitors... I am fine with closing this.

**Comment by robrap** [comment]
@jristau1984: I still think we should think about this before closing, but I just wanted to gauge if it was still your number 1 priority. It sounds like we can put that off a little bit, and/or move it to the future epic. Thanks.

**Comment by jristau1984** [comment]
I think backlogging it defeats the purpose.  Perhaps its a quick "validation" dashboard that can be used to confirm config changes dont cause billing related regressions, which is maybe a smaller lift than a set of alerts?

**Comment by robrap** [comment]
Why don’t we just timebox it. We should be able to get something useful done with not a lot of effort, and edxapp focused alerts will probably be permanently useful. A quick supporting dashboard would also help, but I don’t think that should replace monitors.

**Comment by robrap** [comment]
@jristau1984: This doesn't feel urgent to me. Can I move into the Future epic so we can discuss along with all the other future migration work?

**Comment by jristau1984** [comment]
Sure, if we even need it anymore.  SRE expedited their alerts so this may not even have real value anymore.

**Comment by robrap** [comment]
I’m going to close as Won’t Do. There are too many other tasks. Thanks.
