### ISSUE TITLE
[DEPR-2U] Content Libraries V1

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#682]
2U follow-up for 
- [ ] https://github.com/openedx/edx-platform/issues/32457

@jristau1984: How do we want to track DEPR work for TNL or other teams, or ensure that other teams know what is needed?

**Comment by jristau1984** [comment]
This has no current target date.  I think we should maybe retire this ticket and create a new one when the proposal is accepted and gets a target date.  Thoughts?

**Comment by robrap** [comment]
@jristau1984: That makes sense. I'm going to close this as unplanned for now, and we can always reopen or recreate when it is needed.
