### ISSUE TITLE
No notifications for failing docker builds in edx-platform

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#688]
We have workflows in openedx/edx-platform that build and push docker images. When these fail, we don't get any notification. This can result in stale images or incompatibilities.

**Comment by jristau1984** [comment]
This should be considered for possible scope of Dev Experience improvement epic.

**Comment by UsamaSadiq** [comment]
This will be covered in https://github.com/edx/public-dockerfiles/pull/11 so closing the issue.
