### ISSUE TITLE
Disable NR for edxapp

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#694]
Blockers:
- [x] https://github.com/edx/edx-arch-experiments/issues/692 (tracing issue)
- [x] https://github.com/edx/edx-arch-experiments/issues/658 (kafka monitoring)
  - I guess this isn't a blocker, but we should correct this blindspot sooner rather than later.

Acceptance Criteria:
- [x] NR disabled for all of edxapp
  - [x] LMS
  - [x] CMS
  - [x] LMS Workers
  - [x] CMS Workers
  - [x] [Kafka Consumer in k8s](https://github.com/edx/edx-internal/pull/11758)
- [x] Remove other old New Relic config/code, or ticket the removal
   - [x] https://github.com/edx/edx-internal/pull/11757
   - [x] https://github.com/edx/configuration/pull/77
   - [x] Remove newrelic as a dependency of edx-platform (probably a DEPR, and needs review of code references first) -- filed https://github.com/edx/edx-arch-experiments/issues/829

**Comment by jristau1984** [comment]
@robrap is this worth assigning to yourself or Tim and moving to IN PROGRESS?  I believe at least some of these are checked off now...

**Comment by robrap** [comment]
@jristau1984:  think this is blocked on the DD ticket marked in the description. We have removed the cost, but we haven't actually been able to remove NR and the performance impact and code, etc.

**Comment by jristau1984** [comment]
Moving to backlog to declutter the blocked column.  This will not be able to be picked up until at least concatenation issue is resolved with DD support.

**Comment by jristau1984** [comment]
Marking this as "P2" priority, due to the fact that we are still incurring at ~20% performance impact from having both instrumentations active at the same time.  

When this becomes unblocked, we should prioritize it immediately.

**Comment by robrap** [comment]
@jristau1984: I moved back from Blocked to Backlog, and put it in the new Post-New Relic epic that denotes that all its tickets are blocked.
