### ISSUE TITLE
Fix devstack ecommerce provisioning failure

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#697]
Acceptance Criteria:
- [ ] Get devstack provisioning test to pass again.

Devstack provisioning failed for ecommerce. ([OpsGenie link](https://2u-internal.app.opsgenie.com/alert/detail/6cf2630c-1846-4dd7-9afb-2470ec44b9b2-1718970426259/details))

- Originally assked [purchase to look into this in Slack](https://twou.slack.com/archives/C04B3V5QL3W/p1718987453326329).
- They mentioned ecommerce has not changed, and pointed out https://github.com/pypa/setuptools/issues/3889.

**Comment by jristau1984** [comment]
This has been resolved.
