### ISSUE TITLE
RCA or discussion of 5 minute edxapp outage

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#699]
Edxapp LMS outage for 5 minutes.

- Seems to be mysql lock related when running migrations, but reason is unclear.
- May have been exacerbated by Discovery Service request queuing, resolved with increasing CPU limit.
- [See Slack thread](https://twou.slack.com/archives/C048NH9K5BN/p1718649004396659). Alex D was investigating, and we did not yet create an RCA page.

Do we want an RCA or any further discussion, or are we just putting this one behind us?

**Comment by jristau1984** [comment]
Closing due to age.
