### ISSUE TITLE
Enable monitoring for consumer infinite loop

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#70]
**Acceptance Criteria:**

- [ ] Add New Relic background task monitoring to consumer infinite loop process

**Notes and questions:**

* See https://docs.newrelic.com/docs/apm/agents/python-agent/supported-features/monitor-non-web-scripts-worker-processes-tasks-functions/#wrapping
* What will the task name be? Should it be dynamic? Will it be topic based, or should that just be a custom attribute?
* From New Relic docs: Note that whatever is wrapped by the background task decorator or context manager object, it must be a task which has finite execution time. You must not wrap the main loop of a process within which the separate tasks are being run.

**Comment by robrap** [comment]
We probably want to add a `record_exception` call to any handled exceptions. This is probably a separate issue, but I'm being lazy and dropping this here for now. It could be done as part of this, or we can create a new task. See https://github.com/openedx/edx-django-utils/blob/master/edx_django_utils/monitoring/__init__.py#L27 for the record_exception call.

**Comment by dianakhuang** [comment]
- [ ] Test monitoring on single process
- [ ] Record exceptions in messages and event processing
- [ ] Move monitoring to cover everything in the loop.

**Comment by dianakhuang** [comment]
We discovered that the New Relic Kafka support was capturing consumer transactions for us, so we didn't go through with reporting this data manually.

**Comment by robrap** [comment]
Closing due to last comment. We will look into reporting errors in a separate ticket.
