### ISSUE TITLE
Celery tasks missing from DD

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#700]
Troy created a ticket: https://help.datadoghq.com/hc/en-us/requests/1747459

So far - @robrap is the only collaborator.

From ticket:
> It seems like not all of our celery tasks are ingested into DataDog. When we try to count runs of a specific celery task (update_full_content_metadata_task) we find that there are a different counts depending on whether Metrics or Spans are queried, but more importantly we find that the actual task counts determined via Splunk are much higher than either counts determined via DataDog.
>
> Screenshots attached demonstrate queries against Metrics, APM spans, and also a Splunk query which we consider a reliable source.
>
> Questions:
> 
> 1. Why might celery task counts be different between metrics and spans? Are my queries non-equivalent?
> 
> 2. Is there a common issue with either/both DD queries that would result in several celery tasks discovered via Splunk not appearing at all in DataDog?

This task is to ensure Troy or others follow-up and get this closed.

**Comment by robrap** [comment]
During research for this, it was discovered that one problem (not the only problem) was that we have a retention filter for k8s spans that is pretty general. 
1. We need to find a way to drop it, and add back exclusions for the specific pods, or services, etc.
2. We need to ensure that our indexed logs doesn't go over budget, and that we compensate with appropriate rules.

**Comment by timmc-edx** [comment]
This turned out to be mostly an issue with log ingestion; we'll reopen if it turns out there's a tracing issue as well.
