### ISSUE TITLE
Pin NewRelic to <8.2.0

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#71]
- [ ] Pin NewRelic to <8.2.0 in edx-platform to deal with a bug in confluent kafka instrumentation introduced in 8.2. 
- [ ] Create a ticket to unpin once the support ticket is addressed

To follow the support ticket, you can ask @robrap to add you as a collaborator.

**Comment by robrap** [comment]
We removed (or never added) the pin. The confluent issue was fixed, and we are now at 8.4.0. Closing.
