### ISSUE TITLE
Cleanup metrics work from devstack

### ISSUE THREAD

**Issue by jristau1984** [edx/edx-arch-experiments#718]
[FROM ARCHBOM JIRA]

Acceptance Criteria

- [x] Remove metrics-opt-in/metrics-opt-out as make targets in devstack
- [x] Remove devstack/scripts/send_metrics.py
- [x] Remove references to metrics things in the documentation

There is also Segment and New Relic related clean-up, including communicating any Segment changes to DE and updating their docs, because they will have some cleanup as well. We can also dig up links.

**Comment by huniafatima-arbi** [comment]
PR is raised against this issue
[PR Link](https://github.com/edx/devstack/pull/35/files)
@iamsobanjaved @UsamaSadiq Please give it a review
