### ISSUE TITLE
Migrate Slack channels from edx-internal to twou

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#73]
Worklist: https://docs.google.com/spreadsheets/d/1AmHH1f9L6syrZ190B0GFZ7bUEMQVj6joE2iQ64vjZ8E/edit#gid=0

Note: This issue originally pointed to https://2u-internal.atlassian.net/wiki/spaces/AT/pages/190218278/edx-internal+twou+Slack+migration, which no longer seems to be a page.

**Comment by jmbowman** [comment]
Waiting until Arbisoft contractors have access to the 2U Slack.

**Comment by jmbowman** [comment]
They now have access, so we can start scheduling this work.

**Comment by robrap** [comment]
n April 2023, you will lose access to the edX workspace. This date was selected to give everyone enough time to fully migrate channels and information to the 2U workspace. During the first week in October, all 2U employees will gain access to the 2U Slack workspace. For edX Slack users, you will have access to both the 2U and edX Slack workspace. Below is an outline of what you can expect during the first week of October into November. After November 18, you’re expected to stop using [edx-internal.slack.com](http://edx-internal.slack.com/) for any new messages and only use it for reference. 

 

Here’s the timeline in more detail:

 

October 2022

    You will gain access to the 2U Slack workspace the first week in October.

    To reference historical information from edx-internal Slack, we will provide instructions on how to connect your edx-internal channels to the 2U Slack with Slack Connect.

    Starting in October, all edX Slack users will have six (6) weeks to migrate their channels to the 2U workspace including:

        [Re-create Channels] Recreating your channels using the self-service Slack Helper Bot

        [Move Integrations] Moving integrations, bots, workflows, and other automations to your new channels

        [Slack Connect] Working with external organizations to reconnect Slack Connect connections with channels in the twou workspace

        [Re-Invite Guests] Guests who had single channel or multi-channel access in edx-internal will need to be re-invited to twou and comply with our Contractor Access provisions in the [Electronic Communications Policy](https://2uinccomms.us.newsweaver.com/14lcn9o3s2/gdrbiukgg2j2dtzeehbutj/external?email=true&a=6&p=11245063&t=627257)

        [Move Operations] Using twou for all new conversations and not using edx-internal for any new conversations.

        [Archive Channels] Use the Slack Helper Bot to archive any channels that don’t need to be referenced or used.

    Resources, guidance, and FAQs will be provided to help you manage the self service migration process in October.

 

November 2022

    The final day to move your team’s daily operations from edx-internal to twou Slack will be on Friday, November 18. 

    After this date you will maintain read-only access to channels for historical reference until April 2023.

 

In the next few weeks, we will provide additional information and resources to make the migration process as seamless as possible. For information about the Slack migration process, please refer to the [Slack 2Universe page here](https://2uinccomms.us.newsweaver.com/14lcn9o3s2/1ekq9lab0c52dtzeehbutj/external?email=true&a=6&p=11245063&t=627257).

**Comment by robrap** [comment]
Updated email and links:

You now have access to both the edX Slack workspace and the 2U Slack workspace. From now until Nov. 18, 2022, you should migrate channels and information into 2U Slack. After Nov. 18, 2022, you’re expected to stop using the edX Slack workspace for any new messages. You will maintain read-only access to channels for historical reference until April 2023, in alignment with the workspace retention policy. In April 2023, you will lose access to the edX Slack workspace. 

 

As promised, below are more detailed instructions and resources for edX Slack users to help migrate from edX Slack to 2U Slack. 

 

Recommended steps for migration to 2U Slack:

    Step One: Read through the [Slack Migration Guide for Legacy edX Team](https://2uinccomms.us.newsweaver.com/14lcn9o3s2/8qd4cbzdfgd2dtzeehbutj/external?email=true&a=6&p=11449486&t=627257).
    This resource is intended to be a high-level guide for you and your team to help plan your migration. We highly recommend you read through this guide in its entirety before migrating any information.

    Step Two: Put together a Slack migration plan with your team.
    Use the Slack Migration Guide for Legacy edX Team resource to create a migration plan that works for you and your team. We recommend putting together a plan before creating any channels, groups, or moving your apps or integrations.

    Step Three: Complete the [Checklist for Migration](https://2uinccomms.us.newsweaver.com/14lcn9o3s2/1wq2itpdcsh2dtzeehbutj/external?email=true&a=6&p=11449486&t=627257) document by Nov. 18, 2022.
    This checklist is found within the Slack Migration Guide for Legacy edX Team resource. It provides detailed instructions about adding apps, exporting/importing workflows, moving integrations, connecting historical reference channels, and more.

Other Resources:

    Find support on the #support-slack channel in the 2U Slack workspace.

    Use the Slack Helper Bot to create channels (private or public), rename channels, archive channels, remove users from channels, create a user group, or update a user group. 

    Check out our 2Universe [Slack Resources](https://2uinccomms.us.newsweaver.com/14lcn9o3s2/av6cl1n00sv2dtzeehbutj/external?email=true&a=6&p=11449486&t=627257) and [Slack Frequently Asked Questions](https://2uinccomms.us.newsweaver.com/14lcn9o3s2/1sddqqqi1z32dtzeehbutj/external?email=true&a=6&p=11449486&t=627257) pages. 

Thanks for all your efforts in migrating to 2U Slack. We hope to make the transition as seamless as possible. If there are any questions, please do not hesitate to reach out in the #support-slack channel.

**Comment by timmc-edx** [comment]
Stable heading link: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16386007/BOM+Sprint+Retro+Planning#2022-10-21

**Comment by timmc-edx** [comment]
All items are now represented in spreadsheet.

**Comment by robrap** [comment]
@timmc-edx: Should we split out separate tickets that are blocked on different reasons, or one ticket for all blockers, and note them? For example, #arch-bom-notifications waiting on New Relic integration, etc.? In any case, it might be cleaner than leaving this open indefinitely.

**Comment by timmc-edx** [comment]
My preference is just to leave it in blocked for now.

**Comment by timmc-edx** [comment]
(Spreadsheet has been updated to explain blocked status of remaining channels.)

**Comment by robrap** [comment]
I updated JIRA and New Relic to point to #alert-arch-bom. For New Relic, I updated the existing notification channel, and did not switch to workflows.

:white_check_mark: You have connected Arch Bom (ARCHBOM) to [#alert-arch-bom](https://twou.slack.com/archives/C04A10SLPFZ).

**Comment by robrap** [comment]
The remaining migrations in the spreadsheet are blocked on https://jira.2u.com/servicedesk/customer/portal/9/PSO-11955 (Three RSS feed integrations for software releases), created by Tim and shared with Robert and Jeremy (so far). The ticket had a status changed to Prioritized on 11-28-2022, so giving it some time before reaching out again to Sys Ops.

**Comment by robrap** [comment]
I moved the remaining work to https://github.com/edx/edx-arch-experiments/issues/120. I find it simpler to digest what is left, and will mark this as closed.
