### ISSUE TITLE
Set up Datadog 'ignored errors' functionality

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#738]
We would like to be able to filter out certain errors from our monitors/alerting in Datadog because they aren't errors that we believe we should take action on.

This would probably be similar to the 'ignored errors' functionality we had on NewRelic.

For example:
- `rest_framework.exceptions.Throttled`

**Comment by robrap** [comment]
Notes:
- Errors be found using search `error.type:rest_framework.exceptions.Throttled`.
- We should target arch-bom edxapp monitors and updating our run book, and also communicate out what we learn. Not sure if this would touch the terraform templating or not.

**Comment by dianakhuang** [comment]
Closing as a duplicate of https://github.com/edx/edx-arch-experiments/issues/625
