### ISSUE TITLE
Alerting if DD logs found with "finishing span name" OR "no traceparent header"

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#752]
The purpose of this ticket is to allow for monitoring of these messages, in case someone forgets to configure things correctly for a new service, and these errors reappear.

- [See DD search](https://app.datadoghq.com/logs?query=%22finishing%20span%20name%22%20OR%20%22no%20traceparent%20header%22%20&agg_q=service&agg_q_source=base&cols=host%2Cservice&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort_m=&sort_m_source=&sort_t=&storage=hot&stream_sort=desc&top_n=10&top_o=top&viz=stream&x_missing=true&from_ts=1713283848972&to_ts=1713287448972&live=true).
- This relates to https://github.com/edx/edx-arch-experiments/issues/610, where we might adjust how we configure disabling the logs that contain these errors.
- Relates to https://github.com/edx/edx-arch-experiments/issues/753 as well.

**Comment by jristau1984** [comment]
Recheck at the end of September.  If nothing for September, this should be closed.

**Comment by jristau1984** [comment]
There is nothing in logs for the past month.  I am closing this now, per the last comment.
