### ISSUE TITLE
Discovery: Ensure that we don't need DD errors that were disabled

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#753]
We disabled DD-related errors and warnings because the top errors didn't seem helpful (possibly were NR-related) and they were going to the wrong file.

- We aren't actually sure if the disabling this logging is covering up real issues. 
  - Can SRE still see these errors/warnings on the box?
  - Are there other errors/warning that we should be looking into if we had visibility? 
  - Will this issue be gone in a post-New Relic world, or is it its own problem? What about after the DD trace-concatenation issue?
- https://github.com/edx/edx-arch-experiments/issues/610 discusses refactoring how we've disabled these errors, but doesn't address the question of whether or not it is a problem that we are no longer seeing errors/warnings about DD?
- https://github.com/edx/edx-arch-experiments/issues/752 is to ensure that these errors don't appear when we are trying to suppress them.

**Comment by timmc-edx** [comment]
Agreed, we don't actually want any of the `DD_TRACE_DEBUG` information (which we needed to suppress by setting `DD_TRACE_LOG_STREAM_HANDLER` for some reason).
