### ISSUE TITLE
Fix test-publish CI in edx-arch-experiments

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#773]
The test-publish CI check in edx-arch-experiments is failing due to lack of 2FA on the testpypi account. This increases the risk that we'll have trouble making a real release.

Example failure: https://github.com/edx/edx-arch-experiments/actions/runs/10359826374/job/28677015506

```
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         User 'edX' does not have two-factor authentication enabled. Please     
         enable two-factor authentication before attempting to upload to PyPI.  
         See https://test.pypi.org/help/#two-factor-authentication for more     
         information.                                
```

Filed https://2u-internal.atlassian.net/servicedesk/customer/portal/15/DOS-5079 for SRE to fix this. Moved to https://2u-internal.atlassian.net/browse/GSRE-1991.

**Comment by robrap** [comment]
[inform] The GSRE ticket is assigned to @dianakhuang. Is that accurate, and is this ticket not blocked on SRE?

**Comment by timmc-edx** [comment]
SRE doesn't have login info; we'll need to file an issue with test-pypi to beg for a password reset/account recovery (via trusted email address).

**Comment by timmc-edx** [comment]
Filed a request to PyPI for account recovery: https://github.com/pypi/support/issues/4768

**Comment by jristau1984** [comment]
This could use a follow up with SRE in the linked GSRE ticket.

**Comment by timmc-edx** [comment]
2FA enabled on account and CI check now works.
