### ISSUE TITLE
Create a project page for all Devstack milestones, project plan, etc

### ISSUE THREAD

**Issue by jristau1984** [edx/edx-arch-experiments#775]

**Comment by jristau1984** [comment]
@dianakhuang can I assign this to you to draft up a project page, and I can assist as needed?

**Comment by dianakhuang** [comment]
I did start this a while back. Here's the page: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/1265336321/Devstack+Improvements+Project

We do need to fill out details for our other milestones.
