### ISSUE TITLE
Document and commit to decision around edxapp middleware spans

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#778]
During the New Relic work, we _temporarily_ disabled spans for middleware. @timmc-edx mentioned he'd like to leave it this way.

AC:
- [ ] Create ADR for disabling (or enabling) middleware instrumentation in edxapp.
- [ ] Update comments around disabling, or ticket re-enabling, depending on decision.
- [ ] Communicate the decision to other teams.

Notes/Questions:
- Middleware instrumentation is currently disabled in edxapp, and likely enabled in other services, so we can still screenshot the differences.
- What do we lose without the middleware spans when working on or debugging middleware issues or errors?
- What are the workarounds if we leave this disabled? Could it makes sense documenting temporarily enabling in an environment if we are working on a middleware issue?

**Comment by timmc-edx** [comment]
I don't know that it needs to be assigned to me—I don't have strong feelings around it, and I think anyone can make the decision. I'll just link this from 692 for now.

**Comment by robrap** [comment]
Thanks @timmc-edx. I unassigned you. That said - I thought you had an opinion somewhere to leave this disabled. If you do have any thoughts, you can document them in a comment on this ticket.

**Comment by timmc-edx** [comment]
Added commentary to https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/1008500894/Datadog+configuration+and+setup+details

**Comment by timmc-edx** [comment]
Communicated in observability Slack channel: https://twou.slack.com/archives/C048L3Y9RDG/p1730233003973139

I'm not sure we need an ADR for this, with the wiki docs in place. If we don't, then this issue is probably complete.

**Comment by robrap** [comment]
Closing as complete. Thanks @timmc-edx,
