### ISSUE TITLE
[Discovery] Automate python requirements upgrade review process

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#78]
There is repetitious work currently in the form of reviewing and merging Python requirements upgrade PR, try to come up with a way so we can automate this process (to some extent if not altogether). We can create a separate GitHub action that can be triggered after the upgrade job and can merge the PR if there is no major version upgrade and also tests are passing. Do come up with an approach and then get it reviewed by the team first.

**A/C**
- An approach for the team to review
- A demo PR to test that approach

**Comment by awais786** [comment]
This ticket is complete. Right now its in code review.

**Comment by jmbowman** [comment]
PR for the shared workflow: https://github.com/openedx/.github/pull/50
