### ISSUE TITLE
Update handling of arch-bom completed issues to improve reporting in github

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#792]
Tim's proposal: If we want to avoid the issue of archived Done issues not showing up in reports, we could switch to using a status. From Slack: « Make a status called "Done (archival)", exclude the status from our main board, move the archived Done items to that status and de-archive them.

Additional notes:
- We should get flow working first, before pulling items from archive.
- We should pull a couple of items from archive to test, before pulling lots.
- We only want to pull items that had "Status: Done" from archive. The rest shouldn't apply to us, and hopefully most of these do apply to our work.

**Comment by jristau1984** [comment]
Unarchiving puts an issue back in its previous status with no indicators at all.  I will have to add `status:done` to the query above.

**Comment by jristau1984** [comment]
I updated the board filter to exclude long term storage tickets.

**Comment by jristau1984** [comment]
I have tested the workflow, and everything seems well and good.  However, I do not know how to created an automated workflow that updates the status after 14 days.  I will discuss with the team and see if it is possible.

**Comment by jristau1984** [comment]
According to Gemini, this is not possible...

> GitHub Actions is a platform that allows users to automate workflows, including building, testing, and deploying pipelines. **_While there isn't a built-in way to change an issue's status based on age_**, you can use GitHub Actions to create workflows that perform other actions based on a variety of conditions:

**Comment by jristau1984** [comment]
Limiting the unarchive results to issues from Diana, Tim, Robert.  This is ~136 items, I will unarchive them and move all Done items to long term storage now.

**Comment by jristau1984** [comment]
I unarchived 136 tickets and moved 140 tickets to `Done - Long Term Storage`.  This enabled me to build a set of CFD related Insights graphs:
![Image](https://github.com/user-attachments/assets/d355daca-18b9-4f2a-ac9e-e8724c309d79)

`Done` tickets will need to be manually moved to the LTS status regularly, but the timing does not matter as CFDs are based on Completion timestamp not status timestamp.
