### ISSUE TITLE
Upgrade to Celery protocol 2

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#800]
edx-platform, registrar, and enterprise-catalog are all using Celery task protocol 1. Upgrading to protocol 2 may remove some technical debt, and as a side benefit may help with <https://github.com/edx/edx-arch-experiments/issues/692>. We also may have seen a bug where something in celery (or an associated library) was adding headers to a v1 message as if it were a v2 message, which caused a bug in ddtrace; such things may become more likely over time as code is written with the assumption of v2 messages.

Implementation:

- [x] Make protocol version configurable [[PR](https://github.com/openedx/edx-platform/pull/35789)]
- [x] Test in stage via Django setting [[PR 1](https://github.com/edx/edx-internal/pull/11862), [PR 2](https://github.com/edx/edx-internal/pull/11896)]
- [x] Roll out to edge, prod via Django setting [[edge](https://github.com/edx/edge-internal/pull/799), [prod](https://github.com/edx/edx-internal/pull/11929)]
- [x] Change default to 2 [[PR](https://github.com/openedx/edx-platform/pull/35865)]
- [x] Remove overrides from all envs [[stage](https://github.com/edx/edx-internal/pull/11954), [edge](https://github.com/edx/edge-internal/pull/801), [prod](https://github.com/edx/edx-internal/pull/11955)]
- [x] Document in Open edX release notes: https://openedx.atlassian.net/wiki/spaces/COMM/pages/4570710024/Next+Release+Teak+-+Operator+Dev+Notes
- [x] Inform owners of other relevant services that they should be able to safely upgrade
    - Titans: https://github.com/openedx/enterprise-catalog/blob/b0b2832046c6f83f0a4dee414f845286811aaf78/enterprise_catalog/celery.py#L11
    - Cosmonauts: https://github.com/edx/registrar/blob/51751e6e56b5b86b58ddfb2e2c849577c8175e3e/registrar/celery.py#L19

Notes:

- This can be identified by looking for `APP.conf.task_protocol = 1` in an IDA's celery config file [[edxapp example](https://github.com/openedx/edx-platform/blob/4e5a3b2db96c70a5cacb287ce754b20bfe3fc45b/openedx/core/lib/celery/__init__.py#L26), [added during celery 4 upgrade](https://github.com/openedx/edx-platform/pull/24916)]
- https://docs.celeryq.dev/en/stable/history/whatsnew-4.0.html doesn't mention anything about a stop-the-world aspect to the upgrade (just needing to get everything on 3.1.25 first) -- so this might be an easy rollout with no blue/green compatibility issues.
  - Asking for confirmation here: https://github.com/celery/celery/discussions/9400

**Comment by robrap** [comment]
@timmc-edx: Are you also planning on opening a github issue against celery if you think they are missing test coverage, and potentially have a bug around this?

**Comment by timmc-edx** [comment]
Unlikely. Too much of a rabbit hole to go down right now, unfortunately. (It's not even necessarily celery -- could be some other library that interacts with it.)

**Comment by robrap** [comment]
[inform] This work was scheduled because even though the issue will hopefully first have been fixed by DD in another way, this change will remove technical debt that would have avoided this situation altogether, and may help avoid future related situations.
