### ISSUE TITLE
OAuth config for partners API gateway

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#804]
The Red Ventures split/integration team has requested non-persona API access to edx.  Initial request in #tech-dev-edx: https://twou.slack.com/archives/C030CC8T40N/p1727260029450439

Create OAuth client/creds for new `partners-api` AWS API Gateway, similar to however https://github.com/edx/api-manager is set up.

- [x] PR to add new service user: https://github.com/edx/app-permissions/pull/2889
- [ ] ~~Configure any additional permissions for the service user~~
- [ ] ~~OAuth client credentials generated and handed off~~
- [x] Revert new service user (requested owning team to do the revert)

**Comment by robrap** [comment]
- I created client credentials, learned that the team decided on a different design, and deleted the new credentials.
- I asked the partner management team to rollback the api-permissions change with the new user when they are ready.
  - Marking as blocked, waiting for that revert, and hopefully ensuring that they know what they want. We can check in mid-to-late October if we want to ensure clean-up.

**Comment by robrap** [comment]
Confirmed that the owning team cleaned up the `partner_api_service_user` user. We can open a new ticket if this is needed again. In the meantime, this is being marked closed.
