### ISSUE TITLE
Arch-BOM PR review process updates

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#816]
See note at top of https://2u-internal.atlassian.net/wiki/spaces/AT/pages/16387065/On-Call+Arch-BOM#PR-Triage%2FReview for updated links.

- [x] Ensure process for OSPRs is correct. (@robrap is working on this, but in the meantime, I'd assume it is.)
- [x] Improve and document process for non-OSPR arch-bom owned PRs.

Notes:
- See the on-call doc for notes on how we might handled the non-OSPR arch-bom owned PRs.

**Comment by robrap** [comment]
I [DMed Michelle](https://twou.slack.com/archives/D05FXBBRXHD/p1728056243010629) (sorry this link isn't public), but it is just so I can check back if I fail to hear back, or fail to update this ticket.

**Comment by robrap** [comment]
@dianakhuang: Maybe part of this should spin off as a separate arbi-bom ticket, unless you just discuss and update.

**Comment by dianakhuang** [comment]
We are more concerned with the backlog of upgrade bot PRs that are piling up.  We will probably also need to create a separate stream of work around upgrades (arbi-bom) vs. other reviews(arch-bom).

**Comment by robrap** [comment]
Regarding the OSPR topic, I am taking the following as confirmation that this part is complete.

**Questions from Robert:**
> Here are some hopefully more clear questions/confirmations:
> 1. The [Contributions board](https://github.com/orgs/openedx/projects/19/views/22) is still where we should be looking for PRs that need our attention, correct?
>   - I think yes, but some of the views we used to use were removed, so I am just checking.
> 2. For new PRs, if they are against a repo my team owns, then you will add 2u-arch-bom as "Repo Owner / Owning Team".
>   - Confirming that that is the current process.
> 3. I had a question of the status we should pay attention to, but decided to watch for anything that is not "Done". The link I had provided in my initial question had some status buried in the filter, but we'll just watch all status for now.
> 4. Lastly, I believe you have a process for edx-platform with CCs and the new views that is working well enough for you? Or put another way, you are not expecting anything special on this front from my team that we aren't doing, right?

**Responses from Michelle P.:**
> 1. Yes, the [Contributions board](https://github.com/orgs/openedx/projects/19/views/22) is still where you should look. We cleaned up the views when the teams changed, but you can absolutely add an "arch-bom" view.
> 2. Yes - for new PRs, if they are against arch-bom, I will add 2u-arch-bom as "Repo Owner / Owning Team".
> 3. Re: the statuses, yes, anything that's not "Done" would be great. Tim and I do our best to make sure OSPRs have statuses up-to-date, but it takes a week or two for me to comb through all the ones I'm watching, so sometimes there are status changes that happen before Tim and I get to it (e.g. something might be ready for review, but not in that status yet because we haven't gotten back to it yet).
> 4. The edx-platform view is all we really have right now for CCs to see which OSPRs in that repo need review, and there's lots still needing a reviewer. Nothing specific that arch-bom needs to do, but if you or another arch-bom member are able to review anything that's there, please feel free to do so!

**Comment by robrap** [comment]
Unfortunately, we can only filter out one bot (based on author) at a time (e.g. `-author:edx-requirements-bot`). If I add two of these filters, github just drops one. An alternative is to add a `bot` label (which one of these bots uses) for all bot PRs, so we can filter in or out bots as needed.

**Comment by robrap** [comment]
@dianakhuang: I moved the arbi-bom bot process questions to the following issue. Feel free to update its text as you wish.
- https://github.com/edx/edx-arch-experiments/issues/826

The rest of this I have taken care of, so I am going to mark this ticket closed.
