### ISSUE TITLE
[Discovery] Cloud-based developer environments

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#82]
We currently have sandboxes and hosted devstack, which serve valuable needs but are mostly developed and maintained within 2U.  We should also consider using a 3rd-party tool for provisioning and managing cloud-based development environments that's actively maintained and improved by other technology companies, if this gets us a better developer experience and reduced maintenance/development cost.  Do some discovery on our options, and determine if any of them would serve as a better basis for future cloud environments than our current tooling.  Some nominations to include in the search:

* [Coder](https://coder.com/) - Terraform based, self-hosted, has an original production service and a new open source (AGPL 3.0) offering in beta testing. Can be deployed locally, but may be slow on M1 Macs.
* [DevSpace](https://www.devspace.sh/) - Apache 2.0-licensed tool for developing and deploying Kubernetes-based applications, either in a remote environment or in a local k8s instance (via Docker Desktop, Minikube, etc.)  Includes a CLI, management UI, file sync, hot reloading, etc.
* [Okteto](https://www.okteto.com/) - Apache 2.0-licensed tool (with commercial extras and hosting) for managing Kubernetes dev and preview environments.  Works with local or remote clusters, has a feature for auto-creating preview environments for PRs (which sounds nice but also potentially expensive).
* [Tilt](https://tilt.dev/) - Apache 2.0-licensed tool for managing Docker and/or Kubernetes based dev environments.  Recently acquired by Docker.
* [Gitpod](https://www.gitpod.io/) - Open source, very fast, but seems to assume that you only ever want a single Docker container?  There's a band-aid for this [using Tailscale to let multiple workspaces talk to each other](https://www.gitpod.io/guides/connect-multiple-repositories-using-tailscale), but the DX for this may not be great.
* [Codespaces](https://github.com/features/codespaces) - Proprietary GitHub offering that mainly integrates with Visual Code Studio.  Has some support now for running multiple services, but may resemble our old Vagrant approach of installing them all on a single VM's filesystem.
* Sandboxes - Currently multiple services installed into the same EC2 instance built from a Jenkins job
* Hosted devstack - docker-compose running in an EC2 instance
* Tutor cloud support - I think it currently just launches a pre-built AMI of the LMS?
 
A partial list of points to consider when comparing:

* Does it only work for remote environments, or does it also allow for local dev environments?
* Is there a fully free version of the tool available?
* Does it have explicit support for Kubernetes?  If so, does it help smooth the Kubernetes learning curve?
* Is it actively maintained, and likely to stay so for the foreseeable future?
* Is it just for dev environments, or does it help spin up preview environments for PRs or other sandbox-like use cases?
* Does it offer any functionality for varying combinations of services, or would we need something else to generate an appropriately customized service configuration input file?
* Does it work cleanly with Tutor and/or devstack, or largely replace the need for them?  If the latter, are there pieces we would still need from one or both of them?

Coder and Gitpod both have pages dedicated to comparing against each other and some other alternatives (although GitPod's read like sales pitches, often omitting Gitpod's downsides):

* https://coder.com/blog/coder-or-gitpod-which-is-better-for-your-team
* https://coder.com/blog/coder-the-github-codespaces-alternative
* https://www.gitpod.io/vs/coder
* https://www.gitpod.io/vs/github-codespaces
* https://www.gitpod.io/vs/jetbrains-space

Other pages potentially worth reviewing:

* https://thenewstack.io/devspace-designed-to-lower-the-kubernetes-learning-curve/
* https://loft.sh/blog/skaffold-vs-tilt-vs-devspace/

There's a 2U [ATAM](https://en.wikipedia.org/wiki/Architecture_tradeoff_analysis_method) (Architectural Tradeoff Analysis Method) [spreadsheet template](https://architecture.techdev.2u.com/decisions/index.html) that may (or may not) be useful in starting a comparison grid.

**Comment by timmc-edx** [comment]
Public-readable spreadsheet where I'm building up a comparison and taking notes: https://docs.google.com/spreadsheets/d/1OonpUduqL5tdEPte3mY605DcW00Q3u8W9sze2XB7fAY/edit

**Comment by timmc-edx** [comment]
Wiki page with summary and notes: https://openedx.atlassian.net/wiki/spaces/AC/pages/3647700997/Development+environment+notes

**Comment by jmbowman** [comment]
After discussing that summary, we decided that it would be useful to have a breakdown of what features we expect from a development environment, how devstack currently does those, how Tutor does them, which of them are currently handled at the level of individual service repositories, etc.  We hope this will guide us in figuring out:

* How much of what is currently done in devstack and Tutor can and/or should be done at the level of individual repositories instead, so it can be leveraged regardless of the chosen orchestration/deployment system?
* Which of these features can realistically be supported agnostic of a docker-compose vs. Kubernetes choice, rather than needing to be duplicated for each option?
* What would leveraging one of the tools in this ticket potentially gain us, and which aspects of the development environment would be largely unchanged (or need to be reworked without significant gain) by the choice?

A first draft of such a breakdown and comparison is at https://docs.google.com/spreadsheets/d/1XAipznjIcTaE2H454M74No2Ro_9VftbolfV4YVv-B9I/edit#gid=0 .  Please let us know in either comments there or this thread if you have suggestions for fleshing out and/or reframing this analysis.

**Comment by timmc-edx** [comment]
@jmbowman I extracted your comment to a new ticket https://github.com/edx/edx-arch-experiments/issues/203 -- maybe we can close this one out and put the new one in the appropriate projects?

**Comment by timmc-edx** [comment]
Added to projects; @rgraber will add new issue to dev env wg board.

**Comment by loujaybee** [comment]
@timmc-edx , @rgraber, @jmbowman - My name is Lou, and I'm a Product Manager at Gitpod. Are you still looking into this? I recently compiled some similar research on [Kubernetes Local vs Remote solutions](https://www.gitpod.io/blog/kubernetes-local-remote) (see below table from blog). As I was prepping for a webinar about [Kubernetes and Developer Experience](https://www.gitpod.io/webinars/adopt-kubernetes-for-platform). I'd love to have an [open chat about your findings](https://calendly.com/lou-gitpod/chat), as you seem like you went very thorough. Happy to share notes—I have no interest in "selling" you anything, would just love to chat ! [Find me on Twitter](https://twitter.com/loujaybee) too if you want. 

![image](https://github.com/edx/edx-arch-experiments/assets/5528307/414762d2-2295-43ae-ab89-fbc46eb290f2)
