### ISSUE TITLE
Migrate old flaky test tickets to github

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#827]
A/C:

- [x] List of unresolved flaky tests in Jira is empty: https://2u-internal.atlassian.net/issues/?filter=10600 (`resolution is EMPTY AND labels = flaky_test ORDER BY created DESC`) -- 21 here as of 2024-10-11.
- [x] GitHub issues are discoverable, e.g. via a label: [flaky-test](https://github.com/openedx/edx-platform/labels/flaky-test)
- [x] [Flaky Test Process](https://openedx.atlassian.net/wiki/spaces/AC/pages/4306337795/Flaky+Test+Process) is fully updated to refer to the GitHub process

**Comment by timmc-edx** [comment]
I think I'm done migrating old issues -- the only ones remaining in CR are in ecommerce or edx-e2e-tests, not edx-platform. There are also some LEARNER tickets but they don't appear to be relevant to this flaky test process.

**Comment by timmc-edx** [comment]
I went through a broader set of tickets and established that everything has been either moved or wasn't relevant (such as individually deleted bokchoy tests).
