### ISSUE TITLE
Retire macos-12 in github actions

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#831]
Github provided Dec, 3 deadline for retiring use of macos-12 in github actions. We have one use in devstack.

An attempted fix was made in this PR, but it has not worked yet:
- https://github.com/edx/devstack/pull/52

**Comment by jristau1984** [comment]
Adding to Arbi-BOM board to bring in next.

**Comment by jristau1984** [comment]
Metadata from Arch-BOM project: This is due Dec 3, 2024.
