### ISSUE TITLE
[Discovery] Engineering metrics & dashboards

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#84]
A/C

- [ ] Determine and document a concrete set of metrics we will use to evaluate developer environments
- [ ] Use these metrics to create a rubric for these evaluations
- [ ] Determine which of the tools below will be most useful in collecting these metrics. Make separate issues as needed for making prototypes using 2-3 of the most likely options

It's much easier to make good decisions about software engineering processes once you have appropriate metrics and visualizations.  Doing these manually can eat up a lot of time, but there's now a pile of tools available that claim to do much of the work automatically.  Look into these, figure out which features might be most useful for us, and narrow down to maybe 2-3 candidates for a more in-depth evaluation.  Some tools in this space that I'm aware of:

* [Swarmia](https://www.swarmia.com/)
* [Jellyfish](https://jellyfish.co/)
* [Keypup](https://www.keypup.io/)
* [Screenful Dashboards for GitHub](https://screenful.com/github/dashboards-for-github)
* [GitHub Metrics](https://github.com/lowlighter/metrics)
* [Athenian](https://athenian.com/)
* [DX](https://getdx.com/)
* [Okay](https://www.okayhq.com/)

Some of these tools definitely aren't solving quite the same problem, and it's possible that we could use 2 or more of them effectively.  But we should probably try to figure out which one we think we'd gain the most value from and start there.

In terms of the actual metrics to use, here are some that I've seen suggested as good choices:

* NPS (Net Promoter Score)
* Accelerate (from the book of the same title, recent book club)
* DORA (DevOps Research and Assessments)

A very recent addition in this area is the [SPACE](https://queue.acm.org/detail.cfm?id=3454124) (Satisfaction & Well-being, Performance, Activity, Communication & Collaboration, Efficiency & Flow) framework developed by a team led by one of the Accelerate authors.  The Swarmia blog (which gets good feedback in the LeadDev Slack for posting insightful articles) has a [write-up on it](https://www.swarmia.com/blog/space-framework/).

**Comment by jmbowman** [comment]
For what it's worth, a mentor in the Plato program from Slack recommended starting with the DORA metrics and then moving on to "how long does it take developers to do specific common tasks?" style metrics.

**Comment by rgraber** [comment]
This has been split into new issues after creating https://docs.google.com/spreadsheets/d/1SH7B8YOHArkKp7OF4qPnUuh2Rit_syVaOfjbbFWqmXw/edit#gid=0
