### ISSUE TITLE
Remove waffle switch data for block_structure.storage_backing_for_cache

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#848]
The removal of waffle switch `block_structure.storage_backing_for_cache` landed on Nov 6: https://github.com/openedx/edx-platform/pull/35185/

I want to give this some burn-in time, but after Dec 6+, we should remove the data from all environments: Stage, Edge, Prod.

Note: I think in Stage there is an extra space at the end.

**Comment by jristau1984** [comment]
Dec 9 date has arrived!

**Comment by timmc-edx** [comment]
Completed.
