### ISSUE TITLE
Periodic support windows doc updates

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#85]
We have a [support windows](https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733) document which helps us track upcoming major upgrades.  It's auto-generated from a data file by a script, but the actual data file updates are done manually, and this has been pretty ad-hoc so far.  Schedule a [recurring GitHub Issue](https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation) to update the data accordingly:

* Update the version of each dependency currently in use, if necessary
* Delete any versions older than one prior to the one currently in use
* Add end dates which were not previously known
* Add new releases that we're likely to consider upgrading to
* Do a quick review of our dependencies to see if any categories should be added or removed

A quarterly schedule should be frequent enough; the end of the quarter may be ideal if practical, as that would encourage updates shortly after named Open edX releases.  The issue should at least notify the Arbi-BOM team when created, perhaps even auto-add itself to the Arbi-BOM project board if that doesn't require much additional effort.  The generated issue description should include a link to documentation for the process, including a mention of https://endoflife.date/ which is often a good reference for the necessary information.

Finally, as of this writing the data for Ruby 2.5 and 2.6 EOL is stale, the support windows have already ended: https://endoflife.date/ruby (which is what prompted me to write this issue).  If not fixed by the time you start working on this, please update the Ruby data, including addition of entries for 2.7, 3.0, and 3.1.  Check https://github.com/openedx/cs_comments_service/pull/392 to see if there are any updates in the version we currently use.

**Comment by jmbowman** [comment]
The MongoDB support windows are out of date, and the 4.2 series we currently use goes out of support in April: https://www.mongodb.com/support-policy/lifecycles .  Please update the doc accordingly.

**Comment by UsamaSadiq** [comment]
Plan of Action: 
- Compare all the current versions' end of life with the versions mentioned in the sheet.
- Update the `repo_tools/barcalendar.py` script to reflect new dates.
- Add a workflow to automatically create a GitHub issue on quarterly basis to remind the `arbi-bom` team for updating the data of the `Support Windows` sheet.

**Comment by UsamaSadiq** [comment]
Created first PR https://github.com/openedx/repo-tools/pull/334 to update the sheet entries according to the respective `endoflife` documents for each tool.

**Comment by UsamaSadiq** [comment]
Merged the PR with all the updated details but I don't have edit access to the sheet so I can't update the chart. 
Continuing on writing the workflow to create recurring issues every quarter to update the data.

FYI @jmbowman, could you update the sheet data manually? or if arbi-bom is going to be maintaining this sheet in the future, then it'll probably be best if arbi-bom gets access to this sheet with edit access as well.

**Comment by jmbowman** [comment]
I just gave you and the rest of the team edit access.

**Comment by UsamaSadiq** [comment]
Updated the sheet data with the new information. Verified the versions of `mongoDB` and `Ruby` to be updated as per the changes.

**Comment by UsamaSadiq** [comment]
Created PR https://github.com/openedx/repo-tools/pull/337 to add workflow. 
Tested the workflow to be working successfully for creating issues within the repository but fails to add the issue to project board.
