### ISSUE TITLE
Remove migrate from discovery consumers

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#88]
Acceptance Criteria:

- [x] Remove `./manage migrate` from discovery consumer.
- [x] Double-check that the pipeline itself doesn't run migrations.
- [x] Document decision (not ADR) to have migrations fully managed by main service pipeline, and runbook implications for deploying the consumer, and handling consumer rollbacks related to migrations.

Additional thoughts:

* Docs for k8s pipelines don't have good notes on how and when migrations happen and/or are rolled back. This ultimately shouldn't affect this pipeline, but it would be nice to have what we learn documented.
*Create or update a doc (even if imperfect) for deployment notes. Could be a new Confluence doc that Phoenix can move wherever they want.
* Note that any decision around this is for edx.org only, and tied to our deployment structure.

**Comment by timmc-edx** [comment]
Implemented by https://github.com/edx/edx-internal/pull/7373
