### ISSUE TITLE
[infra] Naming for course-discovery k8s infrastructure

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#89]
AC:
Update docs as needed:
* Add notes for considerations when answering the k8s-bootstrap-tool questions.
* Consider names like "event-consumer" or "consumer-worker" vs "celery-worker", rather than just "worker", unless it represents both.

The rest of this are notes to consider.

Note: this is only partially an Event Bus ticket, because discovery in k8s was introduced as part of the Event Bus work.

When the k8s infrastructure was added, it used "course-discovery" in many places that were formerly known as "discovery". This ticket is about investigating and adjusting names as makes sense.

Notes:
* In the legacy names, the repo was called "course-discovery", but the old GoCD pipeline and New Relic app and domain names for the service all used the term "discovery".
* The GoCD pipeline for k8s is different from the old "discovery" pipeline for AWS instances. It requires a different name. It is currently "course-discovery", which doesn't really indicate what would be found where. Naming it "discovery-consumers" would work in the short-term, but not when and if all of discovery were deployed through k8s.
  * Here is the generated-pipeline: https://github.com/edx/edx-internal/blob/master/gocd/generated-pipelines/output/course-discovery.yaml. I'm not sure what this is generated from.
* The argocd application (for k8s) is named "course-discovery". It is unclear what the right name for it should be short-term or long-term.
* At least one name in the files that has significance is the name of [the New Relic application name, found in the argcd config here](https://github.com/edx/edx-internal/blob/1c78cd839280e880d7feda9ce78c8c90d21b3818/argocd/applications/course-discovery/prod-config.yaml#L71). It was updated from "prod-edx-course-discovery" to "prod-edx-discovery", but now the consumer activity is going to the same New Relic app as the rest of discovery. It could easily be renamed to "prod-edx-discovery-consumers" (or any other name to separate out traffic), but I think this name would apply to all k8s discovery clusters, unless the argocd config enabled different New Relic config for each cluster.

**Comment by robrap** [comment]
@DawoudSheraz: Not sure if you have any feelings on this. The one part that we could do sooner rather than later is the New Relic name, depending on your thoughts.

**Comment by DawoudSheraz** [comment]
I like the idea of having `-consumers` in the name, as it is much clearer in the context. I suspect the naming convention will follow for future event bus implementations. Maybe an explicit consistent postfix like `-event-consumer` across all the places would work. 
Out of curiosity; what will be planned for the future when the event bus is expanded? Will there always be an "old" pipeline and a consumer-focused (k8s) pipeline?

**Comment by robrap** [comment]
@DawoudSheraz: Sorry I forgot to reply to this. 

Short term, the consumers are in k8s and the service is on AWS instances. I propose keeping them separate in New Relic for now to help clarify this difference, but that is up to your team.

Long term, once everything is in k8s, you'll have a separate decision to make. The current argocd config doesn't yet allow for different New Relic configs for each environment (service vs celery workers vs event consumers), but I think it should. With shared config, all of these will go to a single New Relic app, which is the default of what will happen. If someone enhances the config capabilities, you'd be able to split or keep together as you see fit.

**Comment by robrap** [comment]
* In the how-to doc, we will describe how one should complete the bootstrap-k8s-tool questions.
* Other than that, we will close this ticket and Phoenix can determine when and if to rename various pieces, including New Relic app names (and separation, if wanted).
