### ISSUE TITLE
Review and clean up newly owned XBlocks

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#91]
The following XBlocks have had their ownership transferred from the new-defunct Community Engineering group to Arbi-BOM:

| Command | usage count | pypi release | deployed on prod |
| --------------------------- | ------------------------ |------------------------ |------------------------ |
| [acclaimbadge-xblock](https://github.com/edx/edx-arch-experiments/issues/96) | 175 | :heavy_check_mark: | :heavy_check_mark: |
| [acid-xblock](https://github.com/edx/edx-arch-experiments/issues/97)| 0 | already published | :heavy_check_mark: |
| [AnimationXBlock](https://github.com/edx/edx-arch-experiments/issues/95)| 0 | :heavy_check_mark: | :heavy_check_mark: | 
| [AudioXBlock](https://github.com/edx/edx-arch-experiments/issues/100)| 0 | :heavy_check_mark: | :heavy_check_mark: | 
| [ConceptXBlock](https://github.com/edx/edx-arch-experiments/issues/101)| 0 | :heavy_check_mark: | :heavy_check_mark: | 
| [crowdsourcehinter](https://github.com/edx/edx-arch-experiments/issues/102)| 0 | already published |   :heavy_check_mark: |
| [DoneXBlock](https://github.com/edx/edx-arch-experiments/issues/103)| 336 | already published | :heavy_check_mark: |
| [RecommenderXBlock](https://github.com/edx/edx-arch-experiments/issues/104)| 209 | already published | :heavy_check_mark: |
| [schoolyourself-xblock](https://github.com/edx/edx-arch-experiments/issues/105) | 6  | :heavy_check_mark: | :heavy_check_mark: | 
| [staff_graded-xblock](https://github.com/edx/edx-arch-experiments/issues/106) | 266 | already published | :heavy_check_mark: |
| [xblock-free-text-response](https://github.com/edx/edx-arch-experiments/issues/107) | 50  | :heavy_check_mark: | :heavy_check_mark: | 
| [xblock-image-modal](https://github.com/edx/edx-arch-experiments/issues/108)  | 1 | :heavy_check_mark: | :heavy_check_mark: |
| [xblock-in-video-quiz](https://github.com/edx/edx-arch-experiments/issues/109) | 18  | :heavy_check_mark: | :heavy_check_mark: | 
| [xblock-qualtrics-survey](https://github.com/edx/edx-arch-experiments/issues/110) | 100 | :heavy_check_mark: | :heavy_check_mark: | 
| [xblock-sql-grader](https://github.com/edx/edx-arch-experiments/issues/111) | 14 | :heavy_check_mark: | :heavy_check_mark: | 
| [xblock-submit-and-compare](https://github.com/edx/edx-arch-experiments/issues/112) | 20 | :heavy_check_mark: | :heavy_check_mark: | 

For each of these, please:

* Document the extent of current usage on edx.org, as indicated by CourseGraph.
* Determine if we might be able to deprecate it (low usage or obvious replacement), and if so reach out to the DEPR working group for assistance in kicking that off.
* Release it on PyPI and switch to installing it from there, if this has not already been done
* If deprecation seems unlikely, ticket work to get them in a better state of repair (add missing test suites, update CI matrices, other low-hanging fruit indicated by repo health checks)

**Comment by awais786** [comment]
Major work already done and deployed. Next task is to add some tests.
