### ISSUE TITLE
Replace MemcachedCache with PyMemcacheCache

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#92]
As of Django 3.2, MemcachedCache is deprecated and PyMemcacheCache is the officially-supported library for caching with Memcache in Django apps. We should switch all our applications to use the new library. 

The only migration guide I could find is here: https://jugmac00.github.io/blog/bye-bye-python-memcached-hello-pymemcache/ . It seems the new memcached library has some differences in syntax, and also requires more explicit error handling.

```[tasklist]
### Tasks
- [ ] https://github.com/edx/edx-arch-experiments/issues/357
```

**Comment by jmbowman** [comment]
Another point that I called out in the [Django 3.2 Key Changes](https://openedx.atlassian.net/wiki/spaces/AC/pages/3066626061/Django+3.2+Upgrade+Key+Changes) doc:

> Cache operations were updated to no longer treat `None` the same as a cache miss, but the python-memcached library we currently use doesn’t support this and is being deprecated; we’ll want to switch to one of two alternatives. [[Changelog entry](https://docs.djangoproject.com/en/3.2/releases/3.2/#miscellaneous)]

Dave Ormsbee pointed out in a comment there that we may need to enhance some of the caching logic in edx-django-utils as part of switching over.

Also, there hasn't been a release of python-memcached (which we currently use) in nearly 5 years...

**Comment by iamsobanjaved** [comment]
We are done with the platform, created tickets for other services in the Arbi-BOM board. Hence closing this one.
