### ISSUE TITLE
edxapp devstack image job is broken

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#94]
The lms/studio devstack images haven't been updated since early October 2022. The Jenkins job has been failing: https://tools-edx-jenkins.edx.org/job/DockerCI/job/image-builders/job/edxapp-image-builder/

A/C:

- [x] Get lms/studio (`edxapp`) image builder job working again
- [x] Check if other devstack builds are also broken
- [ ] Ensure job failures alert someone

**Comment by aht007** [comment]
Made a potential fix PR: https://github.com/openedx/configuration/pull/6840/files
And also made an [SRE ticket](https://2u-internal.atlassian.net/servicedesk/customer/portal/15/DOS-3493) for investigation and review of the PR

**Comment by aht007** [comment]
Images are being built successfully now.

**Comment by timmc-edx** [comment]
Wonderful, thank you! Looks like ecommerce is still busted, but I know that service is deprecated and probably isn't going to get any attention from that team.

Could we have these send failures to an email address or Opsgenie so that we know sooner next time? I imagine these jobs generally don't get looked at very often otherwise.

**Comment by aht007** [comment]
Added notifications for job failures.
https://github.com/edx/jenkins-job-dsl/pull/1633
