### ISSUE TITLE
Create baseline alerting for event bus metrics

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#98]
Create arch-bom alerts and associated runbooks to help monitor the health of the event bus on both stage and prod. 

Suggested alerts:
Producer throughput floor.
Consumer latency.
Consumer throughput floor
Errors in logs

Runbook(s) should note that these are all early alerting for awareness, and can be tuned as needed when firing.

**Comment by rgraber** [comment]
Blocking until we go to prod and have better data to look at to determine the correct alert conditions.

**Comment by robrap** [comment]
Thanks for this work @rgraber. I'm done reviewing and closing this ticket.
